export declare const n500px: string[];
export declare const aboutMe: string[];
export declare const abstract: string[];
export declare const accusoft: string[];
export declare const acm: string[];
export declare const acquisitionsIncorporated: string[];
export declare const addthis: string[];
export declare const adguard: string[];
export declare const adn: string[];
export declare const adobeAcrobatReader: string[];
export declare const adobeAfterEffects: string[];
export declare const adobeAudition: string[];
export declare const adobeCreativeCloud: string[];
export declare const adobeDreamweaver: string[];
export declare const adobeIllustrator: string[];
export declare const adobeIndesign: string[];
export declare const adobeLightroomcc: string[];
export declare const adobeLightroomclassic: string[];
export declare const adobePhotoshop: string[];
export declare const adobePremiere: string[];
export declare const adobeTypekit: string[];
export declare const adobeXd: string[];
export declare const adobe: string[];
export declare const adversal: string[];
export declare const affiliatetheme: string[];
export declare const airbnb: string[];
export declare const algolia: string[];
export declare const alipay: string[];
export declare const allocine: string[];
export declare const amazonAws: string[];
export declare const amazonPay: string[];
export declare const amazon: string[];
export declare const amd: string[];
export declare const americanExpress: string[];
export declare const amilia: string[];
export declare const anaconda: string[];
export declare const analogue: string[];
export declare const androidAlt: string[];
export declare const android: string[];
export declare const angellist: string[];
export declare const angrycreative: string[];
export declare const angularUniversal: string[];
export declare const angular: string[];
export declare const ansible: string[];
export declare const apacheAirflow: string[];
export declare const apacheFlink: string[];
export declare const apacheSpark: string[];
export declare const apache: string[];
export declare const appStore: string[];
export declare const apper: string[];
export declare const applePay: string[];
export declare const apple: string[];
export declare const appveyor: string[];
export declare const aral: string[];
export declare const archLinux: string[];
export declare const archiveOfOurOwn: string[];
export declare const arduino: string[];
export declare const artstation: string[];
export declare const arxiv: string[];
export declare const asana: string[];
export declare const asymmetrik: string[];
export declare const atAndT: string[];
export declare const atlassian: string[];
export declare const atom: string[];
export declare const audible: string[];
export declare const aurelia: string[];
export declare const auth0: string[];
export declare const automatic: string[];
export declare const autoprefixer: string[];
export declare const autotask: string[];
export declare const aventrix: string[];
export declare const avianex: string[];
export declare const aviato: string[];
export declare const aws: string[];
export declare const azureArtifacts: string[];
export declare const azureDevops: string[];
export declare const azurePipelines: string[];
export declare const babel: string[];
export declare const baidu: string[];
export declare const bamboo: string[];
export declare const bancontact: string[];
export declare const bandcamp: string[];
export declare const basecamp: string[];
export declare const bathasu: string[];
export declare const battleNet: string[];
export declare const beats: string[];
export declare const behance: string[];
export declare const bigCartel: string[];
export declare const bimobject: string[];
export declare const bing: string[];
export declare const bit: string[];
export declare const bitbucket: string[];
export declare const bitcoin: string[];
export declare const bitdefender: string[];
export declare const bitly: string[];
export declare const bity: string[];
export declare const blackTie: string[];
export declare const blackberry: string[];
export declare const blender: string[];
export declare const blogger: string[];
export declare const bluetoothB: string[];
export declare const bluetooth: string[];
export declare const boeing: string[];
export declare const boost: string[];
export declare const bootstrap: string[];
export declare const bower: string[];
export declare const brandAi: string[];
export declare const brandSet: {
    "500px": string[];
    "aboutMe": string[];
    "abstract": string[];
    "accusoft": string[];
    "acquisitionsIncorporated": string[];
    "acm": string[];
    "addthis": string[];
    "adguard": string[];
    "adn": string[];
    "adobeAcrobatReader": string[];
    "adobeAfterEffects": string[];
    "adobeCreativeCloud": string[];
    "adobeDreamweaver": string[];
    "adobeAudition": string[];
    "adobeLightroomcc": string[];
    "adobeLightroomclassic": string[];
    "adobeIllustrator": string[];
    "adobePhotoshop": string[];
    "adobeIndesign": string[];
    "adobePremiere": string[];
    "adobeXd": string[];
    "adobeTypekit": string[];
    "adobe": string[];
    "adversal": string[];
    "airbnb": string[];
    "algolia": string[];
    "alipay": string[];
    "affiliatetheme": string[];
    "amazonAws": string[];
    "allocine": string[];
    "amazonPay": string[];
    "amazon": string[];
    "amd": string[];
    "americanExpress": string[];
    "amilia": string[];
    "anaconda": string[];
    "androidAlt": string[];
    "analogue": string[];
    "angellist": string[];
    "android": string[];
    "angularUniversal": string[];
    "angrycreative": string[];
    "ansible": string[];
    "angular": string[];
    "apacheAirflow": string[];
    "apache": string[];
    "apacheSpark": string[];
    "apper": string[];
    "appStore": string[];
    "apple": string[];
    "applePay": string[];
    "appveyor": string[];
    "aral": string[];
    "archiveOfOurOwn": string[];
    "archLinux": string[];
    "asana": string[];
    "arxiv": string[];
    "artstation": string[];
    "arduino": string[];
    "asymmetrik": string[];
    "atAndT": string[];
    "atlassian": string[];
    "atom": string[];
    "audible": string[];
    "auth0": string[];
    "aurelia": string[];
    "automatic": string[];
    "autoprefixer": string[];
    "autotask": string[];
    "aviato": string[];
    "aventrix": string[];
    "aws": string[];
    "avianex": string[];
    "azureArtifacts": string[];
    "azureDevops": string[];
    "azurePipelines": string[];
    "baidu": string[];
    "bamboo": string[];
    "bandcamp": string[];
    "bancontact": string[];
    "basecamp": string[];
    "battleNet": string[];
    "bathasu": string[];
    "beats": string[];
    "bigCartel": string[];
    "behance": string[];
    "bimobject": string[];
    "bing": string[];
    "bitbucket": string[];
    "bit": string[];
    "bitdefender": string[];
    "bitcoin": string[];
    "bity": string[];
    "blackTie": string[];
    "blackberry": string[];
    "bitly": string[];
    "blogger": string[];
    "blender": string[];
    "bluetoothB": string[];
    "bluetooth": string[];
    "bootstrap": string[];
    "bower": string[];
    "boost": string[];
    "boeing": string[];
    "brandAi": string[];
    "brave": string[];
    "buddy": string[];
    "btc": string[];
    "buymeacoffee": string[];
    "buffer": string[];
    "buzzfeed": string[];
    "buromobelexperte": string[];
    "buysellads": string[];
    "cakephp": string[];
    "c": string[];
    "campaignMonitor": string[];
    "canadianMapleLeaf": string[];
    "cashapp": string[];
    "ccAmazonPay": string[];
    "canva": string[];
    "castorama": string[];
    "cassandra": string[];
    "castro": string[];
    "ccApplePay": string[];
    "ccJcb": string[];
    "ccDinersClub": string[];
    "ccAmex": string[];
    "ccMastercard": string[];
    "ccDiscover": string[];
    "ccStripe": string[];
    "ccVisa": string[];
    "ccPaypal": string[];
    "centos": string[];
    "cevo": string[];
    "chase": string[];
    "centercode": string[];
    "chrome": string[];
    "chef": string[];
    "circleCi": string[];
    "chromecast": string[];
    "clockify": string[];
    "civicrm": string[];
    "cirrusci": string[];
    "clojure": string[];
    "cloudscale": string[];
    "cloudbees": string[];
    "cloudflare": string[];
    "cisco": string[];
    "cloudsmith": string[];
    "cloudversify": string[];
    "circle": string[];
    "cmake": string[];
    "codacy": string[];
    "coOp": string[];
    "codecademy": string[];
    "codeclimate": string[];
    "codefactor": string[];
    "codecov": string[];
    "codeforces": string[];
    "codeigniter": string[];
    "codesandbox": string[];
    "codepen": string[];
    "codeship": string[];
    "coderwall": string[];
    "codiepie": string[];
    "codio": string[];
    "coffeescript": string[];
    "commonworkflowlanguage": string[];
    "compropago": string[];
    "conekta": string[];
    "condaForge": string[];
    "connectdevelop": string[];
    "confluence": string[];
    "cpanel": string[];
    "contao": string[];
    "coveralls": string[];
    "coursera": string[];
    "cplusplus": string[];
    "creativeCommonsBy": string[];
    "creativeCommonsNcEu": string[];
    "creativeCommonsNcJp": string[];
    "creativeCommonsNc": string[];
    "creativeCommonsPdAlt": string[];
    "creativeCommonsNd": string[];
    "creativeCommonsPd": string[];
    "creativeCommonsSa": string[];
    "creativeCommonsSamplingPlus": string[];
    "creativeCommonsRemix": string[];
    "creativeCommonsShare": string[];
    "creativeCommonsSampling": string[];
    "crunchbase": string[];
    "creativeCommonsZero": string[];
    "criticalRole": string[];
    "creativeCommons": string[];
    "crunchyroll": string[];
    "css3Alt": string[];
    "css3": string[];
    "csswizardry": string[];
    "dAndDBeyond": string[];
    "cuttlefish": string[];
    "d3DotJs": string[];
    "dAndD": string[];
    "dailymotion": string[];
    "dashcube": string[];
    "dblp": string[];
    "dassaultsystemes": string[];
    "dazn": string[];
    "debian": string[];
    "dashlane": string[];
    "deepin": string[];
    "delicious": string[];
    "dell": string[];
    "deno": string[];
    "deezer": string[];
    "deploydog": string[];
    "dependabot": string[];
    "designernews": string[];
    "deskpro": string[];
    "devTo": string[];
    "devrant": string[];
    "dhl": string[];
    "deviantart": string[];
    "diaspora": string[];
    "digg": string[];
    "digitalocean": string[];
    "digitalOcean": string[];
    "discourse": string[];
    "discord": string[];
    "discover": string[];
    "disqus": string[];
    "disroot": string[];
    "django": string[];
    "docker": string[];
    "dochub": string[];
    "docusign": string[];
    "dotNet": string[];
    "draft2digital": string[];
    "draugiemDotLv": string[];
    "drone": string[];
    "dribbble": string[];
    "drupal": string[];
    "dropbox": string[];
    "duckduckgo": string[];
    "dtube": string[];
    "dyalog": string[];
    "dynatrace": string[];
    "earlybirds": string[];
    "ebay": string[];
    "edge": string[];
    "eclipseide": string[];
    "elastic": string[];
    "elasticcloud": string[];
    "elasticsearch": string[];
    "electron": string[];
    "elasticstack": string[];
    "elementor": string[];
    "elementary": string[];
    "eleventy": string[];
    "ello": string[];
    "ember": string[];
    "emlakjet": string[];
    "empire": string[];
    "envira": string[];
    "envato": string[];
    "epson": string[];
    "esea": string[];
    "erlang": string[];
    "eslint": string[];
    "empirekred": string[];
    "ethereum": string[];
    "eventbrite": string[];
    "etsy": string[];
    "evernote": string[];
    "eventstore": string[];
    "exercism": string[];
    "everplaces": string[];
    "evry": string[];
    "expeditedssl": string[];
    "expo": string[];
    "expertsexchange": string[];
    "eyeem": string[];
    "fSecure": string[];
    "facebook": string[];
    "facebookMessenger": string[];
    "facebookF": string[];
    "fandango": string[];
    "feathub": string[];
    "faceit": string[];
    "fantasyFlightGames": string[];
    "favro": string[];
    "fedex": string[];
    "feedly": string[];
    "figma": string[];
    "fedora": string[];
    "filezilla": string[];
    "fidoalliance": string[];
    "firebase": string[];
    "firstOrderAlt": string[];
    "firstdraft": string[];
    "firstOrder": string[];
    "firefox": string[];
    "fitbit": string[];
    "flattr": string[];
    "flickr": string[];
    "flipboard": string[];
    "flutter": string[];
    "fontAwesomeAlt": string[];
    "fly": string[];
    "forumbee": string[];
    "fnac": string[];
    "freeCodeCamp": string[];
    "freebsd": string[];
    "framer": string[];
    "freecodecamp": string[];
    "fulcrum": string[];
    "furaffinity": string[];
    "furrynetwork": string[];
    "galacticRepublic": string[];
    "galacticSenate": string[];
    "garmin": string[];
    "gatsby": string[];
    "genius": string[];
    "gauges": string[];
    "getPocket": string[];
    "geocaching": string[];
    "gg": string[];
    "gentoo": string[];
    "ggCircle": string[];
    "gimp": string[];
    "ghost": string[];
    "github": string[];
    "git": string[];
    "githubAlt": string[];
    "gitkraken": string[];
    "gitea": string[];
    "gitlab": string[];
    "gitpod": string[];
    "gitter": string[];
    "glassdoor": string[];
    "glide": string[];
    "gmail": string[];
    "glideG": string[];
    "gnusocial": string[];
    "glitch": string[];
    "gnuprivacyguard": string[];
    "go": string[];
    "godotengine": string[];
    "gofore": string[];
    "gogCom": string[];
    "goodreadsG": string[];
    "goldenline": string[];
    "googleAllo": string[];
    "goodreads": string[];
    "googleAds": string[];
    "googleAnalytics": string[];
    "googleDrive": string[];
    "googleHangouts": string[];
    "googlePay": string[];
    "googlePodcasts": string[];
    "googleHangoutschat": string[];
    "googleCloud": string[];
    "googleKeep": string[];
    "googleScholar": string[];
    "googlePlay": string[];
    "googleWallet": string[];
    "google": string[];
    "govUk": string[];
    "gradle": string[];
    "graphcool": string[];
    "grafana": string[];
    "graphql": string[];
    "grav": string[];
    "gravatar": string[];
    "greenkeeper": string[];
    "gratipay": string[];
    "groupon": string[];
    "gripfire": string[];
    "groovy": string[];
    "grunt": string[];
    "gulp": string[];
    "gumtree": string[];
    "gumroad": string[];
    "hackaday": string[];
    "habr": string[];
    "hackerone": string[];
    "hackerrank": string[];
    "hackster": string[];
    "hackhands": string[];
    "hashnode": string[];
    "hackerearth": string[];
    "hatenabookmark": string[];
    "happycow": string[];
    "haskell": string[];
    "haxe": string[];
    "hackerNews": string[];
    "here": string[];
    "heroku": string[];
    "helm": string[];
    "highly": string[];
    "hexo": string[];
    "hireAHelper": string[];
    "hockeyapp": string[];
    "hipchat": string[];
    "hips": string[];
    "hitachi": string[];
    "homify": string[];
    "hooli": string[];
    "hornbill": string[];
    "hotjar": string[];
    "hootsuite": string[];
    "houzz": string[];
    "hp": string[];
    "htmlacademy": string[];
    "huawei": string[];
    "html5": string[];
    "hubspot": string[];
    "humblebundle": string[];
    "hulu": string[];
    "hurriyetemlak": string[];
    "ibm": string[];
    "iata": string[];
    "icloud": string[];
    "iconjar": string[];
    "icq": string[];
    "ifixit": string[];
    "ideal": string[];
    "indeed": string[];
    "imdb": string[];
    "instacart": string[];
    "inkscape": string[];
    "instagram": string[];
    "instapaper": string[];
    "intel": string[];
    "intellijidea": string[];
    "internetExplorer": string[];
    "intercom": string[];
    "invision": string[];
    "ionic": string[];
    "issuu": string[];
    "internetexplorer": string[];
    "ioxhost": string[];
    "itunesNote": string[];
    "jabber": string[];
    "itchDotIo": string[];
    "itchIo": string[];
    "itunes": string[];
    "java": string[];
    "javascript": string[];
    "jekyll": string[];
    "jenkins": string[];
    "jetbrains": string[];
    "jediOrder": string[];
    "jest": string[];
    "joget": string[];
    "jira": string[];
    "jet": string[];
    "joomla": string[];
    "jquery": string[];
    "jsdelivr": string[];
    "json": string[];
    "justgiving": string[];
    "jupyter": string[];
    "kaios": string[];
    "kaggle": string[];
    "kaspersky": string[];
    "jsfiddle": string[];
    "keras": string[];
    "kentico": string[];
    "keybase": string[];
    "keycdn": string[];
    "khanacademy": string[];
    "kibana": string[];
    "kirby": string[];
    "klout": string[];
    "kik": string[];
    "koFi": string[];
    "kodi": string[];
    "known": string[];
    "koding": string[];
    "kickstarter": string[];
    "kotlin": string[];
    "korvue": string[];
    "kubernetes": string[];
    "lanyrd": string[];
    "laravel": string[];
    "krita": string[];
    "lastDotFm": string[];
    "laravelhorizon": string[];
    "lastfm": string[];
    "laravelnova": string[];
    "leetcode": string[];
    "latex": string[];
    "leanpub": string[];
    "launchpad": string[];
    "lenovo": string[];
    "less": string[];
    "letsencrypt": string[];
    "letterboxd": string[];
    "librarything": string[];
    "lgtm": string[];
    "liberapay": string[];
    "libreoffice": string[];
    "line": string[];
    "linkedin": string[];
    "linode": string[];
    "linewebtoon": string[];
    "livejournal": string[];
    "linuxfoundation": string[];
    "linux": string[];
    "livestream": string[];
    "lumen": string[];
    "lua": string[];
    "lyft": string[];
    "linuxmint": string[];
    "macys": string[];
    "magento": string[];
    "magisk": string[];
    "mailDotRu": string[];
    "logstash": string[];
    "mailchimp": string[];
    "makerbot": string[];
    "markdown": string[];
    "mandalorian": string[];
    "marketo": string[];
    "manjaro": string[];
    "mastercard": string[];
    "mastodon": string[];
    "materialdesign": string[];
    "mathworks": string[];
    "mattermost": string[];
    "matrix": string[];
    "maxcdn": string[];
    "medapps": string[];
    "matternet": string[];
    "mcafee": string[];
    "mediafire": string[];
    "meetup": string[];
    "mediatemple": string[];
    "medium": string[];
    "mega": string[];
    "medrt": string[];
    "mendeley": string[];
    "microgenetics": string[];
    "megaport": string[];
    "messenger": string[];
    "microDotBlog": string[];
    "meteor": string[];
    "minetest": string[];
    "microsoft": string[];
    "microsoftEdge": string[];
    "minutemailer": string[];
    "mixcloud": string[];
    "mixer": string[];
    "mix": string[];
    "modx": string[];
    "mizuni": string[];
    "mojang": string[];
    "monero": string[];
    "monogram": string[];
    "mongodb": string[];
    "monkeytie": string[];
    "mozilla": string[];
    "monzo": string[];
    "moo": string[];
    "mxlinux": string[];
    "mozillaFirefox": string[];
    "musescore": string[];
    "myspace": string[];
    "nativescript": string[];
    "mysql": string[];
    "napster": string[];
    "neo4j": string[];
    "netflix": string[];
    "neos": string[];
    "nec": string[];
    "netlify": string[];
    "nextJs": string[];
    "nginx": string[];
    "nextcloud": string[];
    "nim": string[];
    "nintendo3ds": string[];
    "nimblr": string[];
    "nextdoor": string[];
    "nodeJs": string[];
    "nintendoSwitch": string[];
    "nintendoGamecube": string[];
    "nintendo": string[];
    "nodeRed": string[];
    "node": string[];
    "nodemon": string[];
    "npm": string[];
    "nokia": string[];
    "notion": string[];
    "ns8": string[];
    "nucleo": string[];
    "nuget": string[];
    "nuxtDotJs": string[];
    "nutritionix": string[];
    "ocaml": string[];
    "nvidia": string[];
    "octave": string[];
    "octopusdeploy": string[];
    "odnoklassniki": string[];
    "oculus": string[];
    "opencart": string[];
    "openaccess": string[];
    "openid": string[];
    "openstreetmap": string[];
    "opencollective": string[];
    "openvpn": string[];
    "opensourceinitiative": string[];
    "opensuse": string[];
    "opera": string[];
    "optinMonster": string[];
    "opsgenie": string[];
    "orcid": string[];
    "oracle": string[];
    "osi": string[];
    "osmc": string[];
    "overcast": string[];
    "origin": string[];
    "overleaf": string[];
    "ovh": string[];
    "pagelines": string[];
    "page4": string[];
    "palantir": string[];
    "pagekit": string[];
    "pandora": string[];
    "paloaltosoftware": string[];
    "palfed": string[];
    "pantheon": string[];
    "pennyArcade": string[];
    "patreon": string[];
    "periscope": string[];
    "paypal": string[];
    "phoenixFramework": string[];
    "phabricator": string[];
    "php": string[];
    "phoenixSquadron": string[];
    "piedPiperAlt": string[];
    "picartoDotTv": string[];
    "piedPiperHat": string[];
    "piedPiperPp": string[];
    "pingdom": string[];
    "piedPiper": string[];
    "pinterest": string[];
    "pinboard": string[];
    "pinterestP": string[];
    "pingup": string[];
    "playerDotMe": string[];
    "pivotaltracker": string[];
    "playstation3": string[];
    "plangrid": string[];
    "playerfm": string[];
    "plex": string[];
    "playstation": string[];
    "plurk": string[];
    "playstation4": string[];
    "plesk": string[];
    "pluralsight": string[];
    "pocket": string[];
    "postman": string[];
    "postgresql": string[];
    "powershell": string[];
    "probot": string[];
    "prettier": string[];
    "producthunt": string[];
    "processwire": string[];
    "protonmail": string[];
    "prismic": string[];
    "protoDotIo": string[];
    "python": string[];
    "postwoman": string[];
    "pushed": string[];
    "proxmox": string[];
    "pypi": string[];
    "qgis": string[];
    "qiita": string[];
    "qq": string[];
    "pytorch": string[];
    "qualcomm": string[];
    "quantcast": string[];
    "quantopian": string[];
    "quarkus": string[];
    "quinscape": string[];
    "qwiklabs": string[];
    "quora": string[];
    "qzone": string[];
    "rProject": string[];
    "r": string[];
    "rails": string[];
    "radiopublic": string[];
    "raspberrypi": string[];
    "ravelry": string[];
    "react": string[];
    "readme": string[];
    "readthedocs": string[];
    "reacteurope": string[];
    "reason": string[];
    "realm": string[];
    "redRiver": string[];
    "rebel": string[];
    "redbubble": string[];
    "redditAlien": string[];
    "reddit": string[];
    "redhat": string[];
    "redis": string[];
    "renren": string[];
    "redux": string[];
    "researchgate": string[];
    "replyd": string[];
    "resolving": string[];
    "reverbnation": string[];
    "rev": string[];
    "riot": string[];
    "riseup": string[];
    "rockrms": string[];
    "ripple": string[];
    "rollupJs": string[];
    "roundcube": string[];
    "roots": string[];
    "rocketchat": string[];
    "rss": string[];
    "rstudio": string[];
    "ruby": string[];
    "rubygems": string[];
    "runkeeper": string[];
    "rust": string[];
    "safari": string[];
    "sahibinden": string[];
    "saltstack": string[];
    "salesforce": string[];
    "samsung": string[];
    "samsungPay": string[];
    "sap": string[];
    "sass": string[];
    "scala": string[];
    "saucelabs": string[];
    "schlix": string[];
    "scaleway": string[];
    "scrutinizerci": string[];
    "scribd": string[];
    "searchengin": string[];
    "seagate": string[];
    "sellfy": string[];
    "sega": string[];
    "sellsy": string[];
    "sellcast": string[];
    "semaphoreci": string[];
    "sensu": string[];
    "sentry": string[];
    "serverfault": string[];
    "shopify": string[];
    "servicestack": string[];
    "shazam": string[];
    "shopware": string[];
    "shell": string[];
    "shirtsinbulk": string[];
    "showpad": string[];
    "siemens": string[];
    "simpleicons": string[];
    "signal": string[];
    "simplybuilt": string[];
    "sistrix": string[];
    "sketch": string[];
    "sitepoint": string[];
    "sith": string[];
    "sinaweibo": string[];
    "skillshare": string[];
    "skyliner": string[];
    "skyatlas": string[];
    "skype": string[];
    "slashdot": string[];
    "slack": string[];
    "slackHash": string[];
    "smashingmagazine": string[];
    "slickpic": string[];
    "slides": string[];
    "slideshare": string[];
    "snapchatGhost": string[];
    "snapcraft": string[];
    "snapchat": string[];
    "socketDotIo": string[];
    "snyk": string[];
    "sogou": string[];
    "songkick": string[];
    "society6": string[];
    "sonos": string[];
    "solus": string[];
    "sourcegraph": string[];
    "spacex": string[];
    "spacemacs": string[];
    "soundcloud": string[];
    "sparkfun": string[];
    "sourceforge": string[];
    "sparkpost": string[];
    "speakerDeck": string[];
    "speakap": string[];
    "sourcetree": string[];
    "spdx": string[];
    "spectrum": string[];
    "speakerdeck": string[];
    "spring": string[];
    "spotify": string[];
    "spreaker": string[];
    "spotlight": string[];
    "sprint": string[];
    "squarespace": string[];
    "stackbit": string[];
    "stackOverflow": string[];
    "stackexchange": string[];
    "stackExchange": string[];
    "stackoverflow": string[];
    "stackpath": string[];
    "stackshare": string[];
    "statamic": string[];
    "staticman": string[];
    "stadia": string[];
    "steamSymbol": string[];
    "statuspage": string[];
    "steem": string[];
    "staylinked": string[];
    "steam": string[];
    "stickerMule": string[];
    "stitcher": string[];
    "steemit": string[];
    "storify": string[];
    "storybook": string[];
    "strava": string[];
    "strapi": string[];
    "stubhub": string[];
    "studiovinari": string[];
    "stripe": string[];
    "stumbleuponCircle": string[];
    "stumbleupon": string[];
    "styleshare": string[];
    "sublimetext": string[];
    "stylus": string[];
    "subversion": string[];
    "superpowers": string[];
    "superuser": string[];
    "supple": string[];
    "suse": string[];
    "svg": string[];
    "swagger": string[];
    "svelte": string[];
    "swarm": string[];
    "swift": string[];
    "symfony": string[];
    "symantec": string[];
    "synology": string[];
    "tMobile": string[];
    "tails": string[];
    "tapas": string[];
    "teamviewer": string[];
    "tableau": string[];
    "teamspeak": string[];
    "teespring": string[];
    "tencentWeibo": string[];
    "telegram": string[];
    "tencentweibo": string[];
    "ted": string[];
    "tencentqq": string[];
    "tesla": string[];
    "terraform": string[];
    "tensorflow": string[];
    "theRedYeti": string[];
    "themeco": string[];
    "tidal": string[];
    "themeisle": string[];
    "themighty": string[];
    "thinkPeaks": string[];
    "tiktok": string[];
    "themoviedatabase": string[];
    "todoist": string[];
    "tinder": string[];
    "toptal": string[];
    "toggl": string[];
    "toshiba": string[];
    "topcoder": string[];
    "trakt": string[];
    "tor": string[];
    "tradeFederation": string[];
    "trainerroad": string[];
    "travisci": string[];
    "treehouse": string[];
    "trulia": string[];
    "tripadvisor": string[];
    "trello": string[];
    "tumblr": string[];
    "twilio": string[];
    "turkishairlines": string[];
    "twitch": string[];
    "twoo": string[];
    "typescript": string[];
    "twitter": string[];
    "typo3": string[];
    "uber": string[];
    "ubisoft": string[];
    "ubuntu": string[];
    "ublockorigin": string[];
    "udacity": string[];
    "uikit": string[];
    "umbraco": string[];
    "unity": string[];
    "unrealengine": string[];
    "udemy": string[];
    "ups": string[];
    "uniregistry": string[];
    "unsplash": string[];
    "upwork": string[];
    "usps": string[];
    "ussunnah": string[];
    "untappd": string[];
    "usb": string[];
    "verizon": string[];
    "venmo": string[];
    "vagrant": string[];
    "viacoin": string[];
    "vaadin": string[];
    "viadeo": string[];
    "viber": string[];
    "v8": string[];
    "vim": string[];
    "vimeo": string[];
    "vine": string[];
    "visa": string[];
    "virb": string[];
    "visualstudiocode": string[];
    "visualstudio": string[];
    "vlc": string[];
    "vk": string[];
    "vsco": string[];
    "vnv": string[];
    "vueJs": string[];
    "vuejs": string[];
    "wattpad": string[];
    "waze": string[];
    "weasyl": string[];
    "webcomponentsDotOrg": string[];
    "webstorm": string[];
    "webpack": string[];
    "weixin": string[];
    "weebly": string[];
    "weibo": string[];
    "wechat": string[];
    "whatsapp": string[];
    "wheniwork": string[];
    "whmcs": string[];
    "wii": string[];
    "wiiu": string[];
    "wikipedia": string[];
    "wire": string[];
    "windows": string[];
    "wix": string[];
    "wireguard": string[];
    "wolfPackBattalion": string[];
    "wizardsOfTheCoast": string[];
    "wolframLanguage": string[];
    "wolframMathematica": string[];
    "wordpress": string[];
    "wolfram": string[];
    "wpengine": string[];
    "wpbeginner": string[];
    "wpforms": string[];
    "wpexplorer": string[];
    "xbox": string[];
    "wpressr": string[];
    "xPack": string[];
    "xero": string[];
    "xcode": string[];
    "xing": string[];
    "xiaomi": string[];
    "xrp": string[];
    "xsplit": string[];
    "yamahaCorporation": string[];
    "yahoo": string[];
    "yamahaMotorCorporation": string[];
    "yandex": string[];
    "yammer": string[];
    "yandexInternational": string[];
    "yarn": string[];
    "ycombinator": string[];
    "yelp": string[];
    "zalando": string[];
    "yoast": string[];
    "zeit": string[];
    "zapier": string[];
    "youtube": string[];
    "zendesk": string[];
    "zerply": string[];
    "zillow": string[];
    "zhihu": string[];
    "zingat": string[];
    "zoom": string[];
    "zorin": string[];
    "zulip": string[];
    "apacheFlink": string[];
    "codewars": string[];
    "epicgames": string[];
    "flask": string[];
    "gerrit": string[];
    "gnu": string[];
    "greensock": string[];
    "oldRepublic": string[];
    "babel": string[];
    "composer": string[];
    "elsevier": string[];
};
export declare const brave: string[];
export declare const btc: string[];
export declare const buddy: string[];
export declare const buffer: string[];
export declare const buromobelexperte: string[];
export declare const buymeacoffee: string[];
export declare const buysellads: string[];
export declare const buzzfeed: string[];
export declare const c: string[];
export declare const cakephp: string[];
export declare const campaignMonitor: string[];
export declare const canadianMapleLeaf: string[];
export declare const canva: string[];
export declare const cashapp: string[];
export declare const cassandra: string[];
export declare const castorama: string[];
export declare const castro: string[];
export declare const ccAmazonPay: string[];
export declare const ccAmex: string[];
export declare const ccApplePay: string[];
export declare const ccDinersClub: string[];
export declare const ccDiscover: string[];
export declare const ccJcb: string[];
export declare const ccMastercard: string[];
export declare const ccPaypal: string[];
export declare const ccStripe: string[];
export declare const ccVisa: string[];
export declare const centercode: string[];
export declare const centos: string[];
export declare const cevo: string[];
export declare const chase: string[];
export declare const chef: string[];
export declare const chrome: string[];
export declare const chromecast: string[];
export declare const circleCi: string[];
export declare const circle: string[];
export declare const cirrusci: string[];
export declare const cisco: string[];
export declare const civicrm: string[];
export declare const clockify: string[];
export declare const clojure: string[];
export declare const cloudbees: string[];
export declare const cloudflare: string[];
export declare const cloudscale: string[];
export declare const cloudsmith: string[];
export declare const cloudversify: string[];
export declare const cmake: string[];
export declare const coOp: string[];
export declare const codacy: string[];
export declare const codecademy: string[];
export declare const codeclimate: string[];
export declare const codecov: string[];
export declare const codefactor: string[];
export declare const codeforces: string[];
export declare const codeigniter: string[];
export declare const codepen: string[];
export declare const coderwall: string[];
export declare const codesandbox: string[];
export declare const codeship: string[];
export declare const codewars: string[];
export declare const codiepie: string[];
export declare const codio: string[];
export declare const coffeescript: string[];
export declare const commonworkflowlanguage: string[];
export declare const composer: string[];
export declare const compropago: string[];
export declare const condaForge: string[];
export declare const conekta: string[];
export declare const confluence: string[];
export declare const connectdevelop: string[];
export declare const contao: string[];
export declare const coursera: string[];
export declare const coveralls: string[];
export declare const cpanel: string[];
export declare const cplusplus: string[];
export declare const creativeCommonsBy: string[];
export declare const creativeCommonsNcEu: string[];
export declare const creativeCommonsNcJp: string[];
export declare const creativeCommonsNc: string[];
export declare const creativeCommonsNd: string[];
export declare const creativeCommonsPdAlt: string[];
export declare const creativeCommonsPd: string[];
export declare const creativeCommonsRemix: string[];
export declare const creativeCommonsSa: string[];
export declare const creativeCommonsSamplingPlus: string[];
export declare const creativeCommonsSampling: string[];
export declare const creativeCommonsShare: string[];
export declare const creativeCommonsZero: string[];
export declare const creativeCommons: string[];
export declare const criticalRole: string[];
export declare const crunchbase: string[];
export declare const crunchyroll: string[];
export declare const css3Alt: string[];
export declare const css3: string[];
export declare const csswizardry: string[];
export declare const cuttlefish: string[];
export declare const dAndDBeyond: string[];
export declare const dAndD: string[];
export declare const d3DotJs: string[];
export declare const dailymotion: string[];
export declare const dashcube: string[];
export declare const dashlane: string[];
export declare const dassaultsystemes: string[];
export declare const dazn: string[];
export declare const dblp: string[];
export declare const debian: string[];
export declare const deepin: string[];
export declare const deezer: string[];
export declare const delicious: string[];
export declare const dell: string[];
export declare const deno: string[];
export declare const dependabot: string[];
export declare const deploydog: string[];
export declare const designernews: string[];
export declare const deskpro: string[];
export declare const devTo: string[];
export declare const deviantart: string[];
export declare const devrant: string[];
export declare const dhl: string[];
export declare const diaspora: string[];
export declare const digg: string[];
export declare const digitalOcean: string[];
export declare const digitalocean: string[];
export declare const discord: string[];
export declare const discourse: string[];
export declare const discover: string[];
export declare const disqus: string[];
export declare const disroot: string[];
export declare const django: string[];
export declare const dochub: string[];
export declare const docker: string[];
export declare const docusign: string[];
export declare const dotNet: string[];
export declare const draft2digital: string[];
export declare const draugiemDotLv: string[];
export declare const dribbble: string[];
export declare const drone: string[];
export declare const dropbox: string[];
export declare const drupal: string[];
export declare const dtube: string[];
export declare const duckduckgo: string[];
export declare const dyalog: string[];
export declare const dynatrace: string[];
export declare const earlybirds: string[];
export declare const ebay: string[];
export declare const eclipseide: string[];
export declare const edge: string[];
export declare const elastic: string[];
export declare const elasticcloud: string[];
export declare const elasticsearch: string[];
export declare const elasticstack: string[];
export declare const electron: string[];
export declare const elementary: string[];
export declare const elementor: string[];
export declare const eleventy: string[];
export declare const ello: string[];
export declare const elsevier: string[];
export declare const ember: string[];
export declare const emlakjet: string[];
export declare const empire: string[];
export declare const empirekred: string[];
export declare const envato: string[];
export declare const envira: string[];
export declare const epicgames: string[];
export declare const epson: string[];
export declare const erlang: string[];
export declare const esea: string[];
export declare const eslint: string[];
export declare const ethereum: string[];
export declare const etsy: string[];
export declare const eventbrite: string[];
export declare const eventstore: string[];
export declare const evernote: string[];
export declare const everplaces: string[];
export declare const evry: string[];
export declare const exercism: string[];
export declare const expeditedssl: string[];
export declare const expertsexchange: string[];
export declare const expo: string[];
export declare const eyeem: string[];
export declare const fSecure: string[];
export declare const facebookF: string[];
export declare const facebookMessenger: string[];
export declare const facebook: string[];
export declare const faceit: string[];
export declare const fandango: string[];
export declare const fantasyFlightGames: string[];
export declare const favro: string[];
export declare const feathub: string[];
export declare const fedex: string[];
export declare const fedora: string[];
export declare const feedly: string[];
export declare const fidoalliance: string[];
export declare const figma: string[];
export declare const filezilla: string[];
export declare const firebase: string[];
export declare const firefox: string[];
export declare const firstOrderAlt: string[];
export declare const firstOrder: string[];
export declare const firstdraft: string[];
export declare const fitbit: string[];
export declare const flask: string[];
export declare const flattr: string[];
export declare const flickr: string[];
export declare const flipboard: string[];
export declare const flutter: string[];
export declare const fly: string[];
export declare const fnac: string[];
export declare const fontAwesomeAlt: string[];
export declare const forumbee: string[];
export declare const framer: string[];
export declare const freeCodeCamp: string[];
export declare const freebsd: string[];
export declare const freecodecamp: string[];
export declare const fulcrum: string[];
export declare const furaffinity: string[];
export declare const furrynetwork: string[];
export declare const galacticRepublic: string[];
export declare const galacticSenate: string[];
export declare const garmin: string[];
export declare const gatsby: string[];
export declare const gauges: string[];
export declare const genius: string[];
export declare const gentoo: string[];
export declare const geocaching: string[];
export declare const gerrit: string[];
export declare const getPocket: string[];
export declare const ggCircle: string[];
export declare const gg: string[];
export declare const ghost: string[];
export declare const gimp: string[];
export declare const git: string[];
export declare const gitea: string[];
export declare const githubAlt: string[];
export declare const github: string[];
export declare const gitkraken: string[];
export declare const gitlab: string[];
export declare const gitpod: string[];
export declare const gitter: string[];
export declare const glassdoor: string[];
export declare const glideG: string[];
export declare const glide: string[];
export declare const glitch: string[];
export declare const gmail: string[];
export declare const gnu: string[];
export declare const gnuprivacyguard: string[];
export declare const gnusocial: string[];
export declare const go: string[];
export declare const godotengine: string[];
export declare const gofore: string[];
export declare const gogCom: string[];
export declare const goldenline: string[];
export declare const goodreadsG: string[];
export declare const goodreads: string[];
export declare const googleAds: string[];
export declare const googleAllo: string[];
export declare const googleAnalytics: string[];
export declare const googleCloud: string[];
export declare const googleDrive: string[];
export declare const googleHangouts: string[];
export declare const googleHangoutschat: string[];
export declare const googleKeep: string[];
export declare const googlePay: string[];
export declare const googlePlay: string[];
export declare const googlePodcasts: string[];
export declare const googleScholar: string[];
export declare const googleWallet: string[];
export declare const google: string[];
export declare const govUk: string[];
export declare const gradle: string[];
export declare const grafana: string[];
export declare const graphcool: string[];
export declare const graphql: string[];
export declare const gratipay: string[];
export declare const grav: string[];
export declare const gravatar: string[];
export declare const greenkeeper: string[];
export declare const greensock: string[];
export declare const gripfire: string[];
export declare const groovy: string[];
export declare const groupon: string[];
export declare const grunt: string[];
export declare const gulp: string[];
export declare const gumroad: string[];
export declare const gumtree: string[];
export declare const habr: string[];
export declare const hackaday: string[];
export declare const hackerNews: string[];
export declare const hackerearth: string[];
export declare const hackerone: string[];
export declare const hackerrank: string[];
export declare const hackhands: string[];
export declare const hackster: string[];
export declare const happycow: string[];
export declare const hashnode: string[];
export declare const haskell: string[];
export declare const hatenabookmark: string[];
export declare const haxe: string[];
export declare const helm: string[];
export declare const here: string[];
export declare const heroku: string[];
export declare const hexo: string[];
export declare const highly: string[];
export declare const hipchat: string[];
export declare const hips: string[];
export declare const hireAHelper: string[];
export declare const hitachi: string[];
export declare const hockeyapp: string[];
export declare const homify: string[];
export declare const hooli: string[];
export declare const hootsuite: string[];
export declare const hornbill: string[];
export declare const hotjar: string[];
export declare const houzz: string[];
export declare const hp: string[];
export declare const html5: string[];
export declare const htmlacademy: string[];
export declare const huawei: string[];
export declare const hubspot: string[];
export declare const hulu: string[];
export declare const humblebundle: string[];
export declare const hurriyetemlak: string[];
export declare const iata: string[];
export declare const ibm: string[];
export declare const icloud: string[];
export declare const iconSet: {
    "500px": string[];
    "aboutMe": string[];
    "acm": string[];
    "adn": string[];
    "abstract": string[];
    "accusoft": string[];
    "adguard": string[];
    "acquisitionsIncorporated": string[];
    "addthis": string[];
    "adobeCreativeCloud": string[];
    "adobeAfterEffects": string[];
    "adobeAcrobatReader": string[];
    "adobeDreamweaver": string[];
    "adobeAudition": string[];
    "adobeIllustrator": string[];
    "adobeLightroomcc": string[];
    "adobeLightroomclassic": string[];
    "adobePremiere": string[];
    "adobePhotoshop": string[];
    "adobeIndesign": string[];
    "adobeXd": string[];
    "adversal": string[];
    "adobeTypekit": string[];
    "adobe": string[];
    "affiliatetheme": string[];
    "airbnb": string[];
    "alipay": string[];
    "algolia": string[];
    "allocine": string[];
    "amazonAws": string[];
    "amazonPay": string[];
    "amd": string[];
    "americanExpress": string[];
    "amilia": string[];
    "amazon": string[];
    "anaconda": string[];
    "androidAlt": string[];
    "analogue": string[];
    "angularUniversal": string[];
    "android": string[];
    "angrycreative": string[];
    "angellist": string[];
    "angular": string[];
    "ansible": string[];
    "apacheAirflow": string[];
    "apacheSpark": string[];
    "appStore": string[];
    "apache": string[];
    "apple": string[];
    "apper": string[];
    "applePay": string[];
    "archLinux": string[];
    "appveyor": string[];
    "arduino": string[];
    "aral": string[];
    "archiveOfOurOwn": string[];
    "arxiv": string[];
    "artstation": string[];
    "asymmetrik": string[];
    "asana": string[];
    "atAndT": string[];
    "audible": string[];
    "atlassian": string[];
    "atom": string[];
    "auth0": string[];
    "aurelia": string[];
    "autotask": string[];
    "automatic": string[];
    "autoprefixer": string[];
    "avianex": string[];
    "aventrix": string[];
    "aviato": string[];
    "aws": string[];
    "azureArtifacts": string[];
    "azureDevops": string[];
    "bamboo": string[];
    "azurePipelines": string[];
    "bancontact": string[];
    "beats": string[];
    "battleNet": string[];
    "baidu": string[];
    "basecamp": string[];
    "behance": string[];
    "bit": string[];
    "bandcamp": string[];
    "bathasu": string[];
    "bigCartel": string[];
    "bing": string[];
    "bimobject": string[];
    "bitcoin": string[];
    "bitbucket": string[];
    "bitly": string[];
    "bitdefender": string[];
    "blackTie": string[];
    "blackberry": string[];
    "bity": string[];
    "blogger": string[];
    "bluetoothB": string[];
    "blender": string[];
    "boeing": string[];
    "bluetooth": string[];
    "boost": string[];
    "bootstrap": string[];
    "bower": string[];
    "brandAi": string[];
    "btc": string[];
    "buddy": string[];
    "buffer": string[];
    "brave": string[];
    "buymeacoffee": string[];
    "buysellads": string[];
    "c": string[];
    "buromobelexperte": string[];
    "buzzfeed": string[];
    "campaignMonitor": string[];
    "cakephp": string[];
    "canadianMapleLeaf": string[];
    "cashapp": string[];
    "canva": string[];
    "castro": string[];
    "ccAmazonPay": string[];
    "castorama": string[];
    "cassandra": string[];
    "ccAmex": string[];
    "ccApplePay": string[];
    "ccDiscover": string[];
    "ccDinersClub": string[];
    "ccJcb": string[];
    "ccPaypal": string[];
    "ccStripe": string[];
    "centercode": string[];
    "ccMastercard": string[];
    "ccVisa": string[];
    "cevo": string[];
    "chrome": string[];
    "centos": string[];
    "chef": string[];
    "chromecast": string[];
    "circleCi": string[];
    "cirrusci": string[];
    "chase": string[];
    "circle": string[];
    "civicrm": string[];
    "cisco": string[];
    "clockify": string[];
    "clojure": string[];
    "cloudbees": string[];
    "cloudscale": string[];
    "cloudversify": string[];
    "cloudsmith": string[];
    "cmake": string[];
    "cloudflare": string[];
    "coOp": string[];
    "codecademy": string[];
    "codeclimate": string[];
    "codacy": string[];
    "codecov": string[];
    "codefactor": string[];
    "codeforces": string[];
    "coderwall": string[];
    "codeigniter": string[];
    "codepen": string[];
    "codesandbox": string[];
    "codio": string[];
    "codeship": string[];
    "codiepie": string[];
    "coffeescript": string[];
    "commonworkflowlanguage": string[];
    "compropago": string[];
    "condaForge": string[];
    "confluence": string[];
    "coursera": string[];
    "conekta": string[];
    "coveralls": string[];
    "contao": string[];
    "connectdevelop": string[];
    "cpanel": string[];
    "cplusplus": string[];
    "creativeCommonsBy": string[];
    "creativeCommonsNcEu": string[];
    "creativeCommonsNcJp": string[];
    "creativeCommonsNc": string[];
    "creativeCommonsPdAlt": string[];
    "creativeCommonsNd": string[];
    "creativeCommonsSamplingPlus": string[];
    "creativeCommonsSa": string[];
    "creativeCommonsRemix": string[];
    "creativeCommonsPd": string[];
    "creativeCommonsShare": string[];
    "creativeCommonsSampling": string[];
    "creativeCommonsZero": string[];
    "crunchbase": string[];
    "criticalRole": string[];
    "creativeCommons": string[];
    "crunchyroll": string[];
    "css3Alt": string[];
    "css3": string[];
    "csswizardry": string[];
    "d3DotJs": string[];
    "dAndD": string[];
    "cuttlefish": string[];
    "dAndDBeyond": string[];
    "dailymotion": string[];
    "dashcube": string[];
    "dazn": string[];
    "dashlane": string[];
    "dassaultsystemes": string[];
    "debian": string[];
    "deezer": string[];
    "dblp": string[];
    "deepin": string[];
    "delicious": string[];
    "dell": string[];
    "deploydog": string[];
    "dependabot": string[];
    "deno": string[];
    "deskpro": string[];
    "designernews": string[];
    "deviantart": string[];
    "devrant": string[];
    "devTo": string[];
    "dhl": string[];
    "digg": string[];
    "digitalocean": string[];
    "diaspora": string[];
    "digitalOcean": string[];
    "discord": string[];
    "discourse": string[];
    "discover": string[];
    "disqus": string[];
    "django": string[];
    "disroot": string[];
    "docusign": string[];
    "dochub": string[];
    "docker": string[];
    "dotNet": string[];
    "draugiemDotLv": string[];
    "draft2digital": string[];
    "drone": string[];
    "dribbble": string[];
    "dropbox": string[];
    "drupal": string[];
    "dyalog": string[];
    "dynatrace": string[];
    "duckduckgo": string[];
    "earlybirds": string[];
    "dtube": string[];
    "ebay": string[];
    "elastic": string[];
    "eclipseide": string[];
    "edge": string[];
    "electron": string[];
    "elasticsearch": string[];
    "elementary": string[];
    "elasticstack": string[];
    "elasticcloud": string[];
    "elementor": string[];
    "eleventy": string[];
    "ello": string[];
    "ember": string[];
    "empirekred": string[];
    "emlakjet": string[];
    "empire": string[];
    "envato": string[];
    "epson": string[];
    "envira": string[];
    "erlang": string[];
    "esea": string[];
    "eslint": string[];
    "eventstore": string[];
    "ethereum": string[];
    "evernote": string[];
    "evry": string[];
    "etsy": string[];
    "everplaces": string[];
    "eventbrite": string[];
    "exercism": string[];
    "expeditedssl": string[];
    "eyeem": string[];
    "expertsexchange": string[];
    "fSecure": string[];
    "expo": string[];
    "facebookF": string[];
    "facebook": string[];
    "facebookMessenger": string[];
    "faceit": string[];
    "fandango": string[];
    "fedex": string[];
    "favro": string[];
    "fantasyFlightGames": string[];
    "fedora": string[];
    "fidoalliance": string[];
    "feathub": string[];
    "feedly": string[];
    "figma": string[];
    "firebase": string[];
    "filezilla": string[];
    "firefox": string[];
    "firstOrderAlt": string[];
    "firstOrder": string[];
    "fitbit": string[];
    "flattr": string[];
    "firstdraft": string[];
    "flipboard": string[];
    "flutter": string[];
    "flickr": string[];
    "fly": string[];
    "fnac": string[];
    "forumbee": string[];
    "framer": string[];
    "fontAwesomeAlt": string[];
    "freeCodeCamp": string[];
    "freebsd": string[];
    "fulcrum": string[];
    "furaffinity": string[];
    "freecodecamp": string[];
    "furrynetwork": string[];
    "galacticRepublic": string[];
    "garmin": string[];
    "gatsby": string[];
    "galacticSenate": string[];
    "gauges": string[];
    "gentoo": string[];
    "genius": string[];
    "geocaching": string[];
    "getPocket": string[];
    "ggCircle": string[];
    "git": string[];
    "ghost": string[];
    "gg": string[];
    "gimp": string[];
    "gitea": string[];
    "github": string[];
    "githubAlt": string[];
    "gitkraken": string[];
    "gitpod": string[];
    "gitter": string[];
    "gitlab": string[];
    "glassdoor": string[];
    "glideG": string[];
    "glide": string[];
    "gmail": string[];
    "glitch": string[];
    "gnuprivacyguard": string[];
    "gnusocial": string[];
    "go": string[];
    "gofore": string[];
    "godotengine": string[];
    "goldenline": string[];
    "goodreads": string[];
    "goodreadsG": string[];
    "gogCom": string[];
    "googleAllo": string[];
    "googleCloud": string[];
    "googleAnalytics": string[];
    "googleDrive": string[];
    "googleAds": string[];
    "googleHangouts": string[];
    "googleKeep": string[];
    "googlePlay": string[];
    "googlePodcasts": string[];
    "googleHangoutschat": string[];
    "googlePay": string[];
    "google": string[];
    "googleScholar": string[];
    "googleWallet": string[];
    "gradle": string[];
    "govUk": string[];
    "gratipay": string[];
    "grafana": string[];
    "graphql": string[];
    "graphcool": string[];
    "grav": string[];
    "gravatar": string[];
    "greenkeeper": string[];
    "gripfire": string[];
    "groovy": string[];
    "gulp": string[];
    "gumroad": string[];
    "grunt": string[];
    "groupon": string[];
    "habr": string[];
    "gumtree": string[];
    "hackaday": string[];
    "hackerNews": string[];
    "hackerearth": string[];
    "hackster": string[];
    "hackerone": string[];
    "hackerrank": string[];
    "happycow": string[];
    "hashnode": string[];
    "hatenabookmark": string[];
    "hackhands": string[];
    "haskell": string[];
    "haxe": string[];
    "heroku": string[];
    "hexo": string[];
    "here": string[];
    "helm": string[];
    "highly": string[];
    "hitachi": string[];
    "hipchat": string[];
    "hockeyapp": string[];
    "hips": string[];
    "hireAHelper": string[];
    "hooli": string[];
    "homify": string[];
    "hornbill": string[];
    "hootsuite": string[];
    "hotjar": string[];
    "houzz": string[];
    "hp": string[];
    "html5": string[];
    "htmlacademy": string[];
    "huawei": string[];
    "ibm": string[];
    "hulu": string[];
    "hubspot": string[];
    "iata": string[];
    "humblebundle": string[];
    "hurriyetemlak": string[];
    "icloud": string[];
    "iconjar": string[];
    "ifixit": string[];
    "ideal": string[];
    "imdb": string[];
    "icq": string[];
    "inkscape": string[];
    "indeed": string[];
    "intel": string[];
    "instacart": string[];
    "instagram": string[];
    "instapaper": string[];
    "intercom": string[];
    "intellijidea": string[];
    "internetExplorer": string[];
    "internetexplorer": string[];
    "ionic": string[];
    "issuu": string[];
    "invision": string[];
    "itchDotIo": string[];
    "ioxhost": string[];
    "itchIo": string[];
    "java": string[];
    "itunes": string[];
    "itunesNote": string[];
    "jabber": string[];
    "jediOrder": string[];
    "javascript": string[];
    "jekyll": string[];
    "jenkins": string[];
    "jest": string[];
    "jetbrains": string[];
    "joget": string[];
    "jira": string[];
    "jet": string[];
    "joomla": string[];
    "jquery": string[];
    "jsdelivr": string[];
    "jsfiddle": string[];
    "justgiving": string[];
    "jupyter": string[];
    "json": string[];
    "kaggle": string[];
    "kaspersky": string[];
    "kaios": string[];
    "kentico": string[];
    "keybase": string[];
    "keras": string[];
    "keycdn": string[];
    "kibana": string[];
    "khanacademy": string[];
    "kickstarter": string[];
    "kik": string[];
    "kirby": string[];
    "klout": string[];
    "known": string[];
    "korvue": string[];
    "kodi": string[];
    "koFi": string[];
    "koding": string[];
    "kotlin": string[];
    "lanyrd": string[];
    "krita": string[];
    "kubernetes": string[];
    "laravel": string[];
    "laravelhorizon": string[];
    "laravelnova": string[];
    "lastfm": string[];
    "latex": string[];
    "lastDotFm": string[];
    "leanpub": string[];
    "launchpad": string[];
    "leetcode": string[];
    "less": string[];
    "lgtm": string[];
    "letsencrypt": string[];
    "letterboxd": string[];
    "lenovo": string[];
    "liberapay": string[];
    "line": string[];
    "libreoffice": string[];
    "linkedin": string[];
    "linux": string[];
    "librarything": string[];
    "linewebtoon": string[];
    "linode": string[];
    "linuxfoundation": string[];
    "linuxmint": string[];
    "livejournal": string[];
    "livestream": string[];
    "lua": string[];
    "lumen": string[];
    "logstash": string[];
    "lyft": string[];
    "macys": string[];
    "magento": string[];
    "mailDotRu": string[];
    "mailchimp": string[];
    "magisk": string[];
    "makerbot": string[];
    "mandalorian": string[];
    "mastercard": string[];
    "markdown": string[];
    "manjaro": string[];
    "marketo": string[];
    "mastodon": string[];
    "materialdesign": string[];
    "mathworks": string[];
    "matternet": string[];
    "maxcdn": string[];
    "medapps": string[];
    "matrix": string[];
    "mattermost": string[];
    "mediafire": string[];
    "mcafee": string[];
    "mediatemple": string[];
    "meetup": string[];
    "medrt": string[];
    "medium": string[];
    "megaport": string[];
    "messenger": string[];
    "mega": string[];
    "mendeley": string[];
    "meteor": string[];
    "microDotBlog": string[];
    "microgenetics": string[];
    "microsoftEdge": string[];
    "microsoft": string[];
    "minetest": string[];
    "mixer": string[];
    "mix": string[];
    "mixcloud": string[];
    "minutemailer": string[];
    "modx": string[];
    "mizuni": string[];
    "mojang": string[];
    "monero": string[];
    "mongodb": string[];
    "monkeytie": string[];
    "moo": string[];
    "monzo": string[];
    "monogram": string[];
    "mozillaFirefox": string[];
    "mozilla": string[];
    "myspace": string[];
    "musescore": string[];
    "mxlinux": string[];
    "mysql": string[];
    "nativescript": string[];
    "nec": string[];
    "napster": string[];
    "neo4j": string[];
    "neos": string[];
    "netflix": string[];
    "nextJs": string[];
    "netlify": string[];
    "nextcloud": string[];
    "nextdoor": string[];
    "nim": string[];
    "nimblr": string[];
    "nginx": string[];
    "nintendoGamecube": string[];
    "nintendo3ds": string[];
    "nodeJs": string[];
    "nintendoSwitch": string[];
    "nintendo": string[];
    "nodeRed": string[];
    "npm": string[];
    "nokia": string[];
    "node": string[];
    "nodemon": string[];
    "notion": string[];
    "ns8": string[];
    "nucleo": string[];
    "nuget": string[];
    "nuxtDotJs": string[];
    "nutritionix": string[];
    "octave": string[];
    "nvidia": string[];
    "oculus": string[];
    "octopusdeploy": string[];
    "ocaml": string[];
    "opencollective": string[];
    "odnoklassniki": string[];
    "openaccess": string[];
    "opencart": string[];
    "openid": string[];
    "opensourceinitiative": string[];
    "openvpn": string[];
    "opensuse": string[];
    "opsgenie": string[];
    "optinMonster": string[];
    "openstreetmap": string[];
    "opera": string[];
    "oracle": string[];
    "osi": string[];
    "osmc": string[];
    "origin": string[];
    "orcid": string[];
    "overcast": string[];
    "ovh": string[];
    "page4": string[];
    "overleaf": string[];
    "pagekit": string[];
    "paloaltosoftware": string[];
    "palantir": string[];
    "pagelines": string[];
    "palfed": string[];
    "pantheon": string[];
    "pandora": string[];
    "patreon": string[];
    "pennyArcade": string[];
    "periscope": string[];
    "paypal": string[];
    "phoenixSquadron": string[];
    "phabricator": string[];
    "phoenixFramework": string[];
    "php": string[];
    "picartoDotTv": string[];
    "piedPiperHat": string[];
    "piedPiper": string[];
    "piedPiperAlt": string[];
    "pinboard": string[];
    "piedPiperPp": string[];
    "pingup": string[];
    "pingdom": string[];
    "pinterestP": string[];
    "pinterest": string[];
    "playstation": string[];
    "pivotaltracker": string[];
    "playstation3": string[];
    "plangrid": string[];
    "playerDotMe": string[];
    "plesk": string[];
    "playerfm": string[];
    "pluralsight": string[];
    "playstation4": string[];
    "plex": string[];
    "pocket": string[];
    "plurk": string[];
    "postwoman": string[];
    "postgresql": string[];
    "powershell": string[];
    "prismic": string[];
    "prettier": string[];
    "postman": string[];
    "probot": string[];
    "producthunt": string[];
    "protoDotIo": string[];
    "protonmail": string[];
    "processwire": string[];
    "python": string[];
    "pushed": string[];
    "pypi": string[];
    "proxmox": string[];
    "pytorch": string[];
    "qiita": string[];
    "quantcast": string[];
    "qualcomm": string[];
    "qgis": string[];
    "quarkus": string[];
    "qq": string[];
    "quora": string[];
    "quinscape": string[];
    "quantopian": string[];
    "qwiklabs": string[];
    "rProject": string[];
    "rails": string[];
    "qzone": string[];
    "radiopublic": string[];
    "r": string[];
    "raspberrypi": string[];
    "reacteurope": string[];
    "ravelry": string[];
    "react": string[];
    "realm": string[];
    "reason": string[];
    "readme": string[];
    "readthedocs": string[];
    "rebel": string[];
    "redRiver": string[];
    "redditAlien": string[];
    "reddit": string[];
    "redhat": string[];
    "redbubble": string[];
    "replyd": string[];
    "renren": string[];
    "redis": string[];
    "redux": string[];
    "researchgate": string[];
    "resolving": string[];
    "rev": string[];
    "reverbnation": string[];
    "riot": string[];
    "ripple": string[];
    "rocketchat": string[];
    "rockrms": string[];
    "riseup": string[];
    "rollupJs": string[];
    "roots": string[];
    "roundcube": string[];
    "rstudio": string[];
    "rss": string[];
    "ruby": string[];
    "runkeeper": string[];
    "rubygems": string[];
    "rust": string[];
    "salesforce": string[];
    "sahibinden": string[];
    "saltstack": string[];
    "samsungPay": string[];
    "samsung": string[];
    "safari": string[];
    "sass": string[];
    "sap": string[];
    "scala": string[];
    "saucelabs": string[];
    "scaleway": string[];
    "scribd": string[];
    "scrutinizerci": string[];
    "schlix": string[];
    "sega": string[];
    "seagate": string[];
    "searchengin": string[];
    "semaphoreci": string[];
    "sellcast": string[];
    "sellfy": string[];
    "sensu": string[];
    "servicestack": string[];
    "sellsy": string[];
    "serverfault": string[];
    "sentry": string[];
    "shazam": string[];
    "shell": string[];
    "showpad": string[];
    "shirtsinbulk": string[];
    "shopify": string[];
    "simpleicons": string[];
    "shopware": string[];
    "siemens": string[];
    "signal": string[];
    "simplybuilt": string[];
    "sistrix": string[];
    "sitepoint": string[];
    "sinaweibo": string[];
    "sith": string[];
    "sketch": string[];
    "skyatlas": string[];
    "skillshare": string[];
    "skyliner": string[];
    "skype": string[];
    "slides": string[];
    "slickpic": string[];
    "slack": string[];
    "slackHash": string[];
    "slashdot": string[];
    "smashingmagazine": string[];
    "slideshare": string[];
    "snapchatGhost": string[];
    "snapchat": string[];
    "snapcraft": string[];
    "snyk": string[];
    "society6": string[];
    "sogou": string[];
    "socketDotIo": string[];
    "sonos": string[];
    "solus": string[];
    "sourceforge": string[];
    "songkick": string[];
    "soundcloud": string[];
    "sourcegraph": string[];
    "sourcetree": string[];
    "spacex": string[];
    "spacemacs": string[];
    "sparkfun": string[];
    "speakap": string[];
    "speakerdeck": string[];
    "sparkpost": string[];
    "speakerDeck": string[];
    "spdx": string[];
    "spectrum": string[];
    "spreaker": string[];
    "spotify": string[];
    "spotlight": string[];
    "spring": string[];
    "sprint": string[];
    "squarespace": string[];
    "stackExchange": string[];
    "stackOverflow": string[];
    "stackoverflow": string[];
    "stackbit": string[];
    "stackexchange": string[];
    "stadia": string[];
    "stackshare": string[];
    "stackpath": string[];
    "statamic": string[];
    "statuspage": string[];
    "steam": string[];
    "staticman": string[];
    "steem": string[];
    "staylinked": string[];
    "steamSymbol": string[];
    "stitcher": string[];
    "stickerMule": string[];
    "steemit": string[];
    "storify": string[];
    "storybook": string[];
    "stripe": string[];
    "strapi": string[];
    "studiovinari": string[];
    "strava": string[];
    "stubhub": string[];
    "stumbleuponCircle": string[];
    "stumbleupon": string[];
    "styleshare": string[];
    "stylus": string[];
    "superpowers": string[];
    "supple": string[];
    "sublimetext": string[];
    "superuser": string[];
    "subversion": string[];
    "svelte": string[];
    "suse": string[];
    "svg": string[];
    "swagger": string[];
    "swift": string[];
    "swarm": string[];
    "symantec": string[];
    "symfony": string[];
    "tableau": string[];
    "synology": string[];
    "tMobile": string[];
    "tails": string[];
    "tapas": string[];
    "ted": string[];
    "teamviewer": string[];
    "teamspeak": string[];
    "teespring": string[];
    "tencentqq": string[];
    "telegram": string[];
    "tencentweibo": string[];
    "tencentWeibo": string[];
    "tensorflow": string[];
    "terraform": string[];
    "themeco": string[];
    "tesla": string[];
    "theRedYeti": string[];
    "themoviedatabase": string[];
    "themighty": string[];
    "tidal": string[];
    "themeisle": string[];
    "tiktok": string[];
    "thinkPeaks": string[];
    "todoist": string[];
    "topcoder": string[];
    "toggl": string[];
    "toptal": string[];
    "tinder": string[];
    "tor": string[];
    "toshiba": string[];
    "travisci": string[];
    "trakt": string[];
    "trello": string[];
    "trainerroad": string[];
    "tripadvisor": string[];
    "trulia": string[];
    "tradeFederation": string[];
    "tumblr": string[];
    "treehouse": string[];
    "turkishairlines": string[];
    "twitch": string[];
    "twilio": string[];
    "typescript": string[];
    "twitter": string[];
    "twoo": string[];
    "typo3": string[];
    "ubisoft": string[];
    "uber": string[];
    "ubuntu": string[];
    "ublockorigin": string[];
    "udacity": string[];
    "uikit": string[];
    "umbraco": string[];
    "uniregistry": string[];
    "udemy": string[];
    "untappd": string[];
    "unity": string[];
    "unrealengine": string[];
    "unsplash": string[];
    "ups": string[];
    "upwork": string[];
    "ussunnah": string[];
    "usb": string[];
    "usps": string[];
    "vagrant": string[];
    "vaadin": string[];
    "v8": string[];
    "venmo": string[];
    "verizon": string[];
    "viacoin": string[];
    "viber": string[];
    "vim": string[];
    "viadeo": string[];
    "vine": string[];
    "vimeo": string[];
    "virb": string[];
    "visa": string[];
    "visualstudio": string[];
    "vk": string[];
    "visualstudiocode": string[];
    "vnv": string[];
    "vlc": string[];
    "vueJs": string[];
    "vsco": string[];
    "vuejs": string[];
    "wattpad": string[];
    "waze": string[];
    "webcomponentsDotOrg": string[];
    "webstorm": string[];
    "weasyl": string[];
    "weibo": string[];
    "wechat": string[];
    "webpack": string[];
    "weebly": string[];
    "weixin": string[];
    "whatsapp": string[];
    "wheniwork": string[];
    "wii": string[];
    "whmcs": string[];
    "wikipedia": string[];
    "wiiu": string[];
    "wireguard": string[];
    "wire": string[];
    "wolframLanguage": string[];
    "windows": string[];
    "wix": string[];
    "wolfPackBattalion": string[];
    "wolfram": string[];
    "wordpress": string[];
    "wolframMathematica": string[];
    "wpexplorer": string[];
    "wpengine": string[];
    "wizardsOfTheCoast": string[];
    "wpbeginner": string[];
    "wpforms": string[];
    "wpressr": string[];
    "xero": string[];
    "xPack": string[];
    "xbox": string[];
    "xcode": string[];
    "xrp": string[];
    "xiaomi": string[];
    "xing": string[];
    "yahoo": string[];
    "xsplit": string[];
    "yamahaMotorCorporation": string[];
    "yammer": string[];
    "yamahaCorporation": string[];
    "yarn": string[];
    "yandexInternational": string[];
    "ycombinator": string[];
    "yoast": string[];
    "yelp": string[];
    "yandex": string[];
    "youtube": string[];
    "zalando": string[];
    "zeit": string[];
    "zapier": string[];
    "zendesk": string[];
    "zerply": string[];
    "zhihu": string[];
    "zulip": string[];
    "zoom": string[];
    "zillow": string[];
    "zingat": string[];
    "zorin": string[];
    "apacheFlink": string[];
    "codewars": string[];
    "epicgames": string[];
    "flask": string[];
    "gerrit": string[];
    "gnu": string[];
    "greensock": string[];
    "oldRepublic": string[];
    "babel": string[];
    "composer": string[];
    "elsevier": string[];
};
export declare const iconjar: string[];
export declare const icq: string[];
export declare const ideal: string[];
export declare const ifixit: string[];
export declare const imdb: string[];
export declare const indeed: string[];
export declare const inkscape: string[];
export declare const instacart: string[];
export declare const instagram: string[];
export declare const instapaper: string[];
export declare const intel: string[];
export declare const intellijidea: string[];
export declare const intercom: string[];
export declare const internetExplorer: string[];
export declare const internetexplorer: string[];
export declare const invision: string[];
export declare const ionic: string[];
export declare const ioxhost: string[];
export declare const issuu: string[];
export declare const itchDotIo: string[];
export declare const itchIo: string[];
export declare const itunesNote: string[];
export declare const itunes: string[];
export declare const jabber: string[];
export declare const java: string[];
export declare const javascript: string[];
export declare const jediOrder: string[];
export declare const jekyll: string[];
export declare const jenkins: string[];
export declare const jest: string[];
export declare const jet: string[];
export declare const jetbrains: string[];
export declare const jira: string[];
export declare const joget: string[];
export declare const joomla: string[];
export declare const jquery: string[];
export declare const jsdelivr: string[];
export declare const jsfiddle: string[];
export declare const json: string[];
export declare const jupyter: string[];
export declare const justgiving: string[];
export declare const kaggle: string[];
export declare const kaios: string[];
export declare const kaspersky: string[];
export declare const kentico: string[];
export declare const keras: string[];
export declare const keybase: string[];
export declare const keycdn: string[];
export declare const khanacademy: string[];
export declare const kibana: string[];
export declare const kickstarter: string[];
export declare const kik: string[];
export declare const kirby: string[];
export declare const klout: string[];
export declare const known: string[];
export declare const koFi: string[];
export declare const kodi: string[];
export declare const koding: string[];
export declare const korvue: string[];
export declare const kotlin: string[];
export declare const krita: string[];
export declare const kubernetes: string[];
export declare const lanyrd: string[];
export declare const laravel: string[];
export declare const laravelhorizon: string[];
export declare const laravelnova: string[];
export declare const lastDotFm: string[];
export declare const lastfm: string[];
export declare const latex: string[];
export declare const launchpad: string[];
export declare const leanpub: string[];
export declare const leetcode: string[];
export declare const lenovo: string[];
export declare const less: string[];
export declare const letsencrypt: string[];
export declare const letterboxd: string[];
export declare const lgtm: string[];
export declare const liberapay: string[];
export declare const librarything: string[];
export declare const libreoffice: string[];
export declare const line: string[];
export declare const linewebtoon: string[];
export declare const linkedin: string[];
export declare const linode: string[];
export declare const linux: string[];
export declare const linuxfoundation: string[];
export declare const linuxmint: string[];
export declare const livejournal: string[];
export declare const livestream: string[];
export declare const logstash: string[];
export declare const lua: string[];
export declare const lumen: string[];
export declare const lyft: string[];
export declare const macys: string[];
export declare const magento: string[];
export declare const magisk: string[];
export declare const mailDotRu: string[];
export declare const mailchimp: string[];
export declare const makerbot: string[];
export declare const mandalorian: string[];
export declare const manjaro: string[];
export declare const markdown: string[];
export declare const marketo: string[];
export declare const mastercard: string[];
export declare const mastodon: string[];
export declare const materialdesign: string[];
export declare const mathworks: string[];
export declare const matrix: string[];
export declare const mattermost: string[];
export declare const matternet: string[];
export declare const maxcdn: string[];
export declare const mcafee: string[];
export declare const medapps: string[];
export declare const mediafire: string[];
export declare const mediatemple: string[];
export declare const medium: string[];
export declare const medrt: string[];
export declare const meetup: string[];
export declare const mega: string[];
export declare const megaport: string[];
export declare const mendeley: string[];
export declare const messenger: string[];
export declare const meteor: string[];
export declare const microDotBlog: string[];
export declare const microgenetics: string[];
export declare const microsoftEdge: string[];
export declare const microsoft: string[];
export declare const minetest: string[];
export declare const minutemailer: string[];
export declare const mix: string[];
export declare const mixcloud: string[];
export declare const mixer: string[];
export declare const mizuni: string[];
export declare const modx: string[];
export declare const mojang: string[];
export declare const monero: string[];
export declare const mongodb: string[];
export declare const monkeytie: string[];
export declare const monogram: string[];
export declare const monzo: string[];
export declare const moo: string[];
export declare const mozillaFirefox: string[];
export declare const mozilla: string[];
export declare const musescore: string[];
export declare const mxlinux: string[];
export declare const myspace: string[];
export declare const mysql: string[];
export declare const napster: string[];
export declare const nativescript: string[];
export declare const nec: string[];
export declare const neo4j: string[];
export declare const neos: string[];
export declare const netflix: string[];
export declare const netlify: string[];
export declare const nextJs: string[];
export declare const nextcloud: string[];
export declare const nextdoor: string[];
export declare const nginx: string[];
export declare const nim: string[];
export declare const nimblr: string[];
export declare const nintendo3ds: string[];
export declare const nintendoGamecube: string[];
export declare const nintendoSwitch: string[];
export declare const nintendo: string[];
export declare const nodeJs: string[];
export declare const nodeRed: string[];
export declare const node: string[];
export declare const nodemon: string[];
export declare const nokia: string[];
export declare const notion: string[];
export declare const npm: string[];
export declare const ns8: string[];
export declare const nucleo: string[];
export declare const nuget: string[];
export declare const nutritionix: string[];
export declare const nuxtDotJs: string[];
export declare const nvidia: string[];
export declare const ocaml: string[];
export declare const octave: string[];
export declare const octopusdeploy: string[];
export declare const oculus: string[];
export declare const odnoklassniki: string[];
export declare const oldRepublic: string[];
export declare const openaccess: string[];
export declare const opencart: string[];
export declare const opencollective: string[];
export declare const openid: string[];
export declare const opensourceinitiative: string[];
export declare const openstreetmap: string[];
export declare const opensuse: string[];
export declare const openvpn: string[];
export declare const opera: string[];
export declare const opsgenie: string[];
export declare const optinMonster: string[];
export declare const oracle: string[];
export declare const orcid: string[];
export declare const origin: string[];
export declare const osi: string[];
export declare const osmc: string[];
export declare const overcast: string[];
export declare const overleaf: string[];
export declare const ovh: string[];
export declare const page4: string[];
export declare const pagekit: string[];
export declare const pagelines: string[];
export declare const palantir: string[];
export declare const palfed: string[];
export declare const paloaltosoftware: string[];
export declare const pandora: string[];
export declare const pantheon: string[];
export declare const patreon: string[];
export declare const paypal: string[];
export declare const pennyArcade: string[];
export declare const periscope: string[];
export declare const phabricator: string[];
export declare const phoenixFramework: string[];
export declare const phoenixSquadron: string[];
export declare const php: string[];
export declare const picartoDotTv: string[];
export declare const piedPiperAlt: string[];
export declare const piedPiperHat: string[];
export declare const piedPiperPp: string[];
export declare const piedPiper: string[];
export declare const pinboard: string[];
export declare const pingdom: string[];
export declare const pingup: string[];
export declare const pinterestP: string[];
export declare const pinterest: string[];
export declare const pivotaltracker: string[];
export declare const plangrid: string[];
export declare const playerDotMe: string[];
export declare const playerfm: string[];
export declare const playstation: string[];
export declare const playstation3: string[];
export declare const playstation4: string[];
export declare const plesk: string[];
export declare const plex: string[];
export declare const pluralsight: string[];
export declare const plurk: string[];
export declare const pocket: string[];
export declare const postgresql: string[];
export declare const postman: string[];
export declare const postwoman: string[];
export declare const powershell: string[];
export declare const prettier: string[];
export declare const prismic: string[];
export declare const probot: string[];
export declare const processwire: string[];
export declare const producthunt: string[];
export declare const protoDotIo: string[];
export declare const protonmail: string[];
export declare const proxmox: string[];
export declare const pushed: string[];
export declare const pypi: string[];
export declare const python: string[];
export declare const pytorch: string[];
export declare const qgis: string[];
export declare const qiita: string[];
export declare const qq: string[];
export declare const qualcomm: string[];
export declare const quantcast: string[];
export declare const quantopian: string[];
export declare const quarkus: string[];
export declare const quinscape: string[];
export declare const quora: string[];
export declare const qwiklabs: string[];
export declare const qzone: string[];
export declare const rProject: string[];
export declare const r: string[];
export declare const radiopublic: string[];
export declare const rails: string[];
export declare const raspberrypi: string[];
export declare const ravelry: string[];
export declare const react: string[];
export declare const reacteurope: string[];
export declare const readme: string[];
export declare const readthedocs: string[];
export declare const realm: string[];
export declare const reason: string[];
export declare const rebel: string[];
export declare const redRiver: string[];
export declare const redbubble: string[];
export declare const redditAlien: string[];
export declare const reddit: string[];
export declare const redhat: string[];
export declare const redis: string[];
export declare const redux: string[];
export declare const renren: string[];
export declare const replyd: string[];
export declare const researchgate: string[];
export declare const resolving: string[];
export declare const rev: string[];
export declare const reverbnation: string[];
export declare const riot: string[];
export declare const ripple: string[];
export declare const riseup: string[];
export declare const rocketchat: string[];
export declare const rockrms: string[];
export declare const rollupJs: string[];
export declare const roots: string[];
export declare const roundcube: string[];
export declare const rss: string[];
export declare const rstudio: string[];
export declare const ruby: string[];
export declare const rubygems: string[];
export declare const runkeeper: string[];
export declare const rust: string[];
export declare const safari: string[];
export declare const sahibinden: string[];
export declare const salesforce: string[];
export declare const saltstack: string[];
export declare const samsungPay: string[];
export declare const samsung: string[];
export declare const sap: string[];
export declare const sass: string[];
export declare const saucelabs: string[];
export declare const scala: string[];
export declare const scaleway: string[];
export declare const schlix: string[];
export declare const scribd: string[];
export declare const scrutinizerci: string[];
export declare const seagate: string[];
export declare const searchengin: string[];
export declare const sega: string[];
export declare const sellcast: string[];
export declare const sellfy: string[];
export declare const sellsy: string[];
export declare const semaphoreci: string[];
export declare const sensu: string[];
export declare const sentry: string[];
export declare const serverfault: string[];
export declare const servicestack: string[];
export declare const shazam: string[];
export declare const shell: string[];
export declare const shirtsinbulk: string[];
export declare const shopify: string[];
export declare const shopware: string[];
export declare const showpad: string[];
export declare const siemens: string[];
export declare const signal: string[];
export declare const simpleicons: string[];
export declare const simplybuilt: string[];
export declare const sinaweibo: string[];
export declare const sistrix: string[];
export declare const sitepoint: string[];
export declare const sith: string[];
export declare const sketch: string[];
export declare const skillshare: string[];
export declare const skyatlas: string[];
export declare const skyliner: string[];
export declare const skype: string[];
export declare const slackHash: string[];
export declare const slack: string[];
export declare const slashdot: string[];
export declare const slickpic: string[];
export declare const slides: string[];
export declare const slideshare: string[];
export declare const smashingmagazine: string[];
export declare const snapchatGhost: string[];
export declare const snapchat: string[];
export declare const snapcraft: string[];
export declare const snyk: string[];
export declare const society6: string[];
export declare const socketDotIo: string[];
export declare const sogou: string[];
export declare const solus: string[];
export declare const songkick: string[];
export declare const sonos: string[];
export declare const soundcloud: string[];
export declare const sourceforge: string[];
export declare const sourcegraph: string[];
export declare const sourcetree: string[];
export declare const spacemacs: string[];
export declare const spacex: string[];
export declare const sparkfun: string[];
export declare const sparkpost: string[];
export declare const spdx: string[];
export declare const speakap: string[];
export declare const speakerDeck: string[];
export declare const speakerdeck: string[];
export declare const spectrum: string[];
export declare const spotify: string[];
export declare const spotlight: string[];
export declare const spreaker: string[];
export declare const spring: string[];
export declare const sprint: string[];
export declare const squarespace: string[];
export declare const stackExchange: string[];
export declare const stackOverflow: string[];
export declare const stackbit: string[];
export declare const stackexchange: string[];
export declare const stackoverflow: string[];
export declare const stackpath: string[];
export declare const stackshare: string[];
export declare const stadia: string[];
export declare const statamic: string[];
export declare const staticman: string[];
export declare const statuspage: string[];
export declare const staylinked: string[];
export declare const steamSymbol: string[];
export declare const steam: string[];
export declare const steem: string[];
export declare const steemit: string[];
export declare const stickerMule: string[];
export declare const stitcher: string[];
export declare const storify: string[];
export declare const storybook: string[];
export declare const strapi: string[];
export declare const strava: string[];
export declare const stripe: string[];
export declare const stubhub: string[];
export declare const studiovinari: string[];
export declare const stumbleuponCircle: string[];
export declare const stumbleupon: string[];
export declare const styleshare: string[];
export declare const stylus: string[];
export declare const sublimetext: string[];
export declare const subversion: string[];
export declare const superpowers: string[];
export declare const superuser: string[];
export declare const supple: string[];
export declare const suse: string[];
export declare const svelte: string[];
export declare const svg: string[];
export declare const swagger: string[];
export declare const swarm: string[];
export declare const swift: string[];
export declare const symantec: string[];
export declare const symfony: string[];
export declare const synology: string[];
export declare const tMobile: string[];
export declare const tableau: string[];
export declare const tails: string[];
export declare const tapas: string[];
export declare const teamspeak: string[];
export declare const teamviewer: string[];
export declare const ted: string[];
export declare const teespring: string[];
export declare const telegram: string[];
export declare const tencentWeibo: string[];
export declare const tencentqq: string[];
export declare const tencentweibo: string[];
export declare const tensorflow: string[];
export declare const terraform: string[];
export declare const tesla: string[];
export declare const theRedYeti: string[];
export declare const themeco: string[];
export declare const themeisle: string[];
export declare const themighty: string[];
export declare const themoviedatabase: string[];
export declare const thinkPeaks: string[];
export declare const tidal: string[];
export declare const tiktok: string[];
export declare const tinder: string[];
export declare const todoist: string[];
export declare const toggl: string[];
export declare const topcoder: string[];
export declare const toptal: string[];
export declare const tor: string[];
export declare const toshiba: string[];
export declare const tradeFederation: string[];
export declare const trainerroad: string[];
export declare const trakt: string[];
export declare const travisci: string[];
export declare const treehouse: string[];
export declare const trello: string[];
export declare const tripadvisor: string[];
export declare const trulia: string[];
export declare const tumblr: string[];
export declare const turkishairlines: string[];
export declare const twilio: string[];
export declare const twitch: string[];
export declare const twitter: string[];
export declare const twoo: string[];
export declare const typescript: string[];
export declare const typo3: string[];
export declare const uber: string[];
export declare const ubisoft: string[];
export declare const ublockorigin: string[];
export declare const ubuntu: string[];
export declare const udacity: string[];
export declare const udemy: string[];
export declare const uikit: string[];
export declare const umbraco: string[];
export declare const uniregistry: string[];
export declare const unity: string[];
export declare const unrealengine: string[];
export declare const unsplash: string[];
export declare const untappd: string[];
export declare const ups: string[];
export declare const upwork: string[];
export declare const usb: string[];
export declare const usps: string[];
export declare const ussunnah: string[];
export declare const v8: string[];
export declare const vaadin: string[];
export declare const vagrant: string[];
export declare const venmo: string[];
export declare const verizon: string[];
export declare const viacoin: string[];
export declare const viadeo: string[];
export declare const viber: string[];
export declare const vim: string[];
export declare const vimeo: string[];
export declare const vine: string[];
export declare const virb: string[];
export declare const visa: string[];
export declare const visualstudio: string[];
export declare const visualstudiocode: string[];
export declare const vk: string[];
export declare const vlc: string[];
export declare const vnv: string[];
export declare const vsco: string[];
export declare const vueJs: string[];
export declare const vuejs: string[];
export declare const wattpad: string[];
export declare const waze: string[];
export declare const weasyl: string[];
export declare const webcomponentsDotOrg: string[];
export declare const webpack: string[];
export declare const webstorm: string[];
export declare const wechat: string[];
export declare const weebly: string[];
export declare const weibo: string[];
export declare const weixin: string[];
export declare const whatsapp: string[];
export declare const wheniwork: string[];
export declare const whmcs: string[];
export declare const wii: string[];
export declare const wiiu: string[];
export declare const wikipedia: string[];
export declare const windows: string[];
export declare const wire: string[];
export declare const wireguard: string[];
export declare const wix: string[];
export declare const wizardsOfTheCoast: string[];
export declare const wolfPackBattalion: string[];
export declare const wolframLanguage: string[];
export declare const wolframMathematica: string[];
export declare const wolfram: string[];
export declare const wordpress: string[];
export declare const wpbeginner: string[];
export declare const wpengine: string[];
export declare const wpexplorer: string[];
export declare const wpforms: string[];
export declare const wpressr: string[];
export declare const xPack: string[];
export declare const xbox: string[];
export declare const xcode: string[];
export declare const xero: string[];
export declare const xiaomi: string[];
export declare const xing: string[];
export declare const xrp: string[];
export declare const xsplit: string[];
export declare const yahoo: string[];
export declare const yamahaCorporation: string[];
export declare const yamahaMotorCorporation: string[];
export declare const yammer: string[];
export declare const yandexInternational: string[];
export declare const yandex: string[];
export declare const yarn: string[];
export declare const ycombinator: string[];
export declare const yelp: string[];
export declare const yoast: string[];
export declare const youtube: string[];
export declare const zalando: string[];
export declare const zapier: string[];
export declare const zeit: string[];
export declare const zendesk: string[];
export declare const zerply: string[];
export declare const zhihu: string[];
export declare const zillow: string[];
export declare const zingat: string[];
export declare const zoom: string[];
export declare const zorin: string[];
export declare const zulip: string[];
