export declare const brandSet: {
  "n500px5": string[];
  "aboutMe": string[];
  "n500px": string[];
  "abstract": string[];
  "acm": string[];
  "addthis": string[];
  "adobeAcrobatReader": string[];
  "adguard": string[];
  "adobeAudition": string[];
  "adobeAftereFfects": string[];
  "adobeCreativeCloud": string[];
  "adobeDreamweaver": string[];
  "adobeIndesign": string[];
  "adobeIllustrator": string[];
  "adobeLightroomClassic": string[];
  "adobeLightroom": string[];
  "adobePremiere": string[];
  "adobePhotoshop": string[];
  "adobeTypekit": string[];
  "adobeXd": string[];
  "adobe": string[];
  "airbnb": string[];
  "algolia": string[];
  "alipay": string[];
  "allocine": string[];
  "amazonAws": string[];
  "amazonPay": string[];
  "amd": string[];
  "amazon": string[];
  "americanExpress": string[];
  "anaconda": string[];
  "analogue": string[];
  "androidAlt": string[];
  "android": string[];
  "angellist": string[];
  "angularUniversal": string[];
  "ansible": string[];
  "angular": string[];
  "apacheAirflow": string[];
  "apacheSpark": string[];
  "appStoreIos": string[];
  "apache": string[];
  "appleMusic": string[];
  "appStore": string[];
  "applePay": string[];
  "applePodcasts": string[];
  "appveyor": string[];
  "apple": string[];
  "aral": string[];
  "archLinux": string[];
  "archiveOfOurOwn": string[];
  "arduino": string[];
  "artstation": string[];
  "arxiv": string[];
  "asana": string[];
  "atAndT": string[];
  "atom": string[];
  "audible": string[];
  "atlassian": string[];
  "auth0": string[];
  "automatic": string[];
  "aurelia": string[];
  "autotask": string[];
  "aventrix": string[];
  "azureArtifacts": string[];
  "azureDevops": string[];
  "azurePipelines": string[];
  "baidu": string[];
  "bamboo": string[];
  "bandcamp": string[];
  "bancontact": string[];
  "bathasu": string[];
  "basecamp": string[];
  "bigCartel": string[];
  "behance": string[];
  "bing": string[];
  "bit": string[];
  "bitbucket": string[];
  "bitcoin": string[];
  "bitdefender": string[];
  "bitly": string[];
  "blackberry": string[];
  "bloggerB": string[];
  "blender": string[];
  "blogger": string[];
  "bluetoothB": string[];
  "bluetooth": string[];
  "boeing": string[];
  "boost": string[];
  "bootstrap": string[];
  "bower": string[];
  "brandAi": string[];
  "brave": string[];
  "btc": string[];
  "buddy": string[];
  "buyMeACoffee": string[];
  "buffer": string[];
  "buysellads": string[];
  "buzzfeed": string[];
  "cakephp": string[];
  "c": string[];
  "campaignMonitor": string[];
  "cashapp": string[];
  "canva": string[];
  "cassandra": string[];
  "castro": string[];
  "ccAmazonPay": string[];
  "ccApplePay": string[];
  "ccDinersClub": string[];
  "ccAmex": string[];
  "ccDiscover": string[];
  "ccJcb": string[];
  "ccPaypal": string[];
  "ccMastercard": string[];
  "ccStripe": string[];
  "ccVisa": string[];
  "cevo": string[];
  "centos": string[];
  "chase": string[];
  "chef": string[];
  "chromecast": string[];
  "circle": string[];
  "circleci": string[];
  "civicrm": string[];
  "cisco": string[];
  "cirrusci": string[];
  "clockify": string[];
  "cloudflare": string[];
  "clojure": string[];
  "cloudbees": string[];
  "coOp": string[];
  "codacy": string[];
  "cmake": string[];
  "codeClimate": string[];
  "codecademy": string[];
  "codecov": string[];
  "codeigniter": string[];
  "codepen": string[];
  "coderwall": string[];
  "codesandbox": string[];
  "codeship": string[];
  "codio": string[];
  "coffeescript": string[];
  "commonWorkflowLanguage": string[];
  "condaForge": string[];
  "conekta": string[];
  "confluence": string[];
  "coreui": string[];
  "coursera": string[];
  "coreuiC": string[];
  "coveralls": string[];
  "cplusplus": string[];
  "creativeCommonsBy": string[];
  "cpanel": string[];
  "creativeCommonsNcEu": string[];
  "creativeCommonsNcJp": string[];
  "creativeCommonsNc": string[];
  "creativeCommonsNd": string[];
  "creativeCommonsPdAlt": string[];
  "creativeCommonsPd": string[];
  "creativeCommonsRemix": string[];
  "creativeCommonsSa": string[];
  "creativeCommonsSamplingPlus": string[];
  "creativeCommonsSampling": string[];
  "creativeCommonsShare": string[];
  "creativeCommonsZero": string[];
  "creativeCommons": string[];
  "crunchyroll": string[];
  "crunchbase": string[];
  "css3Shiled": string[];
  "css3": string[];
  "d3Js": string[];
  "csswizardry": string[];
  "dailymotion": string[];
  "dashlane": string[];
  "dazn": string[];
  "dblp": string[];
  "debian": string[];
  "deepin": string[];
  "deezer": string[];
  "delicious": string[];
  "dell": string[];
  "designerNews": string[];
  "dependabot": string[];
  "devTo": string[];
  "deviantart": string[];
  "devrant": string[];
  "diaspora": string[];
  "digitalOcean": string[];
  "discord": string[];
  "digg": string[];
  "discourse": string[];
  "discover": string[];
  "disqus": string[];
  "disroot": string[];
  "docker": string[];
  "django": string[];
  "docusign": string[];
  "dotNet": string[];
  "dribbble": string[];
  "drone": string[];
  "draugiemLv": string[];
  "dropbox": string[];
  "drupal": string[];
  "duckduckgo": string[];
  "dtube": string[];
  "ebay": string[];
  "dynatrace": string[];
  "eclipseide": string[];
  "elasticSearch": string[];
  "elasticCloud": string[];
  "elementary": string[];
  "elasticStack": string[];
  "elastic": string[];
  "electron": string[];
  "eleventy": string[];
  "ello": string[];
  "emlakjet": string[];
  "empirekred": string[];
  "envato": string[];
  "epson": string[];
  "esea": string[];
  "eslint": string[];
  "ethereum": string[];
  "etsy": string[];
  "eventStore": string[];
  "eventbrite": string[];
  "evernote": string[];
  "everplaces": string[];
  "evry": string[];
  "expertsExchange": string[];
  "exercism": string[];
  "eyeem": string[];
  "expo": string[];
  "facebookF": string[];
  "fSecure": string[];
  "facebook": string[];
  "faceit": string[];
  "fandango": string[];
  "favro": string[];
  "feathub": string[];
  "fedora": string[];
  "fedex": string[];
  "feedly": string[];
  "fidoAlliance": string[];
  "figma": string[];
  "filezilla": string[];
  "firebase": string[];
  "fitbit": string[];
  "flickr": string[];
  "flattr": string[];
  "fnac": string[];
  "flipboard": string[];
  "foursquare": string[];
  "flutter": string[];
  "freebsd": string[];
  "framer": string[];
  "freecodecamp": string[];
  "furAffinity": string[];
  "furryNetwork": string[];
  "garmin": string[];
  "gatsby": string[];
  "gauges": string[];
  "genius": string[];
  "gentoo": string[];
  "geocaching": string[];
  "gg": string[];
  "ghost": string[];
  "gimp": string[];
  "git": string[];
  "gitea": string[];
  "github": string[];
  "gitkraken": string[];
  "gitlab": string[];
  "gitpod": string[];
  "gitter": string[];
  "glassdoor": string[];
  "gmail": string[];
  "gnuPrivacyGuard": string[];
  "glitch": string[];
  "gnuSocial": string[];
  "go": string[];
  "gogCom": string[];
  "goldenline": string[];
  "godotEngine": string[];
  "goodreads": string[];
  "googleAds": string[];
  "googleAnalytics": string[];
  "googleChrome": string[];
  "googleAllo": string[];
  "googleCloud": string[];
  "googleKeep": string[];
  "googlePay": string[];
  "googlePlay": string[];
  "govUk": string[];
  "google": string[];
  "gradle": string[];
  "googlesCholar": string[];
  "googlePodcasts": string[];
  "grafana": string[];
  "graphql": string[];
  "grav": string[];
  "graphcool": string[];
  "greenkeeper": string[];
  "gravatar": string[];
  "groupon": string[];
  "groovy": string[];
  "grunt": string[];
  "gulp": string[];
  "gumtree": string[];
  "gumroad": string[];
  "habr": string[];
  "hackerearth": string[];
  "hackerone": string[];
  "hackaday": string[];
  "hackerrank": string[];
  "hackhands": string[];
  "hackster": string[];
  "happycow": string[];
  "hashnode": string[];
  "haskell": string[];
  "hatenaBookmark": string[];
  "haxe": string[];
  "heroku": string[];
  "here": string[];
  "helm": string[];
  "hexo": string[];
  "highly": string[];
  "hipchat": string[];
  "hitachi": string[];
  "hockeyapp": string[];
  "homify": string[];
  "hotjar": string[];
  "hootsuite": string[];
  "houzz": string[];
  "hp": string[];
  "html5Shield": string[];
  "html5": string[];
  "htmlacademy": string[];
  "huawei": string[];
  "hubspot": string[];
  "hulu": string[];
  "humbleBundle": string[];
  "iata": string[];
  "ibm": string[];
  "icloud": string[];
  "ideal": string[];
  "ifixit": string[];
  "icq": string[];
  "imdb": string[];
  "iconjar": string[];
  "inkscape": string[];
  "indeed": string[];
  "instacart": string[];
  "instagram": string[];
  "instapaper": string[];
  "intellijidea": string[];
  "intel": string[];
  "intercom": string[];
  "ionic": string[];
  "invision": string[];
  "internetExplorer": string[];
  "issuu": string[];
  "jabber": string[];
  "itchIo": string[];
  "javascript": string[];
  "java": string[];
  "jekyll": string[];
  "jenkins": string[];
  "jest": string[];
  "jet": string[];
  "jetbrains": string[];
  "jira": string[];
  "joomla": string[];
  "js": string[];
  "jquery": string[];
  "jsfiddle": string[];
  "jsdelivr": string[];
  "justgiving": string[];
  "json": string[];
  "jupyter": string[];
  "kaggle": string[];
  "kaspersky": string[];
  "kaios": string[];
  "kentico": string[];
  "keras": string[];
  "keybase": string[];
  "keycdn": string[];
  "khanAcademy": string[];
  "kibana": string[];
  "kickstarter": string[];
  "kik": string[];
  "klout": string[];
  "kirby": string[];
  "kodi": string[];
  "koFi": string[];
  "koding": string[];
  "known": string[];
  "kotlin": string[];
  "krita": string[];
  "lanyrd": string[];
  "kubernetes": string[];
  "laravelHorizon": string[];
  "laravelNova": string[];
  "lastFm": string[];
  "laravel": string[];
  "latex": string[];
  "launchpad": string[];
  "leetcode": string[];
  "lenovo": string[];
  "less": string[];
  "letsEncrypt": string[];
  "lgtm": string[];
  "letterboxd": string[];
  "liberapay": string[];
  "librarything": string[];
  "libreoffice": string[];
  "line": string[];
  "linkedinIn": string[];
  "linkedin": string[];
  "linuxFoundation": string[];
  "linuxMint": string[];
  "linux": string[];
  "livejournal": string[];
  "livestream": string[];
  "lua": string[];
  "lumen": string[];
  "logstash": string[];
  "lyft": string[];
  "macys": string[];
  "magento": string[];
  "magisk": string[];
  "mailRu": string[];
  "makerbot": string[];
  "mailchimp": string[];
  "markdown": string[];
  "manjaro": string[];
  "marketo": string[];
  "mastercard": string[];
  "mastodon": string[];
  "materialDesign": string[];
  "matrix": string[];
  "mathworks": string[];
  "matternet": string[];
  "maxcdn": string[];
  "mcafee": string[];
  "mattermost": string[];
  "mediafire": string[];
  "mediumM": string[];
  "mediaTemple": string[];
  "meetup": string[];
  "medium": string[];
  "mega": string[];
  "messenger": string[];
  "mendeley": string[];
  "microBlog": string[];
  "meteor": string[];
  "microgenetics": string[];
  "microsoftEdge": string[];
  "microsoft": string[];
  "minetest": string[];
  "minutemailer": string[];
  "mix": string[];
  "mixcloud": string[];
  "mojang": string[];
  "monero": string[];
  "mixer": string[];
  "monkeytie": string[];
  "mongodb": string[];
  "monogram": string[];
  "monzo": string[];
  "moo": string[];
  "mozillaFirefox": string[];
  "mozilla": string[];
  "musescore": string[];
  "mxlinux": string[];
  "myspace": string[];
  "nativescript": string[];
  "nec": string[];
  "neo4j": string[];
  "mysql": string[];
  "netlify": string[];
  "nextJs": string[];
  "nextcloud": string[];
  "netflix": string[];
  "nextdoor": string[];
  "nginx": string[];
  "nim": string[];
  "nintendoGamecube": string[];
  "nintendoSwitch": string[];
  "nintendo": string[];
  "nintendo3ds": string[];
  "nodemon": string[];
  "nodeRed": string[];
  "nodeJs": string[];
  "nokia": string[];
  "notion": string[];
  "npm": string[];
  "nucleo": string[];
  "nvidia": string[];
  "nuget": string[];
  "nuxtJs": string[];
  "ocaml": string[];
  "octave": string[];
  "oculus": string[];
  "octopusDeploy": string[];
  "odnoklassniki": string[];
  "openCollective": string[];
  "openAccess": string[];
  "openId": string[];
  "openSourceInitiative": string[];
  "openstreetmap": string[];
  "openvpn": string[];
  "opensuse": string[];
  "opera": string[];
  "opsgenie": string[];
  "oracle": string[];
  "orcid": string[];
  "origin": string[];
  "osmc": string[];
  "osi": string[];
  "overcast": string[];
  "ovh": string[];
  "palantir": string[];
  "pagekit": string[];
  "overleaf": string[];
  "pandora": string[];
  "pantheon": string[];
  "paypal": string[];
  "php": string[];
  "patreon": string[];
  "periscope": string[];
  "pinboard": string[];
  "picartoTv": string[];
  "pingdom": string[];
  "pingup": string[];
  "pinterestP": string[];
  "pinterest": string[];
  "pivotaltracker": string[];
  "plangrid": string[];
  "playerMe": string[];
  "playerfm": string[];
  "playstation": string[];
  "playstation3": string[];
  "playstation4": string[];
  "plesk": string[];
  "plex": string[];
  "plurk": string[];
  "pluralsight": string[];
  "pocket": string[];
  "postman": string[];
  "postwoman": string[];
  "postgresql": string[];
  "prismic": string[];
  "powershell": string[];
  "prettier": string[];
  "probot": string[];
  "productHunt": string[];
  "processwire": string[];
  "protonmail": string[];
  "protoIo": string[];
  "proxmox": string[];
  "pypi": string[];
  "pytorch": string[];
  "python": string[];
  "qiita": string[];
  "qgis": string[];
  "qq": string[];
  "qualcomm": string[];
  "quantcast": string[];
  "quantopian": string[];
  "quarkus": string[];
  "qwiklabs": string[];
  "qzone": string[];
  "quora": string[];
  "r": string[];
  "radiopublic": string[];
  "rails": string[];
  "raspberryPi": string[];
  "readTheDocs": string[];
  "react": string[];
  "readme": string[];
  "realm": string[];
  "redbubble": string[];
  "reason": string[];
  "redditAlt": string[];
  "redhat": string[];
  "reddit": string[];
  "redis": string[];
  "riot": string[];
  "redux": string[];
  "reverbnation": string[];
  "renren": string[];
  "riseup": string[];
  "ripple": string[];
  "rollupJs": string[];
  "roots": string[];
  "rss": string[];
  "rstudio": string[];
  "roundcube": string[];
  "ruby": string[];
  "rubygems": string[];
  "runkeeper": string[];
  "safari": string[];
  "rust": string[];
  "sahibinden": string[];
  "salesforce": string[];
  "saltstack": string[];
  "samsungPay": string[];
  "sap": string[];
  "samsung": string[];
  "sassAlt": string[];
  "sass": string[];
  "scala": string[];
  "saucelabs": string[];
  "scribd": string[];
  "scaleway": string[];
  "scrutinizerci": string[];
  "seagate": string[];
  "sega": string[];
  "sellfy": string[];
  "semaphoreci": string[];
  "sentry": string[];
  "sensu": string[];
  "serverFault": string[];
  "shazam": string[];
  "shopify": string[];
  "shell": string[];
  "showpad": string[];
  "signal": string[];
  "sinaWeibo": string[];
  "siemens": string[];
  "sitepoint": string[];
  "sketch": string[];
  "skillshare": string[];
  "skyliner": string[];
  "skype": string[];
  "slack": string[];
  "slashdot": string[];
  "slickpic": string[];
  "slides": string[];
  "slideshare": string[];
  "smashingmagazine": string[];
  "snapchat": string[];
  "snapcraft": string[];
  "snyk": string[];
  "society6": string[];
  "socketIo": string[];
  "sogou": string[];
  "songkick": string[];
  "solus": string[];
  "sourceforge": string[];
  "sourcegraph": string[];
  "soundcloud": string[];
  "sonos": string[];
  "spacemacs": string[];
  "spacex": string[];
  "sparkfun": string[];
  "sparkpost": string[];
  "spdx": string[];
  "spectrum": string[];
  "spotify": string[];
  "spreaker": string[];
  "speakerDeck": string[];
  "spring": string[];
  "spotlight": string[];
  "sprint": string[];
  "stackexchange": string[];
  "stackoverflow": string[];
  "stackbit": string[];
  "squarespace": string[];
  "stadia": string[];
  "stackshare": string[];
  "stackpath": string[];
  "statamic": string[];
  "staticman": string[];
  "statuspage": string[];
  "steam": string[];
  "steem": string[];
  "steemit": string[];
  "stitcher": string[];
  "storify": string[];
  "strapi": string[];
  "storybook": string[];
  "strava": string[];
  "stripe": string[];
  "stubhub": string[];
  "stripeS": string[];
  "stumbleupon": string[];
  "styleshare": string[];
  "stylus": string[];
  "sublimeText": string[];
  "subversion": string[];
  "superuser": string[];
  "svelte": string[];
  "svg": string[];
  "swagger": string[];
  "swarm": string[];
  "swift": string[];
  "symantec": string[];
  "symfony": string[];
  "synology": string[];
  "tMobile": string[];
  "tableau": string[];
  "tails": string[];
  "tapas": string[];
  "teamviewer": string[];
  "ted": string[];
  "teespring": string[];
  "telegramPlane": string[];
  "telegram": string[];
  "tencentQq": string[];
  "tensorflow": string[];
  "terraform": string[];
  "tencentWeibo": string[];
  "tesla": string[];
  "theMighty": string[];
  "tidal": string[];
  "theMovieDatabase": string[];
  "tinder": string[];
  "tiktok": string[];
  "todoist": string[];
  "toggl": string[];
  "topcoder": string[];
  "tor": string[];
  "toptal": string[];
  "trainerroad": string[];
  "toshiba": string[];
  "trakt": string[];
  "treehouse": string[];
  "trello": string[];
  "tripadvisor": string[];
  "tumblr": string[];
  "trulia": string[];
  "twilio": string[];
  "twitch": string[];
  "twitter": string[];
  "twoo": string[];
  "typescript": string[];
  "uber": string[];
  "typo3": string[];
  "ublockOrigin": string[];
  "ubisoft": string[];
  "ubuntu": string[];
  "udacity": string[];
  "udemy": string[];
  "uikit": string[];
  "unrealEngine": string[];
  "unity": string[];
  "umbraco": string[];
  "unsplash": string[];
  "untappd": string[];
  "upwork": string[];
  "usb": string[];
  "v8": string[];
  "vagrant": string[];
  "verizon": string[];
  "venmo": string[];
  "viber": string[];
  "vim": string[];
  "viadeo": string[];
  "vimeoV": string[];
  "vimeo": string[];
  "vine": string[];
  "virb": string[];
  "visa": string[];
  "visualStudioCode": string[];
  "visualStudio": string[];
  "vk": string[];
  "vlc": string[];
  "vsco": string[];
  "vueJs": string[];
  "weasyl": string[];
  "wattpad": string[];
  "webpack": string[];
  "webcomponentsOrg": string[];
  "webstorm": string[];
  "wechat": string[];
  "whatsapp": string[];
  "wii": string[];
  "whenIWork": string[];
  "wikipedia": string[];
  "wiiu": string[];
  "windows": string[];
  "wire": string[];
  "wireguard": string[];
  "wix": string[];
  "wolframLanguage": string[];
  "wolframMathematica": string[];
  "wolfram": string[];
  "wordpress": string[];
  "wpengine": string[];
  "xPack": string[];
  "xbox": string[];
  "xcode": string[];
  "xero": string[];
  "xiaomi": string[];
  "xing": string[];
  "xrp": string[];
  "xsplit": string[];
  "yCombinator": string[];
  "yahoo": string[];
  "yammer": string[];
  "yandex": string[];
  "yarn": string[];
  "yelp": string[];
  "youtube": string[];
  "zalando": string[];
  "zapier": string[];
  "zeit": string[];
  "zendesk": string[];
  "zerply": string[];
  "zillow": string[];
  "zingat": string[];
  "zoom": string[];
  "zorin": string[];
  "zulip": string[];
  "deno": string[];
  "epicGames": string[];
  "flask": string[];
  "gerrit": string[];
  "greensock": string[];
  "travisci": string[];
  "apacheFlink": string[];
  "babel": string[];
  "codewars": string[];
  "gnu": string[];
  "composer": string[];
  "elsevier": string[];
}
export declare const n500px5: string[];
export declare const aboutMe: string[];
export declare const n500px: string[];
export declare const abstract: string[];
export declare const acm: string[];
export declare const addthis: string[];
export declare const adobeAcrobatReader: string[];
export declare const adguard: string[];
export declare const adobeAudition: string[];
export declare const adobeAftereFfects: string[];
export declare const adobeCreativeCloud: string[];
export declare const adobeDreamweaver: string[];
export declare const adobeIndesign: string[];
export declare const adobeIllustrator: string[];
export declare const adobeLightroomClassic: string[];
export declare const adobeLightroom: string[];
export declare const adobePremiere: string[];
export declare const adobePhotoshop: string[];
export declare const adobeTypekit: string[];
export declare const adobeXd: string[];
export declare const adobe: string[];
export declare const airbnb: string[];
export declare const algolia: string[];
export declare const alipay: string[];
export declare const allocine: string[];
export declare const amazonAws: string[];
export declare const amazonPay: string[];
export declare const amd: string[];
export declare const amazon: string[];
export declare const americanExpress: string[];
export declare const anaconda: string[];
export declare const analogue: string[];
export declare const androidAlt: string[];
export declare const android: string[];
export declare const angellist: string[];
export declare const angularUniversal: string[];
export declare const ansible: string[];
export declare const angular: string[];
export declare const apacheAirflow: string[];
export declare const apacheSpark: string[];
export declare const appStoreIos: string[];
export declare const apache: string[];
export declare const appleMusic: string[];
export declare const appStore: string[];
export declare const applePay: string[];
export declare const applePodcasts: string[];
export declare const appveyor: string[];
export declare const apple: string[];
export declare const aral: string[];
export declare const archLinux: string[];
export declare const archiveOfOurOwn: string[];
export declare const arduino: string[];
export declare const artstation: string[];
export declare const arxiv: string[];
export declare const asana: string[];
export declare const atAndT: string[];
export declare const atom: string[];
export declare const audible: string[];
export declare const atlassian: string[];
export declare const auth0: string[];
export declare const automatic: string[];
export declare const aurelia: string[];
export declare const autotask: string[];
export declare const aventrix: string[];
export declare const azureArtifacts: string[];
export declare const azureDevops: string[];
export declare const azurePipelines: string[];
export declare const baidu: string[];
export declare const bamboo: string[];
export declare const bandcamp: string[];
export declare const bancontact: string[];
export declare const bathasu: string[];
export declare const basecamp: string[];
export declare const bigCartel: string[];
export declare const behance: string[];
export declare const bing: string[];
export declare const bit: string[];
export declare const bitbucket: string[];
export declare const bitcoin: string[];
export declare const bitdefender: string[];
export declare const bitly: string[];
export declare const blackberry: string[];
export declare const bloggerB: string[];
export declare const blender: string[];
export declare const blogger: string[];
export declare const bluetoothB: string[];
export declare const bluetooth: string[];
export declare const boeing: string[];
export declare const boost: string[];
export declare const bootstrap: string[];
export declare const bower: string[];
export declare const brandAi: string[];
export declare const brave: string[];
export declare const btc: string[];
export declare const buddy: string[];
export declare const buyMeACoffee: string[];
export declare const buffer: string[];
export declare const buysellads: string[];
export declare const buzzfeed: string[];
export declare const cakephp: string[];
export declare const c: string[];
export declare const campaignMonitor: string[];
export declare const cashapp: string[];
export declare const canva: string[];
export declare const cassandra: string[];
export declare const castro: string[];
export declare const ccAmazonPay: string[];
export declare const ccApplePay: string[];
export declare const ccDinersClub: string[];
export declare const ccAmex: string[];
export declare const ccDiscover: string[];
export declare const ccJcb: string[];
export declare const ccPaypal: string[];
export declare const ccMastercard: string[];
export declare const ccStripe: string[];
export declare const ccVisa: string[];
export declare const cevo: string[];
export declare const centos: string[];
export declare const chase: string[];
export declare const chef: string[];
export declare const chromecast: string[];
export declare const circle: string[];
export declare const circleci: string[];
export declare const civicrm: string[];
export declare const cisco: string[];
export declare const cirrusci: string[];
export declare const clockify: string[];
export declare const cloudflare: string[];
export declare const clojure: string[];
export declare const cloudbees: string[];
export declare const coOp: string[];
export declare const codacy: string[];
export declare const cmake: string[];
export declare const codeClimate: string[];
export declare const codecademy: string[];
export declare const codecov: string[];
export declare const codeigniter: string[];
export declare const codepen: string[];
export declare const coderwall: string[];
export declare const codesandbox: string[];
export declare const codeship: string[];
export declare const codio: string[];
export declare const coffeescript: string[];
export declare const commonWorkflowLanguage: string[];
export declare const condaForge: string[];
export declare const conekta: string[];
export declare const confluence: string[];
export declare const coreui: string[];
export declare const coursera: string[];
export declare const coreuiC: string[];
export declare const coveralls: string[];
export declare const cplusplus: string[];
export declare const creativeCommonsBy: string[];
export declare const cpanel: string[];
export declare const creativeCommonsNcEu: string[];
export declare const creativeCommonsNcJp: string[];
export declare const creativeCommonsNc: string[];
export declare const creativeCommonsNd: string[];
export declare const creativeCommonsPdAlt: string[];
export declare const creativeCommonsPd: string[];
export declare const creativeCommonsRemix: string[];
export declare const creativeCommonsSa: string[];
export declare const creativeCommonsSamplingPlus: string[];
export declare const creativeCommonsSampling: string[];
export declare const creativeCommonsShare: string[];
export declare const creativeCommonsZero: string[];
export declare const creativeCommons: string[];
export declare const crunchyroll: string[];
export declare const crunchbase: string[];
export declare const css3Shiled: string[];
export declare const css3: string[];
export declare const d3Js: string[];
export declare const csswizardry: string[];
export declare const dailymotion: string[];
export declare const dashlane: string[];
export declare const dazn: string[];
export declare const dblp: string[];
export declare const debian: string[];
export declare const deepin: string[];
export declare const deezer: string[];
export declare const delicious: string[];
export declare const dell: string[];
export declare const designerNews: string[];
export declare const dependabot: string[];
export declare const devTo: string[];
export declare const deviantart: string[];
export declare const devrant: string[];
export declare const diaspora: string[];
export declare const digitalOcean: string[];
export declare const discord: string[];
export declare const digg: string[];
export declare const discourse: string[];
export declare const discover: string[];
export declare const disqus: string[];
export declare const disroot: string[];
export declare const docker: string[];
export declare const django: string[];
export declare const docusign: string[];
export declare const dotNet: string[];
export declare const dribbble: string[];
export declare const drone: string[];
export declare const draugiemLv: string[];
export declare const dropbox: string[];
export declare const drupal: string[];
export declare const duckduckgo: string[];
export declare const dtube: string[];
export declare const ebay: string[];
export declare const dynatrace: string[];
export declare const eclipseide: string[];
export declare const elasticSearch: string[];
export declare const elasticCloud: string[];
export declare const elementary: string[];
export declare const elasticStack: string[];
export declare const elastic: string[];
export declare const electron: string[];
export declare const eleventy: string[];
export declare const ello: string[];
export declare const emlakjet: string[];
export declare const empirekred: string[];
export declare const envato: string[];
export declare const epson: string[];
export declare const esea: string[];
export declare const eslint: string[];
export declare const ethereum: string[];
export declare const etsy: string[];
export declare const eventStore: string[];
export declare const eventbrite: string[];
export declare const evernote: string[];
export declare const everplaces: string[];
export declare const evry: string[];
export declare const expertsExchange: string[];
export declare const exercism: string[];
export declare const eyeem: string[];
export declare const expo: string[];
export declare const facebookF: string[];
export declare const fSecure: string[];
export declare const facebook: string[];
export declare const faceit: string[];
export declare const fandango: string[];
export declare const favro: string[];
export declare const feathub: string[];
export declare const fedora: string[];
export declare const fedex: string[];
export declare const feedly: string[];
export declare const fidoAlliance: string[];
export declare const figma: string[];
export declare const filezilla: string[];
export declare const firebase: string[];
export declare const fitbit: string[];
export declare const flickr: string[];
export declare const flattr: string[];
export declare const fnac: string[];
export declare const flipboard: string[];
export declare const foursquare: string[];
export declare const flutter: string[];
export declare const freebsd: string[];
export declare const framer: string[];
export declare const freecodecamp: string[];
export declare const furAffinity: string[];
export declare const furryNetwork: string[];
export declare const garmin: string[];
export declare const gatsby: string[];
export declare const gauges: string[];
export declare const genius: string[];
export declare const gentoo: string[];
export declare const geocaching: string[];
export declare const gg: string[];
export declare const ghost: string[];
export declare const gimp: string[];
export declare const git: string[];
export declare const gitea: string[];
export declare const github: string[];
export declare const gitkraken: string[];
export declare const gitlab: string[];
export declare const gitpod: string[];
export declare const gitter: string[];
export declare const glassdoor: string[];
export declare const gmail: string[];
export declare const gnuPrivacyGuard: string[];
export declare const glitch: string[];
export declare const gnuSocial: string[];
export declare const go: string[];
export declare const gogCom: string[];
export declare const goldenline: string[];
export declare const godotEngine: string[];
export declare const goodreads: string[];
export declare const googleAds: string[];
export declare const googleAnalytics: string[];
export declare const googleChrome: string[];
export declare const googleAllo: string[];
export declare const googleCloud: string[];
export declare const googleKeep: string[];
export declare const googlePay: string[];
export declare const googlePlay: string[];
export declare const govUk: string[];
export declare const google: string[];
export declare const gradle: string[];
export declare const googlesCholar: string[];
export declare const googlePodcasts: string[];
export declare const grafana: string[];
export declare const graphql: string[];
export declare const grav: string[];
export declare const graphcool: string[];
export declare const greenkeeper: string[];
export declare const gravatar: string[];
export declare const groupon: string[];
export declare const groovy: string[];
export declare const grunt: string[];
export declare const gulp: string[];
export declare const gumtree: string[];
export declare const gumroad: string[];
export declare const habr: string[];
export declare const hackerearth: string[];
export declare const hackerone: string[];
export declare const hackaday: string[];
export declare const hackerrank: string[];
export declare const hackhands: string[];
export declare const hackster: string[];
export declare const happycow: string[];
export declare const hashnode: string[];
export declare const haskell: string[];
export declare const hatenaBookmark: string[];
export declare const haxe: string[];
export declare const heroku: string[];
export declare const here: string[];
export declare const helm: string[];
export declare const hexo: string[];
export declare const highly: string[];
export declare const hipchat: string[];
export declare const hitachi: string[];
export declare const hockeyapp: string[];
export declare const homify: string[];
export declare const hotjar: string[];
export declare const hootsuite: string[];
export declare const houzz: string[];
export declare const hp: string[];
export declare const html5Shield: string[];
export declare const html5: string[];
export declare const htmlacademy: string[];
export declare const huawei: string[];
export declare const hubspot: string[];
export declare const hulu: string[];
export declare const humbleBundle: string[];
export declare const iata: string[];
export declare const ibm: string[];
export declare const icloud: string[];
export declare const ideal: string[];
export declare const ifixit: string[];
export declare const icq: string[];
export declare const imdb: string[];
export declare const iconjar: string[];
export declare const inkscape: string[];
export declare const indeed: string[];
export declare const instacart: string[];
export declare const instagram: string[];
export declare const instapaper: string[];
export declare const intellijidea: string[];
export declare const intel: string[];
export declare const intercom: string[];
export declare const ionic: string[];
export declare const invision: string[];
export declare const internetExplorer: string[];
export declare const issuu: string[];
export declare const jabber: string[];
export declare const itchIo: string[];
export declare const javascript: string[];
export declare const java: string[];
export declare const jekyll: string[];
export declare const jenkins: string[];
export declare const jest: string[];
export declare const jet: string[];
export declare const jetbrains: string[];
export declare const jira: string[];
export declare const joomla: string[];
export declare const js: string[];
export declare const jquery: string[];
export declare const jsfiddle: string[];
export declare const jsdelivr: string[];
export declare const justgiving: string[];
export declare const json: string[];
export declare const jupyter: string[];
export declare const kaggle: string[];
export declare const kaspersky: string[];
export declare const kaios: string[];
export declare const kentico: string[];
export declare const keras: string[];
export declare const keybase: string[];
export declare const keycdn: string[];
export declare const khanAcademy: string[];
export declare const kibana: string[];
export declare const kickstarter: string[];
export declare const kik: string[];
export declare const klout: string[];
export declare const kirby: string[];
export declare const kodi: string[];
export declare const koFi: string[];
export declare const koding: string[];
export declare const known: string[];
export declare const kotlin: string[];
export declare const krita: string[];
export declare const lanyrd: string[];
export declare const kubernetes: string[];
export declare const laravelHorizon: string[];
export declare const laravelNova: string[];
export declare const lastFm: string[];
export declare const laravel: string[];
export declare const latex: string[];
export declare const launchpad: string[];
export declare const leetcode: string[];
export declare const lenovo: string[];
export declare const less: string[];
export declare const letsEncrypt: string[];
export declare const lgtm: string[];
export declare const letterboxd: string[];
export declare const liberapay: string[];
export declare const librarything: string[];
export declare const libreoffice: string[];
export declare const line: string[];
export declare const linkedinIn: string[];
export declare const linkedin: string[];
export declare const linuxFoundation: string[];
export declare const linuxMint: string[];
export declare const linux: string[];
export declare const livejournal: string[];
export declare const livestream: string[];
export declare const lua: string[];
export declare const lumen: string[];
export declare const logstash: string[];
export declare const lyft: string[];
export declare const macys: string[];
export declare const magento: string[];
export declare const magisk: string[];
export declare const mailRu: string[];
export declare const makerbot: string[];
export declare const mailchimp: string[];
export declare const markdown: string[];
export declare const manjaro: string[];
export declare const marketo: string[];
export declare const mastercard: string[];
export declare const mastodon: string[];
export declare const materialDesign: string[];
export declare const matrix: string[];
export declare const mathworks: string[];
export declare const matternet: string[];
export declare const maxcdn: string[];
export declare const mcafee: string[];
export declare const mattermost: string[];
export declare const mediafire: string[];
export declare const mediumM: string[];
export declare const mediaTemple: string[];
export declare const meetup: string[];
export declare const medium: string[];
export declare const mega: string[];
export declare const messenger: string[];
export declare const mendeley: string[];
export declare const microBlog: string[];
export declare const meteor: string[];
export declare const microgenetics: string[];
export declare const microsoftEdge: string[];
export declare const microsoft: string[];
export declare const minetest: string[];
export declare const minutemailer: string[];
export declare const mix: string[];
export declare const mixcloud: string[];
export declare const mojang: string[];
export declare const monero: string[];
export declare const mixer: string[];
export declare const monkeytie: string[];
export declare const mongodb: string[];
export declare const monogram: string[];
export declare const monzo: string[];
export declare const moo: string[];
export declare const mozillaFirefox: string[];
export declare const mozilla: string[];
export declare const musescore: string[];
export declare const mxlinux: string[];
export declare const myspace: string[];
export declare const nativescript: string[];
export declare const nec: string[];
export declare const neo4j: string[];
export declare const mysql: string[];
export declare const netlify: string[];
export declare const nextJs: string[];
export declare const nextcloud: string[];
export declare const netflix: string[];
export declare const nextdoor: string[];
export declare const nginx: string[];
export declare const nim: string[];
export declare const nintendoGamecube: string[];
export declare const nintendoSwitch: string[];
export declare const nintendo: string[];
export declare const nintendo3ds: string[];
export declare const nodemon: string[];
export declare const nodeRed: string[];
export declare const nodeJs: string[];
export declare const nokia: string[];
export declare const notion: string[];
export declare const npm: string[];
export declare const nucleo: string[];
export declare const nvidia: string[];
export declare const nuget: string[];
export declare const nuxtJs: string[];
export declare const ocaml: string[];
export declare const octave: string[];
export declare const oculus: string[];
export declare const octopusDeploy: string[];
export declare const odnoklassniki: string[];
export declare const openCollective: string[];
export declare const openAccess: string[];
export declare const openId: string[];
export declare const openSourceInitiative: string[];
export declare const openstreetmap: string[];
export declare const openvpn: string[];
export declare const opensuse: string[];
export declare const opera: string[];
export declare const opsgenie: string[];
export declare const oracle: string[];
export declare const orcid: string[];
export declare const origin: string[];
export declare const osmc: string[];
export declare const osi: string[];
export declare const overcast: string[];
export declare const ovh: string[];
export declare const palantir: string[];
export declare const pagekit: string[];
export declare const overleaf: string[];
export declare const pandora: string[];
export declare const pantheon: string[];
export declare const paypal: string[];
export declare const php: string[];
export declare const patreon: string[];
export declare const periscope: string[];
export declare const pinboard: string[];
export declare const picartoTv: string[];
export declare const pingdom: string[];
export declare const pingup: string[];
export declare const pinterestP: string[];
export declare const pinterest: string[];
export declare const pivotaltracker: string[];
export declare const plangrid: string[];
export declare const playerMe: string[];
export declare const playerfm: string[];
export declare const playstation: string[];
export declare const playstation3: string[];
export declare const playstation4: string[];
export declare const plesk: string[];
export declare const plex: string[];
export declare const plurk: string[];
export declare const pluralsight: string[];
export declare const pocket: string[];
export declare const postman: string[];
export declare const postwoman: string[];
export declare const postgresql: string[];
export declare const prismic: string[];
export declare const powershell: string[];
export declare const prettier: string[];
export declare const probot: string[];
export declare const productHunt: string[];
export declare const processwire: string[];
export declare const protonmail: string[];
export declare const protoIo: string[];
export declare const proxmox: string[];
export declare const pypi: string[];
export declare const pytorch: string[];
export declare const python: string[];
export declare const qiita: string[];
export declare const qgis: string[];
export declare const qq: string[];
export declare const qualcomm: string[];
export declare const quantcast: string[];
export declare const quantopian: string[];
export declare const quarkus: string[];
export declare const qwiklabs: string[];
export declare const qzone: string[];
export declare const quora: string[];
export declare const r: string[];
export declare const radiopublic: string[];
export declare const rails: string[];
export declare const raspberryPi: string[];
export declare const readTheDocs: string[];
export declare const react: string[];
export declare const readme: string[];
export declare const realm: string[];
export declare const redbubble: string[];
export declare const reason: string[];
export declare const redditAlt: string[];
export declare const redhat: string[];
export declare const reddit: string[];
export declare const redis: string[];
export declare const riot: string[];
export declare const redux: string[];
export declare const reverbnation: string[];
export declare const renren: string[];
export declare const riseup: string[];
export declare const ripple: string[];
export declare const rollupJs: string[];
export declare const roots: string[];
export declare const rss: string[];
export declare const rstudio: string[];
export declare const roundcube: string[];
export declare const ruby: string[];
export declare const rubygems: string[];
export declare const runkeeper: string[];
export declare const safari: string[];
export declare const rust: string[];
export declare const sahibinden: string[];
export declare const salesforce: string[];
export declare const saltstack: string[];
export declare const samsungPay: string[];
export declare const sap: string[];
export declare const samsung: string[];
export declare const sassAlt: string[];
export declare const sass: string[];
export declare const scala: string[];
export declare const saucelabs: string[];
export declare const scribd: string[];
export declare const scaleway: string[];
export declare const scrutinizerci: string[];
export declare const seagate: string[];
export declare const sega: string[];
export declare const sellfy: string[];
export declare const semaphoreci: string[];
export declare const sentry: string[];
export declare const sensu: string[];
export declare const serverFault: string[];
export declare const shazam: string[];
export declare const shopify: string[];
export declare const shell: string[];
export declare const showpad: string[];
export declare const signal: string[];
export declare const sinaWeibo: string[];
export declare const siemens: string[];
export declare const sitepoint: string[];
export declare const sketch: string[];
export declare const skillshare: string[];
export declare const skyliner: string[];
export declare const skype: string[];
export declare const slack: string[];
export declare const slashdot: string[];
export declare const slickpic: string[];
export declare const slides: string[];
export declare const slideshare: string[];
export declare const smashingmagazine: string[];
export declare const snapchat: string[];
export declare const snapcraft: string[];
export declare const snyk: string[];
export declare const society6: string[];
export declare const socketIo: string[];
export declare const sogou: string[];
export declare const songkick: string[];
export declare const solus: string[];
export declare const sourceforge: string[];
export declare const sourcegraph: string[];
export declare const soundcloud: string[];
export declare const sonos: string[];
export declare const spacemacs: string[];
export declare const spacex: string[];
export declare const sparkfun: string[];
export declare const sparkpost: string[];
export declare const spdx: string[];
export declare const spectrum: string[];
export declare const spotify: string[];
export declare const spreaker: string[];
export declare const speakerDeck: string[];
export declare const spring: string[];
export declare const spotlight: string[];
export declare const sprint: string[];
export declare const stackexchange: string[];
export declare const stackoverflow: string[];
export declare const stackbit: string[];
export declare const squarespace: string[];
export declare const stadia: string[];
export declare const stackshare: string[];
export declare const stackpath: string[];
export declare const statamic: string[];
export declare const staticman: string[];
export declare const statuspage: string[];
export declare const steam: string[];
export declare const steem: string[];
export declare const steemit: string[];
export declare const stitcher: string[];
export declare const storify: string[];
export declare const strapi: string[];
export declare const storybook: string[];
export declare const strava: string[];
export declare const stripe: string[];
export declare const stubhub: string[];
export declare const stripeS: string[];
export declare const stumbleupon: string[];
export declare const styleshare: string[];
export declare const stylus: string[];
export declare const sublimeText: string[];
export declare const subversion: string[];
export declare const superuser: string[];
export declare const svelte: string[];
export declare const svg: string[];
export declare const swagger: string[];
export declare const swarm: string[];
export declare const swift: string[];
export declare const symantec: string[];
export declare const symfony: string[];
export declare const synology: string[];
export declare const tMobile: string[];
export declare const tableau: string[];
export declare const tails: string[];
export declare const tapas: string[];
export declare const teamviewer: string[];
export declare const ted: string[];
export declare const teespring: string[];
export declare const telegramPlane: string[];
export declare const telegram: string[];
export declare const tencentQq: string[];
export declare const tensorflow: string[];
export declare const terraform: string[];
export declare const tencentWeibo: string[];
export declare const tesla: string[];
export declare const theMighty: string[];
export declare const tidal: string[];
export declare const theMovieDatabase: string[];
export declare const tinder: string[];
export declare const tiktok: string[];
export declare const todoist: string[];
export declare const toggl: string[];
export declare const topcoder: string[];
export declare const tor: string[];
export declare const toptal: string[];
export declare const trainerroad: string[];
export declare const toshiba: string[];
export declare const trakt: string[];
export declare const treehouse: string[];
export declare const trello: string[];
export declare const tripadvisor: string[];
export declare const tumblr: string[];
export declare const trulia: string[];
export declare const twilio: string[];
export declare const twitch: string[];
export declare const twitter: string[];
export declare const twoo: string[];
export declare const typescript: string[];
export declare const uber: string[];
export declare const typo3: string[];
export declare const ublockOrigin: string[];
export declare const ubisoft: string[];
export declare const ubuntu: string[];
export declare const udacity: string[];
export declare const udemy: string[];
export declare const uikit: string[];
export declare const unrealEngine: string[];
export declare const unity: string[];
export declare const umbraco: string[];
export declare const unsplash: string[];
export declare const untappd: string[];
export declare const upwork: string[];
export declare const usb: string[];
export declare const v8: string[];
export declare const vagrant: string[];
export declare const verizon: string[];
export declare const venmo: string[];
export declare const viber: string[];
export declare const vim: string[];
export declare const viadeo: string[];
export declare const vimeoV: string[];
export declare const vimeo: string[];
export declare const vine: string[];
export declare const virb: string[];
export declare const visa: string[];
export declare const visualStudioCode: string[];
export declare const visualStudio: string[];
export declare const vk: string[];
export declare const vlc: string[];
export declare const vsco: string[];
export declare const vueJs: string[];
export declare const weasyl: string[];
export declare const wattpad: string[];
export declare const webpack: string[];
export declare const webcomponentsOrg: string[];
export declare const webstorm: string[];
export declare const wechat: string[];
export declare const whatsapp: string[];
export declare const wii: string[];
export declare const whenIWork: string[];
export declare const wikipedia: string[];
export declare const wiiu: string[];
export declare const windows: string[];
export declare const wire: string[];
export declare const wireguard: string[];
export declare const wix: string[];
export declare const wolframLanguage: string[];
export declare const wolframMathematica: string[];
export declare const wolfram: string[];
export declare const wordpress: string[];
export declare const wpengine: string[];
export declare const xPack: string[];
export declare const xbox: string[];
export declare const xcode: string[];
export declare const xero: string[];
export declare const xiaomi: string[];
export declare const xing: string[];
export declare const xrp: string[];
export declare const xsplit: string[];
export declare const yCombinator: string[];
export declare const yahoo: string[];
export declare const yammer: string[];
export declare const yandex: string[];
export declare const yarn: string[];
export declare const yelp: string[];
export declare const youtube: string[];
export declare const zalando: string[];
export declare const zapier: string[];
export declare const zeit: string[];
export declare const zendesk: string[];
export declare const zerply: string[];
export declare const zillow: string[];
export declare const zingat: string[];
export declare const zoom: string[];
export declare const zorin: string[];
export declare const zulip: string[];
export declare const deno: string[];
export declare const epicGames: string[];
export declare const flask: string[];
export declare const gerrit: string[];
export declare const greensock: string[];
export declare const travisci: string[];
export declare const apacheFlink: string[];
export declare const babel: string[];
export declare const codewars: string[];
export declare const gnu: string[];
export declare const composer: string[];
export declare const elsevier: string[];