export declare const flagSet: {
  "cifAD": any[];
  "cifAE": any[];
  "cifAF": any[];
  "cifAG": any[];
  "cifAL": any[];
  "cifAM": any[];
  "cifAO": any[];
  "cifAR": any[];
  "cifAT": any[];
  "cifAU": any[];
  "cifAZ": any[];
  "cifBA": any[];
  "cifBB": any[];
  "cifBD": any[];
  "cifBE": any[];
  "cifBF": any[];
  "cifBG": any[];
  "cifBH": any[];
  "cifBI": any[];
  "cifBJ": any[];
  "cifBN": any[];
  "cifBO": any[];
  "cifBR": any[];
  "cifBS": any[];
  "cifBT": any[];
  "cifBW": any[];
  "cifBY": any[];
  "cifBZ": any[];
  "cifCA": any[];
  "cifCD": any[];
  "cifCF": any[];
  "cifCG": any[];
  "cifCH": any[];
  "cifCI": any[];
  "cifCL": any[];
  "cifCM": any[];
  "cifCN": any[];
  "cifCO": any[];
  "cifCR": any[];
  "cifCU": any[];
  "cifCV": any[];
  "cifCY": any[];
  "cifCZ": any[];
  "cifDE": any[];
  "cifDJ": any[];
  "cifDK": any[];
  "cifDM": any[];
  "cifDO": any[];
  "cifDZ": any[];
  "cifEC": any[];
  "cifEE": any[];
  "cifEG": any[];
  "cifER": any[];
  "cifES": any[];
  "cifET": any[];
  "cifFI": any[];
  "cifFJ": any[];
  "cifFM": any[];
  "cifFR": any[];
  "cifGA": any[];
  "cifGB": any[];
  "cifGD": any[];
  "cifGE": any[];
  "cifGH": any[];
  "cifGM": any[];
  "cifGN": any[];
  "cifGQ": any[];
  "cifGR": any[];
  "cifGT": any[];
  "cifGW": any[];
  "cifGY": any[];
  "cifHK": any[];
  "cifHN": any[];
  "cifHR": any[];
  "cifHT": any[];
  "cifHU": any[];
  "cifID": any[];
  "cifIE": any[];
  "cifIL": any[];
  "cifIN": any[];
  "cifIQ": any[];
  "cifIR": any[];
  "cifIS": any[];
  "cifIT": any[];
  "cifJM": any[];
  "cifJO": any[];
  "cifJP": any[];
  "cifKE": any[];
  "cifKG": any[];
  "cifKH": any[];
  "cifKI": any[];
  "cifKM": any[];
  "cifKN": any[];
  "cifKP": any[];
  "cifKR": any[];
  "cifKW": any[];
  "cifKZ": any[];
  "cifLA": any[];
  "cifLB": any[];
  "cifLC": any[];
  "cifLI": any[];
  "cifLK": any[];
  "cifLR": any[];
  "cifLS": any[];
  "cifLT": any[];
  "cifLU": any[];
  "cifLV": any[];
  "cifLY": any[];
  "cifMA": any[];
  "cifMC": any[];
  "cifMD": any[];
  "cifME": any[];
  "cifMG": any[];
  "cifMH": any[];
  "cifMK": any[];
  "cifML": any[];
  "cifMM": any[];
  "cifMN": any[];
  "cifMR": any[];
  "cifMT": any[];
  "cifMU": any[];
  "cifMV": any[];
  "cifMW": any[];
  "cifMX": any[];
  "cifMY": any[];
  "cifMZ": any[];
  "cifNA": any[];
  "cifNE": any[];
  "cifNG": any[];
  "cifNI": any[];
  "cifNL": any[];
  "cifNO": any[];
  "cifNP": any[];
  "cifNR": any[];
  "cifNU": any[];
  "cifNZ": any[];
  "cifOM": any[];
  "cifPA": any[];
  "cifPE": any[];
  "cifPG": any[];
  "cifPH": any[];
  "cifPK": any[];
  "cifPL": any[];
  "cifPT": any[];
  "cifPW": any[];
  "cifPY": any[];
  "cifQA": any[];
  "cifRO": any[];
  "cifRS": any[];
  "cifRU": any[];
  "cifRW": any[];
  "cifSA": any[];
  "cifSB": any[];
  "cifSC": any[];
  "cifSD": any[];
  "cifSE": any[];
  "cifSG": any[];
  "cifSI": any[];
  "cifSK": any[];
  "cifSL": any[];
  "cifSM": any[];
  "cifSN": any[];
  "cifSO": any[];
  "cifSR": any[];
  "cifSS": any[];
  "cifST": any[];
  "cifSV": any[];
  "cifSY": any[];
  "cifSZ": any[];
  "cifTD": any[];
  "cifTG": any[];
  "cifTH": any[];
  "cifTJ": any[];
  "cifTL": any[];
  "cifTM": any[];
  "cifTN": any[];
  "cifTO": any[];
  "cifTR": any[];
  "cifTT": any[];
  "cifTV": any[];
  "cifTW": any[];
  "cifTZ": any[];
  "cifUA": any[];
  "cifUG": any[];
  "cifUS": any[];
  "cifUY": any[];
  "cifUZ": any[];
  "cifVA": any[];
  "cifVC": any[];
  "cifVE": any[];
  "cifVN": any[];
  "cifWS": any[];
  "cifXK": any[];
  "cifYE": any[];
  "cifZA": any[];
  "cifZM": any[];
  "cifZW": any[];
}
export declare const cifAD: any[];
export declare const cifAE: any[];
export declare const cifAF: any[];
export declare const cifAG: any[];
export declare const cifAL: any[];
export declare const cifAM: any[];
export declare const cifAO: any[];
export declare const cifAR: any[];
export declare const cifAT: any[];
export declare const cifAU: any[];
export declare const cifAZ: any[];
export declare const cifBA: any[];
export declare const cifBB: any[];
export declare const cifBD: any[];
export declare const cifBE: any[];
export declare const cifBF: any[];
export declare const cifBG: any[];
export declare const cifBH: any[];
export declare const cifBI: any[];
export declare const cifBJ: any[];
export declare const cifBN: any[];
export declare const cifBO: any[];
export declare const cifBR: any[];
export declare const cifBS: any[];
export declare const cifBT: any[];
export declare const cifBW: any[];
export declare const cifBY: any[];
export declare const cifBZ: any[];
export declare const cifCA: any[];
export declare const cifCD: any[];
export declare const cifCF: any[];
export declare const cifCG: any[];
export declare const cifCH: any[];
export declare const cifCI: any[];
export declare const cifCL: any[];
export declare const cifCM: any[];
export declare const cifCN: any[];
export declare const cifCO: any[];
export declare const cifCR: any[];
export declare const cifCU: any[];
export declare const cifCV: any[];
export declare const cifCY: any[];
export declare const cifCZ: any[];
export declare const cifDE: any[];
export declare const cifDJ: any[];
export declare const cifDK: any[];
export declare const cifDM: any[];
export declare const cifDO: any[];
export declare const cifDZ: any[];
export declare const cifEC: any[];
export declare const cifEE: any[];
export declare const cifEG: any[];
export declare const cifER: any[];
export declare const cifES: any[];
export declare const cifET: any[];
export declare const cifFI: any[];
export declare const cifFJ: any[];
export declare const cifFM: any[];
export declare const cifFR: any[];
export declare const cifGA: any[];
export declare const cifGB: any[];
export declare const cifGD: any[];
export declare const cifGE: any[];
export declare const cifGH: any[];
export declare const cifGM: any[];
export declare const cifGN: any[];
export declare const cifGQ: any[];
export declare const cifGR: any[];
export declare const cifGT: any[];
export declare const cifGW: any[];
export declare const cifGY: any[];
export declare const cifHK: any[];
export declare const cifHN: any[];
export declare const cifHR: any[];
export declare const cifHT: any[];
export declare const cifHU: any[];
export declare const cifID: any[];
export declare const cifIE: any[];
export declare const cifIL: any[];
export declare const cifIN: any[];
export declare const cifIQ: any[];
export declare const cifIR: any[];
export declare const cifIS: any[];
export declare const cifIT: any[];
export declare const cifJM: any[];
export declare const cifJO: any[];
export declare const cifJP: any[];
export declare const cifKE: any[];
export declare const cifKG: any[];
export declare const cifKH: any[];
export declare const cifKI: any[];
export declare const cifKM: any[];
export declare const cifKN: any[];
export declare const cifKP: any[];
export declare const cifKR: any[];
export declare const cifKW: any[];
export declare const cifKZ: any[];
export declare const cifLA: any[];
export declare const cifLB: any[];
export declare const cifLC: any[];
export declare const cifLI: any[];
export declare const cifLK: any[];
export declare const cifLR: any[];
export declare const cifLS: any[];
export declare const cifLT: any[];
export declare const cifLU: any[];
export declare const cifLV: any[];
export declare const cifLY: any[];
export declare const cifMA: any[];
export declare const cifMC: any[];
export declare const cifMD: any[];
export declare const cifME: any[];
export declare const cifMG: any[];
export declare const cifMH: any[];
export declare const cifMK: any[];
export declare const cifML: any[];
export declare const cifMM: any[];
export declare const cifMN: any[];
export declare const cifMR: any[];
export declare const cifMT: any[];
export declare const cifMU: any[];
export declare const cifMV: any[];
export declare const cifMW: any[];
export declare const cifMX: any[];
export declare const cifMY: any[];
export declare const cifMZ: any[];
export declare const cifNA: any[];
export declare const cifNE: any[];
export declare const cifNG: any[];
export declare const cifNI: any[];
export declare const cifNL: any[];
export declare const cifNO: any[];
export declare const cifNP: any[];
export declare const cifNR: any[];
export declare const cifNU: any[];
export declare const cifNZ: any[];
export declare const cifOM: any[];
export declare const cifPA: any[];
export declare const cifPE: any[];
export declare const cifPG: any[];
export declare const cifPH: any[];
export declare const cifPK: any[];
export declare const cifPL: any[];
export declare const cifPT: any[];
export declare const cifPW: any[];
export declare const cifPY: any[];
export declare const cifQA: any[];
export declare const cifRO: any[];
export declare const cifRS: any[];
export declare const cifRU: any[];
export declare const cifRW: any[];
export declare const cifSA: any[];
export declare const cifSB: any[];
export declare const cifSC: any[];
export declare const cifSD: any[];
export declare const cifSE: any[];
export declare const cifSG: any[];
export declare const cifSI: any[];
export declare const cifSK: any[];
export declare const cifSL: any[];
export declare const cifSM: any[];
export declare const cifSN: any[];
export declare const cifSO: any[];
export declare const cifSR: any[];
export declare const cifSS: any[];
export declare const cifST: any[];
export declare const cifSV: any[];
export declare const cifSY: any[];
export declare const cifSZ: any[];
export declare const cifTD: any[];
export declare const cifTG: any[];
export declare const cifTH: any[];
export declare const cifTJ: any[];
export declare const cifTL: any[];
export declare const cifTM: any[];
export declare const cifTN: any[];
export declare const cifTO: any[];
export declare const cifTR: any[];
export declare const cifTT: any[];
export declare const cifTV: any[];
export declare const cifTW: any[];
export declare const cifTZ: any[];
export declare const cifUA: any[];
export declare const cifUG: any[];
export declare const cifUS: any[];
export declare const cifUY: any[];
export declare const cifUZ: any[];
export declare const cifVA: any[];
export declare const cifVC: any[];
export declare const cifVE: any[];
export declare const cifVN: any[];
export declare const cifWS: any[];
export declare const cifXK: any[];
export declare const cifYE: any[];
export declare const cifZA: any[];
export declare const cifZM: any[];
export declare const cifZW: any[];