export declare const flagSet: {
  "cifAe": string[];
  "cifAg": string[];
  "cifAo": string[];
  "cifAm": string[];
  "cifAu": string[];
  "cifBa": string[];
  "cifAt": string[];
  "cifAz": string[];
  "cifBb": string[];
  "cifBg": string[];
  "cifBd": string[];
  "cifBe": string[];
  "cifBf": string[];
  "cifBj": string[];
  "cifBi": string[];
  "cifBr": string[];
  "cifBo": string[];
  "cifBh": string[];
  "cifBs": string[];
  "cifBw": string[];
  "cifCa": string[];
  "cifCd": string[];
  "cifCg": string[];
  "cifCh": string[];
  "cifCf": string[];
  "cifCl": string[];
  "cifCi": string[];
  "cifCm": string[];
  "cifCn": string[];
  "cifCo": string[];
  "cifCu": string[];
  "cifCv": string[];
  "cifCr": string[];
  "cifDj": string[];
  "cifDk": string[];
  "cifCz": string[];
  "cifDe": string[];
  "cifDz": string[];
  "cifEt": string[];
  "cifEr": string[];
  "cifEe": string[];
  "cifFi": string[];
  "cifFm": string[];
  "cifFr": string[];
  "cifGb": string[];
  "cifGe": string[];
  "cifGd": string[];
  "cifGh": string[];
  "cifGa": string[];
  "cifGm": string[];
  "cifGr": string[];
  "cifGw": string[];
  "cifHn": string[];
  "cifGy": string[];
  "cifHk": string[];
  "cifId": string[];
  "cifIn": string[];
  "cifIe": string[];
  "cifHu": string[];
  "cifIl": string[];
  "cifIs": string[];
  "cifIr": string[];
  "cifIt": string[];
  "cifIq": string[];
  "cifJo": string[];
  "cifJm": string[];
  "cifKe": string[];
  "cifJp": string[];
  "cifKm": string[];
  "cifKp": string[];
  "cifKn": string[];
  "cifKr": string[];
  "cifKw": string[];
  "cifLa": string[];
  "cifLc": string[];
  "cifLr": string[];
  "cifLt": string[];
  "cifLs": string[];
  "cifLy": string[];
  "cifLu": string[];
  "cifLv": string[];
  "cifMa": string[];
  "cifMc": string[];
  "cifMg": string[];
  "cifMh": string[];
  "cifMl": string[];
  "cifMk": string[];
  "cifMr": string[];
  "cifKi": string[];
  "cifMm": string[];
  "cifMn": string[];
  "cifMw": string[];
  "cifMu": string[];
  "cifMv": string[];
  "cifMy": string[];
  "cifMz": string[];
  "cifNa": string[];
  "cifNg": string[];
  "cifNl": string[];
  "cifNo": string[];
  "cifNp": string[];
  "cifNr": string[];
  "cifNz": string[];
  "cifNe": string[];
  "cifNu": string[];
  "cifPa": string[];
  "cifPg": string[];
  "cifPk": string[];
  "cifPl": string[];
  "cifPh": string[];
  "cifPe": string[];
  "cifPw": string[];
  "cifQa": string[];
  "cifRo": string[];
  "cifRw": string[];
  "cifRu": string[];
  "cifSd": string[];
  "cifSc": string[];
  "cifSb": string[];
  "cifSi": string[];
  "cifSe": string[];
  "cifSg": string[];
  "cifSk": string[];
  "cifSl": string[];
  "cifSo": string[];
  "cifSn": string[];
  "cifSr": string[];
  "cifSs": string[];
  "cifSt": string[];
  "cifSy": string[];
  "cifTd": string[];
  "cifSz": string[];
  "cifTg": string[];
  "cifTh": string[];
  "cifTj": string[];
  "cifTl": string[];
  "cifTn": string[];
  "cifTo": string[];
  "cifTr": string[];
  "cifTt": string[];
  "cifTv": string[];
  "cifTz": string[];
  "cifUa": string[];
  "cifUg": string[];
  "cifUs": string[];
  "cifUy": string[];
  "cifUz": string[];
  "cifTw": string[];
  "cifVc": string[];
  "cifVe": string[];
  "cifYe": string[];
  "cifXk": string[];
  "cifWs": string[];
  "cifVn": string[];
  "cifZa": string[];
  "cifZw": string[];
  "cifZm": string[];
  "cifAr": string[];
  "cifAl": string[];
  "cifBy": string[];
  "cifCy": string[];
  "cifDm": string[];
  "cifGn": string[];
  "cifGq": string[];
  "cifKg": string[];
  "cifLb": string[];
  "cifMt": string[];
  "cifKh": string[];
  "cifLi": string[];
  "cifNi": string[];
  "cifOm": string[];
  "cifSa": string[];
  "cifBn": string[];
  "cifEg": string[];
  "cifKz": string[];
  "cifLk": string[];
  "cifMd": string[];
  "cifBt": string[];
  "cifHt": string[];
  "cifPy": string[];
  "cifPt": string[];
  "cifAf": string[];
  "cifTm": string[];
  "cifAd": string[];
  "cifVa": string[];
  "cifMe": string[];
  "cifBz": string[];
  "cifGt": string[];
  "cifFj": string[];
  "cifHr": string[];
  "cifEs": string[];
  "cifSm": string[];
  "cifDo": string[];
  "cifSv": string[];
  "cifMx": string[];
  "cifEc": string[];
  "cifRs": string[];
}
export declare const cifAe: string[];
export declare const cifAg: string[];
export declare const cifAo: string[];
export declare const cifAm: string[];
export declare const cifAu: string[];
export declare const cifBa: string[];
export declare const cifAt: string[];
export declare const cifAz: string[];
export declare const cifBb: string[];
export declare const cifBg: string[];
export declare const cifBd: string[];
export declare const cifBe: string[];
export declare const cifBf: string[];
export declare const cifBj: string[];
export declare const cifBi: string[];
export declare const cifBr: string[];
export declare const cifBo: string[];
export declare const cifBh: string[];
export declare const cifBs: string[];
export declare const cifBw: string[];
export declare const cifCa: string[];
export declare const cifCd: string[];
export declare const cifCg: string[];
export declare const cifCh: string[];
export declare const cifCf: string[];
export declare const cifCl: string[];
export declare const cifCi: string[];
export declare const cifCm: string[];
export declare const cifCn: string[];
export declare const cifCo: string[];
export declare const cifCu: string[];
export declare const cifCv: string[];
export declare const cifCr: string[];
export declare const cifDj: string[];
export declare const cifDk: string[];
export declare const cifCz: string[];
export declare const cifDe: string[];
export declare const cifDz: string[];
export declare const cifEt: string[];
export declare const cifEr: string[];
export declare const cifEe: string[];
export declare const cifFi: string[];
export declare const cifFm: string[];
export declare const cifFr: string[];
export declare const cifGb: string[];
export declare const cifGe: string[];
export declare const cifGd: string[];
export declare const cifGh: string[];
export declare const cifGa: string[];
export declare const cifGm: string[];
export declare const cifGr: string[];
export declare const cifGw: string[];
export declare const cifHn: string[];
export declare const cifGy: string[];
export declare const cifHk: string[];
export declare const cifId: string[];
export declare const cifIn: string[];
export declare const cifIe: string[];
export declare const cifHu: string[];
export declare const cifIl: string[];
export declare const cifIs: string[];
export declare const cifIr: string[];
export declare const cifIt: string[];
export declare const cifIq: string[];
export declare const cifJo: string[];
export declare const cifJm: string[];
export declare const cifKe: string[];
export declare const cifJp: string[];
export declare const cifKm: string[];
export declare const cifKp: string[];
export declare const cifKn: string[];
export declare const cifKr: string[];
export declare const cifKw: string[];
export declare const cifLa: string[];
export declare const cifLc: string[];
export declare const cifLr: string[];
export declare const cifLt: string[];
export declare const cifLs: string[];
export declare const cifLy: string[];
export declare const cifLu: string[];
export declare const cifLv: string[];
export declare const cifMa: string[];
export declare const cifMc: string[];
export declare const cifMg: string[];
export declare const cifMh: string[];
export declare const cifMl: string[];
export declare const cifMk: string[];
export declare const cifMr: string[];
export declare const cifKi: string[];
export declare const cifMm: string[];
export declare const cifMn: string[];
export declare const cifMw: string[];
export declare const cifMu: string[];
export declare const cifMv: string[];
export declare const cifMy: string[];
export declare const cifMz: string[];
export declare const cifNa: string[];
export declare const cifNg: string[];
export declare const cifNl: string[];
export declare const cifNo: string[];
export declare const cifNp: string[];
export declare const cifNr: string[];
export declare const cifNz: string[];
export declare const cifNe: string[];
export declare const cifNu: string[];
export declare const cifPa: string[];
export declare const cifPg: string[];
export declare const cifPk: string[];
export declare const cifPl: string[];
export declare const cifPh: string[];
export declare const cifPe: string[];
export declare const cifPw: string[];
export declare const cifQa: string[];
export declare const cifRo: string[];
export declare const cifRw: string[];
export declare const cifRu: string[];
export declare const cifSd: string[];
export declare const cifSc: string[];
export declare const cifSb: string[];
export declare const cifSi: string[];
export declare const cifSe: string[];
export declare const cifSg: string[];
export declare const cifSk: string[];
export declare const cifSl: string[];
export declare const cifSo: string[];
export declare const cifSn: string[];
export declare const cifSr: string[];
export declare const cifSs: string[];
export declare const cifSt: string[];
export declare const cifSy: string[];
export declare const cifTd: string[];
export declare const cifSz: string[];
export declare const cifTg: string[];
export declare const cifTh: string[];
export declare const cifTj: string[];
export declare const cifTl: string[];
export declare const cifTn: string[];
export declare const cifTo: string[];
export declare const cifTr: string[];
export declare const cifTt: string[];
export declare const cifTv: string[];
export declare const cifTz: string[];
export declare const cifUa: string[];
export declare const cifUg: string[];
export declare const cifUs: string[];
export declare const cifUy: string[];
export declare const cifUz: string[];
export declare const cifTw: string[];
export declare const cifVc: string[];
export declare const cifVe: string[];
export declare const cifYe: string[];
export declare const cifXk: string[];
export declare const cifWs: string[];
export declare const cifVn: string[];
export declare const cifZa: string[];
export declare const cifZw: string[];
export declare const cifZm: string[];
export declare const cifAr: string[];
export declare const cifAl: string[];
export declare const cifBy: string[];
export declare const cifCy: string[];
export declare const cifDm: string[];
export declare const cifGn: string[];
export declare const cifGq: string[];
export declare const cifKg: string[];
export declare const cifLb: string[];
export declare const cifMt: string[];
export declare const cifKh: string[];
export declare const cifLi: string[];
export declare const cifNi: string[];
export declare const cifOm: string[];
export declare const cifSa: string[];
export declare const cifBn: string[];
export declare const cifEg: string[];
export declare const cifKz: string[];
export declare const cifLk: string[];
export declare const cifMd: string[];
export declare const cifBt: string[];
export declare const cifHt: string[];
export declare const cifPy: string[];
export declare const cifPt: string[];
export declare const cifAf: string[];
export declare const cifTm: string[];
export declare const cifAd: string[];
export declare const cifVa: string[];
export declare const cifMe: string[];
export declare const cifBz: string[];
export declare const cifGt: string[];
export declare const cifFj: string[];
export declare const cifHr: string[];
export declare const cifEs: string[];
export declare const cifSm: string[];
export declare const cifDo: string[];
export declare const cifSv: string[];
export declare const cifMx: string[];
export declare const cifEc: string[];
export declare const cifRs: string[];