export declare const flagSet: {
  "cifAd": any[];
  "cifAe": any[];
  "cifAf": any[];
  "cifAg": any[];
  "cifAl": any[];
  "cifAm": any[];
  "cifAo": any[];
  "cifAr": any[];
  "cifAt": any[];
  "cifAu": any[];
  "cifAz": any[];
  "cifBa": any[];
  "cifBb": any[];
  "cifBd": any[];
  "cifBe": any[];
  "cifBf": any[];
  "cifBg": any[];
  "cifBh": any[];
  "cifBi": any[];
  "cifBj": any[];
  "cifBn": any[];
  "cifBo": any[];
  "cifBr": any[];
  "cifBs": any[];
  "cifBt": any[];
  "cifBw": any[];
  "cifBy": any[];
  "cifBz": any[];
  "cifCa": any[];
  "cifCd": any[];
  "cifCf": any[];
  "cifCg": any[];
  "cifCh": any[];
  "cifCi": any[];
  "cifCl": any[];
  "cifCm": any[];
  "cifCn": any[];
  "cifCo": any[];
  "cifCr": any[];
  "cifCu": any[];
  "cifCv": any[];
  "cifCy": any[];
  "cifCz": any[];
  "cifDe": any[];
  "cifDj": any[];
  "cifDk": any[];
  "cifDm": any[];
  "cifDo": any[];
  "cifDz": any[];
  "cifEc": any[];
  "cifEe": any[];
  "cifEg": any[];
  "cifEr": any[];
  "cifEs": any[];
  "cifEt": any[];
  "cifFi": any[];
  "cifFj": any[];
  "cifFm": any[];
  "cifFr": any[];
  "cifGa": any[];
  "cifGb": any[];
  "cifGd": any[];
  "cifGe": any[];
  "cifGh": any[];
  "cifGm": any[];
  "cifGn": any[];
  "cifGq": any[];
  "cifGr": any[];
  "cifGt": any[];
  "cifGw": any[];
  "cifGy": any[];
  "cifHk": any[];
  "cifHn": any[];
  "cifHr": any[];
  "cifHt": any[];
  "cifHu": any[];
  "cifId": any[];
  "cifIe": any[];
  "cifIl": any[];
  "cifIn": any[];
  "cifIq": any[];
  "cifIr": any[];
  "cifIs": any[];
  "cifIt": any[];
  "cifJm": any[];
  "cifJo": any[];
  "cifJp": any[];
  "cifKe": any[];
  "cifKg": any[];
  "cifKh": any[];
  "cifKi": any[];
  "cifKm": any[];
  "cifKn": any[];
  "cifKp": any[];
  "cifKr": any[];
  "cifKw": any[];
  "cifKz": any[];
  "cifLa": any[];
  "cifLb": any[];
  "cifLc": any[];
  "cifLi": any[];
  "cifLk": any[];
  "cifLr": any[];
  "cifLs": any[];
  "cifLt": any[];
  "cifLu": any[];
  "cifLv": any[];
  "cifLy": any[];
  "cifMa": any[];
  "cifMc": any[];
  "cifMd": any[];
  "cifMe": any[];
  "cifMg": any[];
  "cifMh": any[];
  "cifMk": any[];
  "cifMl": any[];
  "cifMm": any[];
  "cifMn": any[];
  "cifMr": any[];
  "cifMt": any[];
  "cifMu": any[];
  "cifMv": any[];
  "cifMw": any[];
  "cifMx": any[];
  "cifMy": any[];
  "cifMz": any[];
  "cifNa": any[];
  "cifNe": any[];
  "cifNg": any[];
  "cifNi": any[];
  "cifNl": any[];
  "cifNo": any[];
  "cifNp": any[];
  "cifNr": any[];
  "cifNu": any[];
  "cifNz": any[];
  "cifOm": any[];
  "cifPa": any[];
  "cifPe": any[];
  "cifPg": any[];
  "cifPh": any[];
  "cifPk": any[];
  "cifPl": any[];
  "cifPt": any[];
  "cifPw": any[];
  "cifPy": any[];
  "cifQa": any[];
  "cifRo": any[];
  "cifRs": any[];
  "cifRu": any[];
  "cifRw": any[];
  "cifSa": any[];
  "cifSb": any[];
  "cifSc": any[];
  "cifSd": any[];
  "cifSe": any[];
  "cifSg": any[];
  "cifSi": any[];
  "cifSk": any[];
  "cifSl": any[];
  "cifSm": any[];
  "cifSn": any[];
  "cifSo": any[];
  "cifSr": any[];
  "cifSs": any[];
  "cifSt": any[];
  "cifSv": any[];
  "cifSy": any[];
  "cifSz": any[];
  "cifTd": any[];
  "cifTg": any[];
  "cifTh": any[];
  "cifTj": any[];
  "cifTl": any[];
  "cifTm": any[];
  "cifTn": any[];
  "cifTo": any[];
  "cifTr": any[];
  "cifTt": any[];
  "cifTv": any[];
  "cifTw": any[];
  "cifTz": any[];
  "cifUa": any[];
  "cifUg": any[];
  "cifUs": any[];
  "cifUy": any[];
  "cifUz": any[];
  "cifVa": any[];
  "cifVc": any[];
  "cifVe": any[];
  "cifVn": any[];
  "cifWs": any[];
  "cifXk": any[];
  "cifYe": any[];
  "cifZa": any[];
  "cifZm": any[];
  "cifZw": any[];
}
export declare const cifAd: any[];
export declare const cifAe: any[];
export declare const cifAf: any[];
export declare const cifAg: any[];
export declare const cifAl: any[];
export declare const cifAm: any[];
export declare const cifAo: any[];
export declare const cifAr: any[];
export declare const cifAt: any[];
export declare const cifAu: any[];
export declare const cifAz: any[];
export declare const cifBa: any[];
export declare const cifBb: any[];
export declare const cifBd: any[];
export declare const cifBe: any[];
export declare const cifBf: any[];
export declare const cifBg: any[];
export declare const cifBh: any[];
export declare const cifBi: any[];
export declare const cifBj: any[];
export declare const cifBn: any[];
export declare const cifBo: any[];
export declare const cifBr: any[];
export declare const cifBs: any[];
export declare const cifBt: any[];
export declare const cifBw: any[];
export declare const cifBy: any[];
export declare const cifBz: any[];
export declare const cifCa: any[];
export declare const cifCd: any[];
export declare const cifCf: any[];
export declare const cifCg: any[];
export declare const cifCh: any[];
export declare const cifCi: any[];
export declare const cifCl: any[];
export declare const cifCm: any[];
export declare const cifCn: any[];
export declare const cifCo: any[];
export declare const cifCr: any[];
export declare const cifCu: any[];
export declare const cifCv: any[];
export declare const cifCy: any[];
export declare const cifCz: any[];
export declare const cifDe: any[];
export declare const cifDj: any[];
export declare const cifDk: any[];
export declare const cifDm: any[];
export declare const cifDo: any[];
export declare const cifDz: any[];
export declare const cifEc: any[];
export declare const cifEe: any[];
export declare const cifEg: any[];
export declare const cifEr: any[];
export declare const cifEs: any[];
export declare const cifEt: any[];
export declare const cifFi: any[];
export declare const cifFj: any[];
export declare const cifFm: any[];
export declare const cifFr: any[];
export declare const cifGa: any[];
export declare const cifGb: any[];
export declare const cifGd: any[];
export declare const cifGe: any[];
export declare const cifGh: any[];
export declare const cifGm: any[];
export declare const cifGn: any[];
export declare const cifGq: any[];
export declare const cifGr: any[];
export declare const cifGt: any[];
export declare const cifGw: any[];
export declare const cifGy: any[];
export declare const cifHk: any[];
export declare const cifHn: any[];
export declare const cifHr: any[];
export declare const cifHt: any[];
export declare const cifHu: any[];
export declare const cifId: any[];
export declare const cifIe: any[];
export declare const cifIl: any[];
export declare const cifIn: any[];
export declare const cifIq: any[];
export declare const cifIr: any[];
export declare const cifIs: any[];
export declare const cifIt: any[];
export declare const cifJm: any[];
export declare const cifJo: any[];
export declare const cifJp: any[];
export declare const cifKe: any[];
export declare const cifKg: any[];
export declare const cifKh: any[];
export declare const cifKi: any[];
export declare const cifKm: any[];
export declare const cifKn: any[];
export declare const cifKp: any[];
export declare const cifKr: any[];
export declare const cifKw: any[];
export declare const cifKz: any[];
export declare const cifLa: any[];
export declare const cifLb: any[];
export declare const cifLc: any[];
export declare const cifLi: any[];
export declare const cifLk: any[];
export declare const cifLr: any[];
export declare const cifLs: any[];
export declare const cifLt: any[];
export declare const cifLu: any[];
export declare const cifLv: any[];
export declare const cifLy: any[];
export declare const cifMa: any[];
export declare const cifMc: any[];
export declare const cifMd: any[];
export declare const cifMe: any[];
export declare const cifMg: any[];
export declare const cifMh: any[];
export declare const cifMk: any[];
export declare const cifMl: any[];
export declare const cifMm: any[];
export declare const cifMn: any[];
export declare const cifMr: any[];
export declare const cifMt: any[];
export declare const cifMu: any[];
export declare const cifMv: any[];
export declare const cifMw: any[];
export declare const cifMx: any[];
export declare const cifMy: any[];
export declare const cifMz: any[];
export declare const cifNa: any[];
export declare const cifNe: any[];
export declare const cifNg: any[];
export declare const cifNi: any[];
export declare const cifNl: any[];
export declare const cifNo: any[];
export declare const cifNp: any[];
export declare const cifNr: any[];
export declare const cifNu: any[];
export declare const cifNz: any[];
export declare const cifOm: any[];
export declare const cifPa: any[];
export declare const cifPe: any[];
export declare const cifPg: any[];
export declare const cifPh: any[];
export declare const cifPk: any[];
export declare const cifPl: any[];
export declare const cifPt: any[];
export declare const cifPw: any[];
export declare const cifPy: any[];
export declare const cifQa: any[];
export declare const cifRo: any[];
export declare const cifRs: any[];
export declare const cifRu: any[];
export declare const cifRw: any[];
export declare const cifSa: any[];
export declare const cifSb: any[];
export declare const cifSc: any[];
export declare const cifSd: any[];
export declare const cifSe: any[];
export declare const cifSg: any[];
export declare const cifSi: any[];
export declare const cifSk: any[];
export declare const cifSl: any[];
export declare const cifSm: any[];
export declare const cifSn: any[];
export declare const cifSo: any[];
export declare const cifSr: any[];
export declare const cifSs: any[];
export declare const cifSt: any[];
export declare const cifSv: any[];
export declare const cifSy: any[];
export declare const cifSz: any[];
export declare const cifTd: any[];
export declare const cifTg: any[];
export declare const cifTh: any[];
export declare const cifTj: any[];
export declare const cifTl: any[];
export declare const cifTm: any[];
export declare const cifTn: any[];
export declare const cifTo: any[];
export declare const cifTr: any[];
export declare const cifTt: any[];
export declare const cifTv: any[];
export declare const cifTw: any[];
export declare const cifTz: any[];
export declare const cifUa: any[];
export declare const cifUg: any[];
export declare const cifUs: any[];
export declare const cifUy: any[];
export declare const cifUz: any[];
export declare const cifVa: any[];
export declare const cifVc: any[];
export declare const cifVe: any[];
export declare const cifVn: any[];
export declare const cifWs: any[];
export declare const cifXk: any[];
export declare const cifYe: any[];
export declare const cifZa: any[];
export declare const cifZm: any[];
export declare const cifZw: any[];