export declare const freeSet: {
  "cil4k": string[];
  "cilActionUndo": string[];
  "cilAccountLogout": string[];
  "cilActionRedo": string[];
  "cilAirplaneModeOff": string[];
  "cilAddressBook": string[];
  "cilAlarm": string[];
  "cilAirplaneMode": string[];
  "cilAlbum": string[];
  "cilAirplay": string[];
  "cilAlignCenter": string[];
  "cilAmericanFootball": string[];
  "cilAlignLeft": string[];
  "cilAlignRight": string[];
  "cilAperture": string[];
  "cil3d": string[];
  "cilApple": string[];
  "cilApplicationsSettings": string[];
  "cilArrowBottom": string[];
  "cilArrowCircleBottom": string[];
  "cilArrowCircleRight": string[];
  "cilApplications": string[];
  "cilArrowCircleTop": string[];
  "cilArrowCircleLeft": string[];
  "cilArrowRight": string[];
  "cilArrowThickBottom": string[];
  "cilArrowLeft": string[];
  "cilArrowThickFromLeft": string[];
  "cilArrowThickFromBottom": string[];
  "cilArrowThickFromRight": string[];
  "cilArrowThickFromTop": string[];
  "cilArrowThickLeft": string[];
  "cilArrowThickRight": string[];
  "cilArrowThickToBottom": string[];
  "cilArrowThickToLeft": string[];
  "cilArrowThickToRight": string[];
  "cilArrowThickToTop": string[];
  "cilArrowThickTop": string[];
  "cilArrowTop": string[];
  "cilAsteriskCircle": string[];
  "cilAt": string[];
  "cilAudioDescription": string[];
  "cilAssistiveListeningSystem": string[];
  "cilAudioSpectrum": string[];
  "cilBadge": string[];
  "cilAudio": string[];
  "cilAvTimer": string[];
  "cilAsterisk": string[];
  "cilBalanceScale": string[];
  "cilBarChart": string[];
  "cilBan": string[];
  "cilBank": string[];
  "cilBarcode": string[];
  "cilBasket": string[];
  "cilBaseball": string[];
  "cilBasketball": string[];
  "cilBattery0": string[];
  "cilBattery3": string[];
  "cilBatteryAlert": string[];
  "cilBattery5": string[];
  "cilBatterySlash": string[];
  "cilBed": string[];
  "cilBeaker": string[];
  "cilBeachAccess": string[];
  "cilBath": string[];
  "cilBell": string[];
  "cilBirthdayCake": string[];
  "cilBlind": string[];
  "cilBike": string[];
  "cilBluetooth": string[];
  "cilBlurCircular": string[];
  "cilBoatAlt": string[];
  "cilBold": string[];
  "cilBlurLinear": string[];
  "cilBook": string[];
  "cilBolt": string[];
  "cilBlur": string[];
  "cilBookmark": string[];
  "cilBorderBottom": string[];
  "cilBorderClear": string[];
  "cilBorderHorizontal": string[];
  "cilBorderInner": string[];
  "cilBorderAll": string[];
  "cilBorderLeft": string[];
  "cilBorderRight": string[];
  "cilBorderOuter": string[];
  "cilBorderStyle": string[];
  "cilBorderTop": string[];
  "cilBorderVertical": string[];
  "cilBowling": string[];
  "cilBritishPound": string[];
  "cilBrightness": string[];
  "cilBraille": string[];
  "cilBriefcase": string[];
  "cilBrowser": string[];
  "cilBrush": string[];
  "cilBug": string[];
  "cilBuilding": string[];
  "cilBullhorn": string[];
  "cilBurger": string[];
  "cilBusAlt": string[];
  "cilBrushAlt": string[];
  "cilCalculator": string[];
  "cilCameraRoll": string[];
  "cilCalendarCheck": string[];
  "cilCalendar": string[];
  "cilCarAlt": string[];
  "cilCamera": string[];
  "cilCameraControl": string[];
  "cilCaretLeft": string[];
  "cilCaretBottom": string[];
  "cilCaretTop": string[];
  "cilCart": string[];
  "cilCaretRight": string[];
  "cilCast": string[];
  "cilCenterFocus": string[];
  "cilCasino": string[];
  "cilCat": string[];
  "cilChart": string[];
  "cilChartLine": string[];
  "cilCheckAlt": string[];
  "cilChatBubble": string[];
  "cilChartPie": string[];
  "cilCheckCircle": string[];
  "cilCheck": string[];
  "cilChevronBottom": string[];
  "cilChevronCircleLeftAlt": string[];
  "cilChevronCircleDownAlt": string[];
  "cilChevronCircleRightAlt": string[];
  "cilChevronDoubleLeft": string[];
  "cilChevronCircleUpAlt": string[];
  "cilChevronDoubleUp": string[];
  "cilChevronDoubleRight": string[];
  "cilChevronDoubleUpAlt": string[];
  "cilChevronTop": string[];
  "cilChevronLeft": string[];
  "cilChevronRight": string[];
  "cilChildFriendly": string[];
  "cilChevronDoubleDown": string[];
  "cilChild": string[];
  "cilClipboard": string[];
  "cilClearAll": string[];
  "cilClone": string[];
  "cilClock": string[];
  "cilCloudUpload": string[];
  "cilCloud": string[];
  "cilClosedCaptioning": string[];
  "cilCloudy": string[];
  "cilCode": string[];
  "cilCoffee": string[];
  "cilColorBorder": string[];
  "cilCloudDownload": string[];
  "cilColorFill": string[];
  "cilColorPalette": string[];
  "cilCircle": string[];
  "cilColumns": string[];
  "cilCommentSquare": string[];
  "cilCommentBubble": string[];
  "cilCompass": string[];
  "cilContact": string[];
  "cilContrast": string[];
  "cilCompress": string[];
  "cilCopy": string[];
  "cilCouch": string[];
  "cilCropRotate": string[];
  "cilCreditCard": string[];
  "cilCrop": string[];
  "cilCut": string[];
  "cilCursor": string[];
  "cilDataTransferDown": string[];
  "cilDeaf": string[];
  "cilDescription": string[];
  "cilDevices": string[];
  "cilDataTransferUp": string[];
  "cilDialpad": string[];
  "cilCursorMove": string[];
  "cilDog": string[];
  "cilDinner": string[];
  "cilDollar": string[];
  "cilDoubleQuoteSansRight": string[];
  "cilDrinkAlcohol": string[];
  "cilDoor": string[];
  "cilDrop": string[];
  "cilDrink": string[];
  "cilDoubleQuoteSansLeft": string[];
  "cilElevator": string[];
  "cilEnvelopeClosed": string[];
  "cilEnvelopeOpen": string[];
  "cilEthernet": string[];
  "cilEnvelopeLetter": string[];
  "cilEuro": string[];
  "cilExcerpt": string[];
  "cilExitToApp": string[];
  "cilExpandLeft": string[];
  "cilExpandDown": string[];
  "cilExpandRight": string[];
  "cilExpandUp": string[];
  "cilExposure": string[];
  "cilDrop1": string[];
  "cilExternalLink": string[];
  "cilEyedropper": string[];
  "cilFaceDead": string[];
  "cilFastfood": string[];
  "cilFace": string[];
  "cilEqualizer": string[];
  "cilFax": string[];
  "cilFeaturedPlaylist": string[];
  "cilFile": string[];
  "cilFilterPhoto": string[];
  "cilFilter": string[];
  "cilFingerprint": string[];
  "cilFilterFrames": string[];
  "cilFlagAlt": string[];
  "cilFindInPage": string[];
  "cilFlightTakeoff": string[];
  "cilFlip": string[];
  "cilFlipToBack": string[];
  "cilFolderOpen": string[];
  "cilFlower": string[];
  "cilFire": string[];
  "cilFolder": string[];
  "cilFont": string[];
  "cilFootball": string[];
  "cilFrown": string[];
  "cilFlipToFront": string[];
  "cilFork": string[];
  "cilFullscreenExit": string[];
  "cilFridge": string[];
  "cilFullscreen": string[];
  "cilFunctionsAlt": string[];
  "cilFunctions": string[];
  "cilGarage": string[];
  "cilGamepad": string[];
  "cilGem": string[];
  "cilGif": string[];
  "cilGift": string[];
  "cilGlobeAlt": string[];
  "cilGolfAlt": string[];
  "cilGolf": string[];
  "cilGradient": string[];
  "cilGrain": string[];
  "cilGraph": string[];
  "cilGridSlash": string[];
  "cilGrid": string[];
  "cilHandPointUp": string[];
  "cilHandPointLeft": string[];
  "cilHd": string[];
  "cilHdr": string[];
  "cilHandPointDown": string[];
  "cilHandPointRight": string[];
  "cilHeader": string[];
  "cilHeadphones": string[];
  "cilHighligt": string[];
  "cilHeart": string[];
  "cilHighlighter": string[];
  "cilHospital": string[];
  "cilHotTub": string[];
  "cilHistory": string[];
  "cilHome": string[];
  "cilHealing": string[];
  "cilHouse": string[];
  "cilHttps": string[];
  "cilImageBroken": string[];
  "cilImage1": string[];
  "cilImagePlus": string[];
  "cilInbox": string[];
  "cilIndentDecrease": string[];
  "cilIndustrySlash": string[];
  "cilInfinity": string[];
  "cilIndustry": string[];
  "cilInfo": string[];
  "cilInputHdmi": string[];
  "cilInstitution": string[];
  "cilInput": string[];
  "cilInputPower": string[];
  "cilJustifyCenter": string[];
  "cilItalic": string[];
  "cilJustifyLeft": string[];
  "cilJustifyRight": string[];
  "cilKeyboard": string[];
  "cilLan": string[];
  "cilLanguage": string[];
  "cilLaptop": string[];
  "cilIndentIncrease": string[];
  "cilLayers": string[];
  "cilLeaf": string[];
  "cilLemon": string[];
  "cilLevelUp": string[];
  "cilLevelDown": string[];
  "cilLibraryAdd": string[];
  "cilLibrary": string[];
  "cilLifeRing": string[];
  "cilLightbulb": string[];
  "cilLineSpacing": string[];
  "cilLineStyle": string[];
  "cilLineWeight": string[];
  "cilLink": string[];
  "cilListHighPriority": string[];
  "cilListFilter": string[];
  "cilLinkAlt": string[];
  "cilListLowPriority": string[];
  "cilLinkBroken": string[];
  "cilListRich": string[];
  "cilListNumbered": string[];
  "cilLocationPin": string[];
  "cilList": string[];
  "cilLockLocked": string[];
  "cilLocomotive": string[];
  "cilLockUnlocked": string[];
  "cilLoopCircular": string[];
  "cilLoop1": string[];
  "cilLowVision": string[];
  "cilLoop": string[];
  "cilMagnifyingGlass": string[];
  "cilMap": string[];
  "cilMediaEject": string[];
  "cilMediaPause": string[];
  "cilMediaPlay": string[];
  "cilMediaSkipBackward": string[];
  "cilMediaRecord": string[];
  "cilMediaSkipForward": string[];
  "cilMediaStepBackward": string[];
  "cilMediaStepForward": string[];
  "cilMediaStop": string[];
  "cilMeh": string[];
  "cilMedicalCross": string[];
  "cilMemory": string[];
  "cilMinus": string[];
  "cilMenu": string[];
  "cilMicrophone": string[];
  "cilMobileLandscape": string[];
  "cilMonitor": string[];
  "cilMoney": string[];
  "cilMobile": string[];
  "cilMoodBad": string[];
  "cilMoodGood": string[];
  "cilMoodVeryBad": string[];
  "cilMoodVeryGood": string[];
  "cilMoon": string[];
  "cilMouthSlash": string[];
  "cilMouse": string[];
  "cilMovie": string[];
  "cilMove": string[];
  "cilMug": string[];
  "cilMugTea": string[];
  "cilObjectGroup": string[];
  "cilMusicNote": string[];
  "cilNewspaper": string[];
  "cilNotes": string[];
  "cilOptionsHorizontal": string[];
  "cilObjectUngroup": string[];
  "cilOptions": string[];
  "cilOpacity": string[];
  "cilPaintBucket": string[];
  "cilPaint": string[];
  "cilPaperPlane": string[];
  "cilPaperclip": string[];
  "cilPaw": string[];
  "cilPenNib": string[];
  "cilPencil": string[];
  "cilPenAlt": string[];
  "cilParagraph": string[];
  "cilPin": string[];
  "cilPhone": string[];
  "cilPizza": string[];
  "cilPlaylistAdd": string[];
  "cilPeople": string[];
  "cilPlus": string[];
  "cilPowerStandby": string[];
  "cilPool": string[];
  "cilPregnant": string[];
  "cilPuzzle": string[];
  "cilPrint": string[];
  "cilQrCode": string[];
  "cilRectangle": string[];
  "cilReload": string[];
  "cilRain": string[];
  "cilRemove": string[];
  "cilResizeBoth": string[];
  "cilResizeHeight": string[];
  "cilResizeWidth": string[];
  "cilRestaurant": string[];
  "cilRoom": string[];
  "cilRowing": string[];
  "cilRunning": string[];
  "cilRss": string[];
  "cilSatelite": string[];
  "cilSchool": string[];
  "cilSave": string[];
  "cilScreenDesktop": string[];
  "cilScreenSmartphone": string[];
  "cilScrubber": string[];
  "cilShareAll": string[];
  "cilSettings": string[];
  "cilShareBoxed": string[];
  "cilShare": string[];
  "cilShareAlt": string[];
  "cilShieldAlt": string[];
  "cilShortText": string[];
  "cilSignLanguage": string[];
  "cilShower": string[];
  "cilSignalCellular0": string[];
  "cilSignalCellular3": string[];
  "cilSignalCellular4": string[];
  "cilSim": string[];
  "cilSmilePlus": string[];
  "cilSmile": string[];
  "cilSitemap": string[];
  "cilSmokeFree": string[];
  "cilSmokingRoom": string[];
  "cilSnowflake": string[];
  "cilSortAlphaDown": string[];
  "cilSortAlphaUp": string[];
  "cilSortAscending": string[];
  "cilSortNumericDown": string[];
  "cilSortNumericUp": string[];
  "cilSortDescending": string[];
  "cilSpa": string[];
  "cilSpeaker": string[];
  "cilSpeech": string[];
  "cilSpaceBar": string[];
  "cilSpeedometer": string[];
  "cilSpreadsheet": string[];
  "cilStarHalf": string[];
  "cilStar": string[];
  "cilStream": string[];
  "cilStorage": string[];
  "cilSun": string[];
  "cilSquare": string[];
  "cilSwapHorizontal": string[];
  "cilSwapVertical": string[];
  "cilSwimming": string[];
  "cilTablet": string[];
  "cilSync": string[];
  "cilTag": string[];
  "cilTags": string[];
  "cilTask": string[];
  "cilTaxi": string[];
  "cilTennisBall": string[];
  "cilTennis": string[];
  "cilTerminal": string[];
  "cilTextShapes": string[];
  "cilTerrain": string[];
  "cilTextSize": string[];
  "cilTextSquare": string[];
  "cilTextStrike": string[];
  "cilText": string[];
  "cilThumbDown": string[];
  "cilThumbUp": string[];
  "cilToggleOff": string[];
  "cilToilet": string[];
  "cilTouchApp": string[];
  "cilTransfer": string[];
  "cilTranslate": string[];
  "cilTrash": string[];
  "cilTriangle": string[];
  "cilTruck": string[];
  "cilTv": string[];
  "cilUserFemale": string[];
  "cilUnderline": string[];
  "cilUserFollow": string[];
  "cilUser": string[];
  "cilUserUnfollow": string[];
  "cilVector": string[];
  "cilVerticalAlignBottom1": string[];
  "cilVerticalAlignBottom": string[];
  "cilVerticalAlignCenter": string[];
  "cilVerticalAlignCenter1": string[];
  "cilVerticalAlignTop1": string[];
  "cilVideo": string[];
  "cilViewColumn": string[];
  "cilVerticalAlignTop": string[];
  "cilViewModule": string[];
  "cilViewStream": string[];
  "cilViewQuilt": string[];
  "cilVolumeHigh": string[];
  "cilVoiceOverRecord": string[];
  "cilWalk": string[];
  "cilVolumeLow": string[];
  "cilVolumeOff": string[];
  "cilWallet": string[];
  "cilWallpaper": string[];
  "cilWarning": string[];
  "cilWatch": string[];
  "cilWc": string[];
  "cilWeightlifitng": string[];
  "cilWheelchair": string[];
  "cilWifiSignal0": string[];
  "cilWifiSignal1": string[];
  "cilWifiSignalOff": string[];
  "cilWifiSignal4": string[];
  "cilWindowMaximize": string[];
  "cilWindowMinimize": string[];
  "cilWifiSignal2": string[];
  "cilWindow": string[];
  "cilWindowRestore": string[];
  "cilXCircle": string[];
  "cilWrapText": string[];
  "cilX": string[];
  "cilZoomIn": string[];
  "cilZoomOut": string[];
  "cilYen": string[];
}
export declare const cil4k: string[];
export declare const cilActionUndo: string[];
export declare const cilAccountLogout: string[];
export declare const cilActionRedo: string[];
export declare const cilAirplaneModeOff: string[];
export declare const cilAddressBook: string[];
export declare const cilAlarm: string[];
export declare const cilAirplaneMode: string[];
export declare const cilAlbum: string[];
export declare const cilAirplay: string[];
export declare const cilAlignCenter: string[];
export declare const cilAmericanFootball: string[];
export declare const cilAlignLeft: string[];
export declare const cilAlignRight: string[];
export declare const cilAperture: string[];
export declare const cil3d: string[];
export declare const cilApple: string[];
export declare const cilApplicationsSettings: string[];
export declare const cilArrowBottom: string[];
export declare const cilArrowCircleBottom: string[];
export declare const cilArrowCircleRight: string[];
export declare const cilApplications: string[];
export declare const cilArrowCircleTop: string[];
export declare const cilArrowCircleLeft: string[];
export declare const cilArrowRight: string[];
export declare const cilArrowThickBottom: string[];
export declare const cilArrowLeft: string[];
export declare const cilArrowThickFromLeft: string[];
export declare const cilArrowThickFromBottom: string[];
export declare const cilArrowThickFromRight: string[];
export declare const cilArrowThickFromTop: string[];
export declare const cilArrowThickLeft: string[];
export declare const cilArrowThickRight: string[];
export declare const cilArrowThickToBottom: string[];
export declare const cilArrowThickToLeft: string[];
export declare const cilArrowThickToRight: string[];
export declare const cilArrowThickToTop: string[];
export declare const cilArrowThickTop: string[];
export declare const cilArrowTop: string[];
export declare const cilAsteriskCircle: string[];
export declare const cilAt: string[];
export declare const cilAudioDescription: string[];
export declare const cilAssistiveListeningSystem: string[];
export declare const cilAudioSpectrum: string[];
export declare const cilBadge: string[];
export declare const cilAudio: string[];
export declare const cilAvTimer: string[];
export declare const cilAsterisk: string[];
export declare const cilBalanceScale: string[];
export declare const cilBarChart: string[];
export declare const cilBan: string[];
export declare const cilBank: string[];
export declare const cilBarcode: string[];
export declare const cilBasket: string[];
export declare const cilBaseball: string[];
export declare const cilBasketball: string[];
export declare const cilBattery0: string[];
export declare const cilBattery3: string[];
export declare const cilBatteryAlert: string[];
export declare const cilBattery5: string[];
export declare const cilBatterySlash: string[];
export declare const cilBed: string[];
export declare const cilBeaker: string[];
export declare const cilBeachAccess: string[];
export declare const cilBath: string[];
export declare const cilBell: string[];
export declare const cilBirthdayCake: string[];
export declare const cilBlind: string[];
export declare const cilBike: string[];
export declare const cilBluetooth: string[];
export declare const cilBlurCircular: string[];
export declare const cilBoatAlt: string[];
export declare const cilBold: string[];
export declare const cilBlurLinear: string[];
export declare const cilBook: string[];
export declare const cilBolt: string[];
export declare const cilBlur: string[];
export declare const cilBookmark: string[];
export declare const cilBorderBottom: string[];
export declare const cilBorderClear: string[];
export declare const cilBorderHorizontal: string[];
export declare const cilBorderInner: string[];
export declare const cilBorderAll: string[];
export declare const cilBorderLeft: string[];
export declare const cilBorderRight: string[];
export declare const cilBorderOuter: string[];
export declare const cilBorderStyle: string[];
export declare const cilBorderTop: string[];
export declare const cilBorderVertical: string[];
export declare const cilBowling: string[];
export declare const cilBritishPound: string[];
export declare const cilBrightness: string[];
export declare const cilBraille: string[];
export declare const cilBriefcase: string[];
export declare const cilBrowser: string[];
export declare const cilBrush: string[];
export declare const cilBug: string[];
export declare const cilBuilding: string[];
export declare const cilBullhorn: string[];
export declare const cilBurger: string[];
export declare const cilBusAlt: string[];
export declare const cilBrushAlt: string[];
export declare const cilCalculator: string[];
export declare const cilCameraRoll: string[];
export declare const cilCalendarCheck: string[];
export declare const cilCalendar: string[];
export declare const cilCarAlt: string[];
export declare const cilCamera: string[];
export declare const cilCameraControl: string[];
export declare const cilCaretLeft: string[];
export declare const cilCaretBottom: string[];
export declare const cilCaretTop: string[];
export declare const cilCart: string[];
export declare const cilCaretRight: string[];
export declare const cilCast: string[];
export declare const cilCenterFocus: string[];
export declare const cilCasino: string[];
export declare const cilCat: string[];
export declare const cilChart: string[];
export declare const cilChartLine: string[];
export declare const cilCheckAlt: string[];
export declare const cilChatBubble: string[];
export declare const cilChartPie: string[];
export declare const cilCheckCircle: string[];
export declare const cilCheck: string[];
export declare const cilChevronBottom: string[];
export declare const cilChevronCircleLeftAlt: string[];
export declare const cilChevronCircleDownAlt: string[];
export declare const cilChevronCircleRightAlt: string[];
export declare const cilChevronDoubleLeft: string[];
export declare const cilChevronCircleUpAlt: string[];
export declare const cilChevronDoubleUp: string[];
export declare const cilChevronDoubleRight: string[];
export declare const cilChevronDoubleUpAlt: string[];
export declare const cilChevronTop: string[];
export declare const cilChevronLeft: string[];
export declare const cilChevronRight: string[];
export declare const cilChildFriendly: string[];
export declare const cilChevronDoubleDown: string[];
export declare const cilChild: string[];
export declare const cilClipboard: string[];
export declare const cilClearAll: string[];
export declare const cilClone: string[];
export declare const cilClock: string[];
export declare const cilCloudUpload: string[];
export declare const cilCloud: string[];
export declare const cilClosedCaptioning: string[];
export declare const cilCloudy: string[];
export declare const cilCode: string[];
export declare const cilCoffee: string[];
export declare const cilColorBorder: string[];
export declare const cilCloudDownload: string[];
export declare const cilColorFill: string[];
export declare const cilColorPalette: string[];
export declare const cilCircle: string[];
export declare const cilColumns: string[];
export declare const cilCommentSquare: string[];
export declare const cilCommentBubble: string[];
export declare const cilCompass: string[];
export declare const cilContact: string[];
export declare const cilContrast: string[];
export declare const cilCompress: string[];
export declare const cilCopy: string[];
export declare const cilCouch: string[];
export declare const cilCropRotate: string[];
export declare const cilCreditCard: string[];
export declare const cilCrop: string[];
export declare const cilCut: string[];
export declare const cilCursor: string[];
export declare const cilDataTransferDown: string[];
export declare const cilDeaf: string[];
export declare const cilDescription: string[];
export declare const cilDevices: string[];
export declare const cilDataTransferUp: string[];
export declare const cilDialpad: string[];
export declare const cilCursorMove: string[];
export declare const cilDog: string[];
export declare const cilDinner: string[];
export declare const cilDollar: string[];
export declare const cilDoubleQuoteSansRight: string[];
export declare const cilDrinkAlcohol: string[];
export declare const cilDoor: string[];
export declare const cilDrop: string[];
export declare const cilDrink: string[];
export declare const cilDoubleQuoteSansLeft: string[];
export declare const cilElevator: string[];
export declare const cilEnvelopeClosed: string[];
export declare const cilEnvelopeOpen: string[];
export declare const cilEthernet: string[];
export declare const cilEnvelopeLetter: string[];
export declare const cilEuro: string[];
export declare const cilExcerpt: string[];
export declare const cilExitToApp: string[];
export declare const cilExpandLeft: string[];
export declare const cilExpandDown: string[];
export declare const cilExpandRight: string[];
export declare const cilExpandUp: string[];
export declare const cilExposure: string[];
export declare const cilDrop1: string[];
export declare const cilExternalLink: string[];
export declare const cilEyedropper: string[];
export declare const cilFaceDead: string[];
export declare const cilFastfood: string[];
export declare const cilFace: string[];
export declare const cilEqualizer: string[];
export declare const cilFax: string[];
export declare const cilFeaturedPlaylist: string[];
export declare const cilFile: string[];
export declare const cilFilterPhoto: string[];
export declare const cilFilter: string[];
export declare const cilFingerprint: string[];
export declare const cilFilterFrames: string[];
export declare const cilFlagAlt: string[];
export declare const cilFindInPage: string[];
export declare const cilFlightTakeoff: string[];
export declare const cilFlip: string[];
export declare const cilFlipToBack: string[];
export declare const cilFolderOpen: string[];
export declare const cilFlower: string[];
export declare const cilFire: string[];
export declare const cilFolder: string[];
export declare const cilFont: string[];
export declare const cilFootball: string[];
export declare const cilFrown: string[];
export declare const cilFlipToFront: string[];
export declare const cilFork: string[];
export declare const cilFullscreenExit: string[];
export declare const cilFridge: string[];
export declare const cilFullscreen: string[];
export declare const cilFunctionsAlt: string[];
export declare const cilFunctions: string[];
export declare const cilGarage: string[];
export declare const cilGamepad: string[];
export declare const cilGem: string[];
export declare const cilGif: string[];
export declare const cilGift: string[];
export declare const cilGlobeAlt: string[];
export declare const cilGolfAlt: string[];
export declare const cilGolf: string[];
export declare const cilGradient: string[];
export declare const cilGrain: string[];
export declare const cilGraph: string[];
export declare const cilGridSlash: string[];
export declare const cilGrid: string[];
export declare const cilHandPointUp: string[];
export declare const cilHandPointLeft: string[];
export declare const cilHd: string[];
export declare const cilHdr: string[];
export declare const cilHandPointDown: string[];
export declare const cilHandPointRight: string[];
export declare const cilHeader: string[];
export declare const cilHeadphones: string[];
export declare const cilHighligt: string[];
export declare const cilHeart: string[];
export declare const cilHighlighter: string[];
export declare const cilHospital: string[];
export declare const cilHotTub: string[];
export declare const cilHistory: string[];
export declare const cilHome: string[];
export declare const cilHealing: string[];
export declare const cilHouse: string[];
export declare const cilHttps: string[];
export declare const cilImageBroken: string[];
export declare const cilImage1: string[];
export declare const cilImagePlus: string[];
export declare const cilInbox: string[];
export declare const cilIndentDecrease: string[];
export declare const cilIndustrySlash: string[];
export declare const cilInfinity: string[];
export declare const cilIndustry: string[];
export declare const cilInfo: string[];
export declare const cilInputHdmi: string[];
export declare const cilInstitution: string[];
export declare const cilInput: string[];
export declare const cilInputPower: string[];
export declare const cilJustifyCenter: string[];
export declare const cilItalic: string[];
export declare const cilJustifyLeft: string[];
export declare const cilJustifyRight: string[];
export declare const cilKeyboard: string[];
export declare const cilLan: string[];
export declare const cilLanguage: string[];
export declare const cilLaptop: string[];
export declare const cilIndentIncrease: string[];
export declare const cilLayers: string[];
export declare const cilLeaf: string[];
export declare const cilLemon: string[];
export declare const cilLevelUp: string[];
export declare const cilLevelDown: string[];
export declare const cilLibraryAdd: string[];
export declare const cilLibrary: string[];
export declare const cilLifeRing: string[];
export declare const cilLightbulb: string[];
export declare const cilLineSpacing: string[];
export declare const cilLineStyle: string[];
export declare const cilLineWeight: string[];
export declare const cilLink: string[];
export declare const cilListHighPriority: string[];
export declare const cilListFilter: string[];
export declare const cilLinkAlt: string[];
export declare const cilListLowPriority: string[];
export declare const cilLinkBroken: string[];
export declare const cilListRich: string[];
export declare const cilListNumbered: string[];
export declare const cilLocationPin: string[];
export declare const cilList: string[];
export declare const cilLockLocked: string[];
export declare const cilLocomotive: string[];
export declare const cilLockUnlocked: string[];
export declare const cilLoopCircular: string[];
export declare const cilLoop1: string[];
export declare const cilLowVision: string[];
export declare const cilLoop: string[];
export declare const cilMagnifyingGlass: string[];
export declare const cilMap: string[];
export declare const cilMediaEject: string[];
export declare const cilMediaPause: string[];
export declare const cilMediaPlay: string[];
export declare const cilMediaSkipBackward: string[];
export declare const cilMediaRecord: string[];
export declare const cilMediaSkipForward: string[];
export declare const cilMediaStepBackward: string[];
export declare const cilMediaStepForward: string[];
export declare const cilMediaStop: string[];
export declare const cilMeh: string[];
export declare const cilMedicalCross: string[];
export declare const cilMemory: string[];
export declare const cilMinus: string[];
export declare const cilMenu: string[];
export declare const cilMicrophone: string[];
export declare const cilMobileLandscape: string[];
export declare const cilMonitor: string[];
export declare const cilMoney: string[];
export declare const cilMobile: string[];
export declare const cilMoodBad: string[];
export declare const cilMoodGood: string[];
export declare const cilMoodVeryBad: string[];
export declare const cilMoodVeryGood: string[];
export declare const cilMoon: string[];
export declare const cilMouthSlash: string[];
export declare const cilMouse: string[];
export declare const cilMovie: string[];
export declare const cilMove: string[];
export declare const cilMug: string[];
export declare const cilMugTea: string[];
export declare const cilObjectGroup: string[];
export declare const cilMusicNote: string[];
export declare const cilNewspaper: string[];
export declare const cilNotes: string[];
export declare const cilOptionsHorizontal: string[];
export declare const cilObjectUngroup: string[];
export declare const cilOptions: string[];
export declare const cilOpacity: string[];
export declare const cilPaintBucket: string[];
export declare const cilPaint: string[];
export declare const cilPaperPlane: string[];
export declare const cilPaperclip: string[];
export declare const cilPaw: string[];
export declare const cilPenNib: string[];
export declare const cilPencil: string[];
export declare const cilPenAlt: string[];
export declare const cilParagraph: string[];
export declare const cilPin: string[];
export declare const cilPhone: string[];
export declare const cilPizza: string[];
export declare const cilPlaylistAdd: string[];
export declare const cilPeople: string[];
export declare const cilPlus: string[];
export declare const cilPowerStandby: string[];
export declare const cilPool: string[];
export declare const cilPregnant: string[];
export declare const cilPuzzle: string[];
export declare const cilPrint: string[];
export declare const cilQrCode: string[];
export declare const cilRectangle: string[];
export declare const cilReload: string[];
export declare const cilRain: string[];
export declare const cilRemove: string[];
export declare const cilResizeBoth: string[];
export declare const cilResizeHeight: string[];
export declare const cilResizeWidth: string[];
export declare const cilRestaurant: string[];
export declare const cilRoom: string[];
export declare const cilRowing: string[];
export declare const cilRunning: string[];
export declare const cilRss: string[];
export declare const cilSatelite: string[];
export declare const cilSchool: string[];
export declare const cilSave: string[];
export declare const cilScreenDesktop: string[];
export declare const cilScreenSmartphone: string[];
export declare const cilScrubber: string[];
export declare const cilShareAll: string[];
export declare const cilSettings: string[];
export declare const cilShareBoxed: string[];
export declare const cilShare: string[];
export declare const cilShareAlt: string[];
export declare const cilShieldAlt: string[];
export declare const cilShortText: string[];
export declare const cilSignLanguage: string[];
export declare const cilShower: string[];
export declare const cilSignalCellular0: string[];
export declare const cilSignalCellular3: string[];
export declare const cilSignalCellular4: string[];
export declare const cilSim: string[];
export declare const cilSmilePlus: string[];
export declare const cilSmile: string[];
export declare const cilSitemap: string[];
export declare const cilSmokeFree: string[];
export declare const cilSmokingRoom: string[];
export declare const cilSnowflake: string[];
export declare const cilSortAlphaDown: string[];
export declare const cilSortAlphaUp: string[];
export declare const cilSortAscending: string[];
export declare const cilSortNumericDown: string[];
export declare const cilSortNumericUp: string[];
export declare const cilSortDescending: string[];
export declare const cilSpa: string[];
export declare const cilSpeaker: string[];
export declare const cilSpeech: string[];
export declare const cilSpaceBar: string[];
export declare const cilSpeedometer: string[];
export declare const cilSpreadsheet: string[];
export declare const cilStarHalf: string[];
export declare const cilStar: string[];
export declare const cilStream: string[];
export declare const cilStorage: string[];
export declare const cilSun: string[];
export declare const cilSquare: string[];
export declare const cilSwapHorizontal: string[];
export declare const cilSwapVertical: string[];
export declare const cilSwimming: string[];
export declare const cilTablet: string[];
export declare const cilSync: string[];
export declare const cilTag: string[];
export declare const cilTags: string[];
export declare const cilTask: string[];
export declare const cilTaxi: string[];
export declare const cilTennisBall: string[];
export declare const cilTennis: string[];
export declare const cilTerminal: string[];
export declare const cilTextShapes: string[];
export declare const cilTerrain: string[];
export declare const cilTextSize: string[];
export declare const cilTextSquare: string[];
export declare const cilTextStrike: string[];
export declare const cilText: string[];
export declare const cilThumbDown: string[];
export declare const cilThumbUp: string[];
export declare const cilToggleOff: string[];
export declare const cilToilet: string[];
export declare const cilTouchApp: string[];
export declare const cilTransfer: string[];
export declare const cilTranslate: string[];
export declare const cilTrash: string[];
export declare const cilTriangle: string[];
export declare const cilTruck: string[];
export declare const cilTv: string[];
export declare const cilUserFemale: string[];
export declare const cilUnderline: string[];
export declare const cilUserFollow: string[];
export declare const cilUser: string[];
export declare const cilUserUnfollow: string[];
export declare const cilVector: string[];
export declare const cilVerticalAlignBottom1: string[];
export declare const cilVerticalAlignBottom: string[];
export declare const cilVerticalAlignCenter: string[];
export declare const cilVerticalAlignCenter1: string[];
export declare const cilVerticalAlignTop1: string[];
export declare const cilVideo: string[];
export declare const cilViewColumn: string[];
export declare const cilVerticalAlignTop: string[];
export declare const cilViewModule: string[];
export declare const cilViewStream: string[];
export declare const cilViewQuilt: string[];
export declare const cilVolumeHigh: string[];
export declare const cilVoiceOverRecord: string[];
export declare const cilWalk: string[];
export declare const cilVolumeLow: string[];
export declare const cilVolumeOff: string[];
export declare const cilWallet: string[];
export declare const cilWallpaper: string[];
export declare const cilWarning: string[];
export declare const cilWatch: string[];
export declare const cilWc: string[];
export declare const cilWeightlifitng: string[];
export declare const cilWheelchair: string[];
export declare const cilWifiSignal0: string[];
export declare const cilWifiSignal1: string[];
export declare const cilWifiSignalOff: string[];
export declare const cilWifiSignal4: string[];
export declare const cilWindowMaximize: string[];
export declare const cilWindowMinimize: string[];
export declare const cilWifiSignal2: string[];
export declare const cilWindow: string[];
export declare const cilWindowRestore: string[];
export declare const cilXCircle: string[];
export declare const cilWrapText: string[];
export declare const cilX: string[];
export declare const cilZoomIn: string[];
export declare const cilZoomOut: string[];
export declare const cilYen: string[];