export declare const n3d: string[];
export declare const n4k: string[];
export declare const accountLogout: string[];
export declare const actionRedo: string[];
export declare const actionUndo: string[];
export declare const addressBook: string[];
export declare const airplaneModeOff: string[];
export declare const airplaneMode: string[];
export declare const airplay: string[];
export declare const alarm: string[];
export declare const album: string[];
export declare const alignCenter: string[];
export declare const alignLeft: string[];
export declare const alignRight: string[];
export declare const americanFootball: string[];
export declare const aperture: string[];
export declare const applicationsSettings: string[];
export declare const applications: string[];
export declare const arrowBottom: string[];
export declare const arrowCircleBottom: string[];
export declare const arrowCircleLeft: string[];
export declare const arrowCircleRight: string[];
export declare const arrowCircleTop: string[];
export declare const arrowLeft: string[];
export declare const arrowRight: string[];
export declare const arrowThickBottom: string[];
export declare const arrowThickFromBottom: string[];
export declare const arrowThickFromLeft: string[];
export declare const arrowThickFromRight: string[];
export declare const arrowThickFromTop: string[];
export declare const arrowThickLeft: string[];
export declare const arrowThickRight: string[];
export declare const arrowThickToBottom: string[];
export declare const arrowThickToLeft: string[];
export declare const arrowThickToRight: string[];
export declare const arrowThickToTop: string[];
export declare const arrowThickTop: string[];
export declare const arrowTop: string[];
export declare const assistiveListeningSystem: string[];
export declare const asteriskCircle: string[];
export declare const asterisk: string[];
export declare const at: string[];
export declare const audioDescription: string[];
export declare const audioSpectrum: string[];
export declare const audio: string[];
export declare const avTimer: string[];
export declare const badge: string[];
export declare const balanceScale: string[];
export declare const ban: string[];
export declare const bank: string[];
export declare const barChart: string[];
export declare const barcode: string[];
export declare const baseball: string[];
export declare const basket: string[];
export declare const basketball: string[];
export declare const bath: string[];
export declare const battery0: string[];
export declare const battery3: string[];
export declare const battery5: string[];
export declare const batteryAlert: string[];
export declare const batterySlash: string[];
export declare const beachAccess: string[];
export declare const beaker: string[];
export declare const bed: string[];
export declare const bell: string[];
export declare const bike: string[];
export declare const birthdayCake: string[];
export declare const blind: string[];
export declare const blurCircular: string[];
export declare const blurLinear: string[];
export declare const blur: string[];
export declare const boatAlt: string[];
export declare const bold: string[];
export declare const bolt: string[];
export declare const book: string[];
export declare const bookmark: string[];
export declare const borderAll: string[];
export declare const borderBottom: string[];
export declare const borderClear: string[];
export declare const borderHorizontal: string[];
export declare const borderInner: string[];
export declare const borderLeft: string[];
export declare const borderOuter: string[];
export declare const borderRight: string[];
export declare const borderStyle: string[];
export declare const borderTop: string[];
export declare const borderVertical: string[];
export declare const bowling: string[];
export declare const braille: string[];
export declare const briefcase: string[];
export declare const brightness: string[];
export declare const britishPound: string[];
export declare const browser: string[];
export declare const brushAlt: string[];
export declare const brush: string[];
export declare const bug: string[];
export declare const building: string[];
export declare const bullhorn: string[];
export declare const burger: string[];
export declare const busAlt: string[];
export declare const calculator: string[];
export declare const calendarCheck: string[];
export declare const calendar: string[];
export declare const cameraControl: string[];
export declare const cameraRoll: string[];
export declare const camera: string[];
export declare const carAlt: string[];
export declare const caretBottom: string[];
export declare const caretLeft: string[];
export declare const caretRight: string[];
export declare const caretTop: string[];
export declare const cart: string[];
export declare const casino: string[];
export declare const cast: string[];
export declare const cat: string[];
export declare const centerFocus: string[];
export declare const chartLine: string[];
export declare const chartPie: string[];
export declare const chart: string[];
export declare const chatBubble: string[];
export declare const check: string[];
export declare const chevronBottom: string[];
export declare const chevronCircleDownAlt: string[];
export declare const chevronCircleLeftAlt: string[];
export declare const chevronCircleRightAlt: string[];
export declare const chevronCircleUpAlt: string[];
export declare const chevronDoubleDown: string[];
export declare const chevronDoubleLeft: string[];
export declare const chevronDoubleRight: string[];
export declare const chevronDoubleUpAlt: string[];
export declare const chevronDoubleUp: string[];
export declare const chevronLeft: string[];
export declare const chevronRight: string[];
export declare const chevronTop: string[];
export declare const childFriendly: string[];
export declare const child: string[];
export declare const clearAll: string[];
export declare const clipboard: string[];
export declare const clock: string[];
export declare const clone: string[];
export declare const closedCaptioning: string[];
export declare const cloudDownload: string[];
export declare const cloudUpload: string[];
export declare const cloud: string[];
export declare const cloudy: string[];
export declare const code: string[];
export declare const coffee: string[];
export declare const colorBorder: string[];
export declare const colorFill: string[];
export declare const colorPalette: string[];
export declare const columns: string[];
export declare const commentBubble: string[];
export declare const commentSquare: string[];
export declare const compass: string[];
export declare const compress: string[];
export declare const contact: string[];
export declare const contrast: string[];
export declare const copy: string[];
export declare const copyright: string[];
export declare const couch: string[];
export declare const creditCard: string[];
export declare const cropRotate: string[];
export declare const crop: string[];
export declare const cursorMove: string[];
export declare const cursor: string[];
export declare const cut: string[];
export declare const dataTransferDown: string[];
export declare const dataTransferUp: string[];
export declare const deaf: string[];
export declare const description: string[];
export declare const devices: string[];
export declare const dialpad: string[];
export declare const dinner: string[];
export declare const dog: string[];
export declare const dollar: string[];
export declare const door: string[];
export declare const doubleQuoteSansLeft: string[];
export declare const doubleQuoteSansRight: string[];
export declare const drinkAlcohol: string[];
export declare const drink: string[];
export declare const drop: string[];
export declare const drop1: string[];
export declare const elevator: string[];
export declare const envelopeClosed: string[];
export declare const envelopeLetter: string[];
export declare const envelopeOpen: string[];
export declare const equalizer: string[];
export declare const ethernet: string[];
export declare const euro: string[];
export declare const excerpt: string[];
export declare const exitToApp: string[];
export declare const expandDown: string[];
export declare const expandLeft: string[];
export declare const expandRight: string[];
export declare const expandUp: string[];
export declare const exposure: string[];
export declare const externalLink: string[];
export declare const eyedropper: string[];
export declare const faceDead: string[];
export declare const face: string[];
export declare const fastfood: string[];
export declare const fax: string[];
export declare const featuredPlaylist: string[];
export declare const file: string[];
export declare const filterFrames: string[];
export declare const filterPhoto: string[];
export declare const filter: string[];
export declare const findInPage: string[];
export declare const fingerprint: string[];
export declare const fire: string[];
export declare const flagAlt: string[];
export declare const flightTakeoff: string[];
export declare const flipToBack: string[];
export declare const flipToFront: string[];
export declare const flip: string[];
export declare const flower: string[];
export declare const folderOpen: string[];
export declare const folder: string[];
export declare const font: string[];
export declare const football: string[];
export declare const fork: string[];
export declare const freeSet: {
    "3d": string[];
    "4k": string[];
    "actionRedo": string[];
    "accountLogout": string[];
    "actionUndo": string[];
    "addressBook": string[];
    "airplaneMode": string[];
    "airplaneModeOff": string[];
    "airplay": string[];
    "alarm": string[];
    "album": string[];
    "alignCenter": string[];
    "alignLeft": string[];
    "alignRight": string[];
    "americanFootball": string[];
    "aperture": string[];
    "applicationsSettings": string[];
    "applications": string[];
    "arrowBottom": string[];
    "arrowCircleLeft": string[];
    "arrowRight": string[];
    "arrowCircleBottom": string[];
    "arrowCircleTop": string[];
    "arrowThickBottom": string[];
    "arrowThickFromLeft": string[];
    "arrowThickFromBottom": string[];
    "arrowThickFromRight": string[];
    "arrowThickFromTop": string[];
    "arrowThickLeft": string[];
    "arrowCircleRight": string[];
    "arrowThickRight": string[];
    "arrowThickToBottom": string[];
    "arrowThickToLeft": string[];
    "arrowLeft": string[];
    "arrowThickToRight": string[];
    "arrowThickToTop": string[];
    "arrowThickTop": string[];
    "arrowTop": string[];
    "assistiveListeningSystem": string[];
    "asteriskCircle": string[];
    "at": string[];
    "asterisk": string[];
    "audioDescription": string[];
    "audioSpectrum": string[];
    "audio": string[];
    "avTimer": string[];
    "badge": string[];
    "balanceScale": string[];
    "ban": string[];
    "bank": string[];
    "barChart": string[];
    "basket": string[];
    "baseball": string[];
    "barcode": string[];
    "bath": string[];
    "basketball": string[];
    "battery3": string[];
    "battery0": string[];
    "batteryAlert": string[];
    "battery5": string[];
    "batterySlash": string[];
    "beachAccess": string[];
    "beaker": string[];
    "bell": string[];
    "birthdayCake": string[];
    "bed": string[];
    "bike": string[];
    "blind": string[];
    "blur": string[];
    "blurCircular": string[];
    "boatAlt": string[];
    "blurLinear": string[];
    "bold": string[];
    "bolt": string[];
    "book": string[];
    "borderAll": string[];
    "bookmark": string[];
    "borderBottom": string[];
    "borderClear": string[];
    "borderHorizontal": string[];
    "borderLeft": string[];
    "borderInner": string[];
    "borderRight": string[];
    "borderOuter": string[];
    "borderTop": string[];
    "borderStyle": string[];
    "bowling": string[];
    "borderVertical": string[];
    "braille": string[];
    "briefcase": string[];
    "brightness": string[];
    "britishPound": string[];
    "browser": string[];
    "brushAlt": string[];
    "brush": string[];
    "bug": string[];
    "building": string[];
    "bullhorn": string[];
    "burger": string[];
    "busAlt": string[];
    "calculator": string[];
    "calendarCheck": string[];
    "cameraControl": string[];
    "calendar": string[];
    "caretBottom": string[];
    "carAlt": string[];
    "cameraRoll": string[];
    "camera": string[];
    "caretRight": string[];
    "caretLeft": string[];
    "caretTop": string[];
    "cart": string[];
    "casino": string[];
    "cast": string[];
    "cat": string[];
    "centerFocus": string[];
    "chartLine": string[];
    "chartPie": string[];
    "chart": string[];
    "chatBubble": string[];
    "chevronBottom": string[];
    "check": string[];
    "chevronCircleDownAlt": string[];
    "chevronCircleLeftAlt": string[];
    "chevronCircleUpAlt": string[];
    "chevronCircleRightAlt": string[];
    "chevronDoubleDown": string[];
    "chevronDoubleRight": string[];
    "chevronRight": string[];
    "chevronDoubleLeft": string[];
    "chevronDoubleUpAlt": string[];
    "chevronDoubleUp": string[];
    "chevronLeft": string[];
    "chevronTop": string[];
    "child": string[];
    "childFriendly": string[];
    "clipboard": string[];
    "clearAll": string[];
    "clock": string[];
    "cloudDownload": string[];
    "clone": string[];
    "closedCaptioning": string[];
    "cloud": string[];
    "cloudy": string[];
    "cloudUpload": string[];
    "code": string[];
    "coffee": string[];
    "colorFill": string[];
    "commentBubble": string[];
    "commentSquare": string[];
    "colorPalette": string[];
    "compass": string[];
    "compress": string[];
    "columns": string[];
    "contact": string[];
    "contrast": string[];
    "copyright": string[];
    "copy": string[];
    "colorBorder": string[];
    "couch": string[];
    "creditCard": string[];
    "cropRotate": string[];
    "cursor": string[];
    "crop": string[];
    "cut": string[];
    "cursorMove": string[];
    "dataTransferDown": string[];
    "dataTransferUp": string[];
    "description": string[];
    "devices": string[];
    "deaf": string[];
    "dialpad": string[];
    "dinner": string[];
    "dollar": string[];
    "dog": string[];
    "door": string[];
    "doubleQuoteSansRight": string[];
    "doubleQuoteSansLeft": string[];
    "drink": string[];
    "envelopeClosed": string[];
    "drinkAlcohol": string[];
    "drop": string[];
    "drop1": string[];
    "elevator": string[];
    "envelopeOpen": string[];
    "envelopeLetter": string[];
    "equalizer": string[];
    "ethernet": string[];
    "excerpt": string[];
    "exitToApp": string[];
    "euro": string[];
    "expandLeft": string[];
    "expandDown": string[];
    "exposure": string[];
    "expandUp": string[];
    "expandRight": string[];
    "externalLink": string[];
    "face": string[];
    "faceDead": string[];
    "eyedropper": string[];
    "fax": string[];
    "fastfood": string[];
    "file": string[];
    "featuredPlaylist": string[];
    "filterFrames": string[];
    "filterPhoto": string[];
    "findInPage": string[];
    "fingerprint": string[];
    "filter": string[];
    "fire": string[];
    "flagAlt": string[];
    "flipToFront": string[];
    "flipToBack": string[];
    "flightTakeoff": string[];
    "flower": string[];
    "folderOpen": string[];
    "flip": string[];
    "folder": string[];
    "font": string[];
    "football": string[];
    "fridge": string[];
    "fork": string[];
    "fullscreenExit": string[];
    "functionsAlt": string[];
    "frown": string[];
    "fullscreen": string[];
    "functions": string[];
    "gamepad": string[];
    "gem": string[];
    "garage": string[];
    "gif": string[];
    "githubCircle": string[];
    "gift": string[];
    "grain": string[];
    "golfAlt": string[];
    "golf": string[];
    "globeAlt": string[];
    "gradient": string[];
    "graph": string[];
    "gridSlash": string[];
    "handPointDown": string[];
    "handPointLeft": string[];
    "grid": string[];
    "hd": string[];
    "handPointRight": string[];
    "handPointUp": string[];
    "hdr": string[];
    "headphones": string[];
    "healing": string[];
    "header": string[];
    "heart": string[];
    "history": string[];
    "highlighter": string[];
    "highligt": string[];
    "home": string[];
    "hotTub": string[];
    "hospital": string[];
    "house": string[];
    "https": string[];
    "imagePlus": string[];
    "imageBroken": string[];
    "image1": string[];
    "inbox": string[];
    "indentDecrease": string[];
    "industrySlash": string[];
    "indentIncrease": string[];
    "industry": string[];
    "infinity": string[];
    "info": string[];
    "inputHdmi": string[];
    "inputPower": string[];
    "italic": string[];
    "justifyLeft": string[];
    "keyboard": string[];
    "justifyCenter": string[];
    "input": string[];
    "justifyRight": string[];
    "language": string[];
    "lan": string[];
    "institution": string[];
    "laptop": string[];
    "lemon": string[];
    "leaf": string[];
    "levelUp": string[];
    "layers": string[];
    "levelDown": string[];
    "lightbulb": string[];
    "libraryAdd": string[];
    "lifeRing": string[];
    "library": string[];
    "lineSpacing": string[];
    "lineStyle": string[];
    "linkBroken": string[];
    "lineWeight": string[];
    "link": string[];
    "listFilter": string[];
    "listHighPriority": string[];
    "listLowPriority": string[];
    "listRich": string[];
    "linkAlt": string[];
    "listNumbered": string[];
    "locationPin": string[];
    "list": string[];
    "lockLocked": string[];
    "locomotive": string[];
    "lockUnlocked": string[];
    "loop1": string[];
    "loopCircular": string[];
    "loop": string[];
    "mediaEject": string[];
    "lowVision": string[];
    "magnifyingGlass": string[];
    "mediaPause": string[];
    "mediaPlay": string[];
    "map": string[];
    "mediaRecord": string[];
    "mediaSkipBackward": string[];
    "mediaSkipForward": string[];
    "mediaStepForward": string[];
    "mediaStepBackward": string[];
    "medicalCross": string[];
    "mediaStop": string[];
    "memory": string[];
    "meh": string[];
    "microphone": string[];
    "menu": string[];
    "minus": string[];
    "mobileLandscape": string[];
    "mobile": string[];
    "money": string[];
    "moodBad": string[];
    "monitor": string[];
    "moodVeryBad": string[];
    "moon": string[];
    "moodVeryGood": string[];
    "moodGood": string[];
    "mouthSlash": string[];
    "mouse": string[];
    "move": string[];
    "mugTea": string[];
    "movie": string[];
    "mug": string[];
    "musicNote": string[];
    "newspaper": string[];
    "notes": string[];
    "objectGroup": string[];
    "objectUngroup": string[];
    "opacity": string[];
    "optionsHorizontal": string[];
    "paintBucket": string[];
    "options": string[];
    "paperPlane": string[];
    "paint": string[];
    "paperclip": string[];
    "paragraph": string[];
    "paw": string[];
    "penAlt": string[];
    "people": string[];
    "penNib": string[];
    "pencil": string[];
    "phone": string[];
    "pin": string[];
    "pizza": string[];
    "playlistAdd": string[];
    "plus": string[];
    "polymer": string[];
    "pool": string[];
    "print": string[];
    "powerStandby": string[];
    "pregnant": string[];
    "puzzle": string[];
    "rectangle": string[];
    "rain": string[];
    "qrCode": string[];
    "registered": string[];
    "reload": string[];
    "resizeBoth": string[];
    "remove": string[];
    "resizeWidth": string[];
    "room": string[];
    "resizeHeight": string[];
    "restaurant": string[];
    "rowing": string[];
    "satelite": string[];
    "running": string[];
    "save": string[];
    "school": string[];
    "screenDesktop": string[];
    "screenSmartphone": string[];
    "scrubber": string[];
    "settings": string[];
    "shareBoxed": string[];
    "shareAll": string[];
    "shieldAlt": string[];
    "shareAlt": string[];
    "shortText": string[];
    "share": string[];
    "shower": string[];
    "signLanguage": string[];
    "signalCellular0": string[];
    "signalCellular4": string[];
    "sim": string[];
    "signalCellular3": string[];
    "sitemap": string[];
    "smile": string[];
    "smilePlus": string[];
    "smokeFree": string[];
    "snowflake": string[];
    "sortAlphaUp": string[];
    "sortAlphaDown": string[];
    "sortDescending": string[];
    "smokingRoom": string[];
    "sortNumericDown": string[];
    "sortAscending": string[];
    "spa": string[];
    "sortNumericUp": string[];
    "speaker": string[];
    "spaceBar": string[];
    "speedometer": string[];
    "speech": string[];
    "starHalf": string[];
    "spreadsheet": string[];
    "square": string[];
    "star": string[];
    "storage": string[];
    "stream": string[];
    "sun": string[];
    "swapHorizontal": string[];
    "tablet": string[];
    "swimming": string[];
    "swapVertical": string[];
    "sync": string[];
    "tags": string[];
    "tag": string[];
    "taxi": string[];
    "task": string[];
    "tennisBall": string[];
    "terminal": string[];
    "tennis": string[];
    "terrain": string[];
    "textShapes": string[];
    "textStrike": string[];
    "textSize": string[];
    "text": string[];
    "textSquare": string[];
    "thumbUp": string[];
    "thumbDown": string[];
    "toggleOff": string[];
    "toilet": string[];
    "touchApp": string[];
    "trademark": string[];
    "transfer": string[];
    "translate": string[];
    "trash": string[];
    "truck": string[];
    "triangle": string[];
    "userFollow": string[];
    "userUnfollow": string[];
    "userFemale": string[];
    "user": string[];
    "verticalAlignBottom": string[];
    "vector": string[];
    "underline": string[];
    "verticalAlignBottom1": string[];
    "verticalAlignCenter": string[];
    "verticalAlignTop": string[];
    "verticalAlignTop1": string[];
    "verticalAlignCenter1": string[];
    "tv": string[];
    "viewModule": string[];
    "video": string[];
    "viewColumn": string[];
    "viewQuilt": string[];
    "viewStream": string[];
    "volumeHigh": string[];
    "voiceOverRecord": string[];
    "volumeLow": string[];
    "volumeOff": string[];
    "wallet": string[];
    "walk": string[];
    "vue": string[];
    "wallpaper": string[];
    "watch": string[];
    "warning": string[];
    "weightlifitng": string[];
    "wc": string[];
    "wifiSignal0": string[];
    "wheelchair": string[];
    "wifiSignal1": string[];
    "wifiSignal2": string[];
    "wifiSignalOff": string[];
    "wifiSignal4": string[];
    "window": string[];
    "windowMaximize": string[];
    "wrapText": string[];
    "windowMinimize": string[];
    "windowRestore": string[];
    "xCircle": string[];
    "yen": string[];
    "x": string[];
    "zoomIn": string[];
    "zoomOut": string[];
};
export declare const fridge: string[];
export declare const frown: string[];
export declare const fullscreenExit: string[];
export declare const fullscreen: string[];
export declare const functionsAlt: string[];
export declare const functions: string[];
export declare const gamepad: string[];
export declare const garage: string[];
export declare const gem: string[];
export declare const gif: string[];
export declare const gift: string[];
export declare const githubCircle: string[];
export declare const globeAlt: string[];
export declare const golfAlt: string[];
export declare const golf: string[];
export declare const gradient: string[];
export declare const grain: string[];
export declare const graph: string[];
export declare const gridSlash: string[];
export declare const grid: string[];
export declare const handPointDown: string[];
export declare const handPointLeft: string[];
export declare const handPointRight: string[];
export declare const handPointUp: string[];
export declare const hd: string[];
export declare const hdr: string[];
export declare const header: string[];
export declare const headphones: string[];
export declare const healing: string[];
export declare const heart: string[];
export declare const highlighter: string[];
export declare const highligt: string[];
export declare const history: string[];
export declare const home: string[];
export declare const hospital: string[];
export declare const hotTub: string[];
export declare const house: string[];
export declare const https: string[];
export declare const imageBroken: string[];
export declare const imagePlus: string[];
export declare const image1: string[];
export declare const inbox: string[];
export declare const indentDecrease: string[];
export declare const indentIncrease: string[];
export declare const industrySlash: string[];
export declare const industry: string[];
export declare const infinity: string[];
export declare const info: string[];
export declare const inputHdmi: string[];
export declare const inputPower: string[];
export declare const input: string[];
export declare const institution: string[];
export declare const italic: string[];
export declare const justifyCenter: string[];
export declare const justifyLeft: string[];
export declare const justifyRight: string[];
export declare const keyboard: string[];
export declare const lan: string[];
export declare const language: string[];
export declare const laptop: string[];
export declare const layers: string[];
export declare const leaf: string[];
export declare const lemon: string[];
export declare const levelDown: string[];
export declare const levelUp: string[];
export declare const libraryAdd: string[];
export declare const library: string[];
export declare const lifeRing: string[];
export declare const lightbulb: string[];
export declare const lineSpacing: string[];
export declare const lineStyle: string[];
export declare const lineWeight: string[];
export declare const linkAlt: string[];
export declare const linkBroken: string[];
export declare const link: string[];
export declare const listFilter: string[];
export declare const listHighPriority: string[];
export declare const listLowPriority: string[];
export declare const listNumbered: string[];
export declare const listRich: string[];
export declare const list: string[];
export declare const locationPin: string[];
export declare const lockLocked: string[];
export declare const lockUnlocked: string[];
export declare const locomotive: string[];
export declare const loop1: string[];
export declare const loopCircular: string[];
export declare const loop: string[];
export declare const lowVision: string[];
export declare const magnifyingGlass: string[];
export declare const map: string[];
export declare const mediaEject: string[];
export declare const mediaPause: string[];
export declare const mediaPlay: string[];
export declare const mediaRecord: string[];
export declare const mediaSkipBackward: string[];
export declare const mediaSkipForward: string[];
export declare const mediaStepBackward: string[];
export declare const mediaStepForward: string[];
export declare const mediaStop: string[];
export declare const medicalCross: string[];
export declare const meh: string[];
export declare const memory: string[];
export declare const menu: string[];
export declare const microphone: string[];
export declare const minus: string[];
export declare const mobileLandscape: string[];
export declare const mobile: string[];
export declare const money: string[];
export declare const monitor: string[];
export declare const moodBad: string[];
export declare const moodGood: string[];
export declare const moodVeryBad: string[];
export declare const moodVeryGood: string[];
export declare const moon: string[];
export declare const mouse: string[];
export declare const mouthSlash: string[];
export declare const move: string[];
export declare const movie: string[];
export declare const mugTea: string[];
export declare const mug: string[];
export declare const musicNote: string[];
export declare const newspaper: string[];
export declare const notes: string[];
export declare const objectGroup: string[];
export declare const objectUngroup: string[];
export declare const opacity: string[];
export declare const optionsHorizontal: string[];
export declare const options: string[];
export declare const paintBucket: string[];
export declare const paint: string[];
export declare const paperPlane: string[];
export declare const paperclip: string[];
export declare const paragraph: string[];
export declare const paw: string[];
export declare const penAlt: string[];
export declare const penNib: string[];
export declare const pencil: string[];
export declare const people: string[];
export declare const phone: string[];
export declare const pin: string[];
export declare const pizza: string[];
export declare const playlistAdd: string[];
export declare const plus: string[];
export declare const polymer: string[];
export declare const pool: string[];
export declare const powerStandby: string[];
export declare const pregnant: string[];
export declare const print: string[];
export declare const puzzle: string[];
export declare const qrCode: string[];
export declare const rain: string[];
export declare const rectangle: string[];
export declare const registered: string[];
export declare const reload: string[];
export declare const remove: string[];
export declare const resizeBoth: string[];
export declare const resizeHeight: string[];
export declare const resizeWidth: string[];
export declare const restaurant: string[];
export declare const room: string[];
export declare const rowing: string[];
export declare const running: string[];
export declare const satelite: string[];
export declare const save: string[];
export declare const school: string[];
export declare const screenDesktop: string[];
export declare const screenSmartphone: string[];
export declare const scrubber: string[];
export declare const settings: string[];
export declare const shareAll: string[];
export declare const shareAlt: string[];
export declare const shareBoxed: string[];
export declare const share: string[];
export declare const shieldAlt: string[];
export declare const shortText: string[];
export declare const shower: string[];
export declare const signLanguage: string[];
export declare const signalCellular0: string[];
export declare const signalCellular3: string[];
export declare const signalCellular4: string[];
export declare const sim: string[];
export declare const sitemap: string[];
export declare const smilePlus: string[];
export declare const smile: string[];
export declare const smokeFree: string[];
export declare const smokingRoom: string[];
export declare const snowflake: string[];
export declare const sortAlphaDown: string[];
export declare const sortAlphaUp: string[];
export declare const sortAscending: string[];
export declare const sortDescending: string[];
export declare const sortNumericDown: string[];
export declare const sortNumericUp: string[];
export declare const spa: string[];
export declare const spaceBar: string[];
export declare const speaker: string[];
export declare const speech: string[];
export declare const speedometer: string[];
export declare const spreadsheet: string[];
export declare const square: string[];
export declare const starHalf: string[];
export declare const star: string[];
export declare const storage: string[];
export declare const stream: string[];
export declare const sun: string[];
export declare const swapHorizontal: string[];
export declare const swapVertical: string[];
export declare const swimming: string[];
export declare const sync: string[];
export declare const tablet: string[];
export declare const tag: string[];
export declare const tags: string[];
export declare const task: string[];
export declare const taxi: string[];
export declare const tennisBall: string[];
export declare const tennis: string[];
export declare const terminal: string[];
export declare const terrain: string[];
export declare const textShapes: string[];
export declare const textSize: string[];
export declare const textSquare: string[];
export declare const textStrike: string[];
export declare const text: string[];
export declare const thumbDown: string[];
export declare const thumbUp: string[];
export declare const toggleOff: string[];
export declare const toilet: string[];
export declare const touchApp: string[];
export declare const trademark: string[];
export declare const transfer: string[];
export declare const translate: string[];
export declare const trash: string[];
export declare const triangle: string[];
export declare const truck: string[];
export declare const tv: string[];
export declare const underline: string[];
export declare const userFemale: string[];
export declare const userFollow: string[];
export declare const userUnfollow: string[];
export declare const user: string[];
export declare const vector: string[];
export declare const verticalAlignBottom: string[];
export declare const verticalAlignBottom1: string[];
export declare const verticalAlignCenter: string[];
export declare const verticalAlignCenter1: string[];
export declare const verticalAlignTop: string[];
export declare const verticalAlignTop1: string[];
export declare const video: string[];
export declare const viewColumn: string[];
export declare const viewModule: string[];
export declare const viewQuilt: string[];
export declare const viewStream: string[];
export declare const voiceOverRecord: string[];
export declare const volumeHigh: string[];
export declare const volumeLow: string[];
export declare const volumeOff: string[];
export declare const vue: string[];
export declare const walk: string[];
export declare const wallet: string[];
export declare const wallpaper: string[];
export declare const warning: string[];
export declare const watch: string[];
export declare const wc: string[];
export declare const weightlifitng: string[];
export declare const wheelchair: string[];
export declare const wifiSignal0: string[];
export declare const wifiSignal1: string[];
export declare const wifiSignal2: string[];
export declare const wifiSignal4: string[];
export declare const wifiSignalOff: string[];
export declare const windowMaximize: string[];
export declare const windowMinimize: string[];
export declare const windowRestore: string[];
export declare const window: string[];
export declare const wrapText: string[];
export declare const xCircle: string[];
export declare const x: string[];
export declare const yen: string[];
export declare const zoomIn: string[];
export declare const zoomOut: string[];
